
# SPDX-License-Identifier: GPL-2.0+

obmm-y := obmm_core.o \
	obmm_shm_dev.o obmm_sysfs_ub.o obmm_cache.o obmm_import.o \
	obmm_export_from_user.o obmm_ownership.o conti_mem_allocator.o \
	obmm_export.o obmm_export_from_pool.o obmm_preimport.o \
	ubmempool_allocator.o obmm_lowmem.o obmm_export_region_ops.o \
	obmm_addr_check.o obmm_preimport_prefilled.o obmm_resource.o

obj-$(CONFIG_OBMM) += obmm.o
