/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _PS3_KERNEL_VERSION_H_
#define _PS3_KERNEL_VERSION_H_

#define PS3_STRSCPY
#define PS3_KMAP_LOCAL
#define PS3_KUNMAP_LOCAL
#define DRIVER_SUPPORT_PRIV_BUSY
#define PS3_HOST_ATTRS
#define PS3_TRACK_QUEUE_DEPTH
#define PS3_RESET_TIMER
#define PS3_FALLTHROUGH
#define PS3_SCMD_IO_DONE
#define PS3_SCMD_GET_REQUEST
#define PS3_SYPPORT_BIO_ITER
#define PS3_AER_CLEAR_STATUS
#define PS3_LINUX_SIGNAL
#define PS3_SUPPORT_TAGSET
#define DRIVER_SUPPORT_KERNEL_IRQ_AFFINITY
#define PS3_OS_MANAGED_IRQ_SUPPORT
#define PS3_MAP_QUEUES
#include <linux/blk-mq-pci.h>
#ifndef PS3_TAGSET_SUPPORT
#define PS3_TAGSET_SUPPORT
#endif
#define PS3_VFS_WRITE
#define PS3_FORCE_UACCESS
#define PS3_FSNOTIFY_FILE
#define PS3_KERNEL_WRITE_FILE
#define PS3_BLK_QUEUE_FLAG_CLEAR

#endif
