# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Motor-comm Corporation.
#
# Makefile for the Motorcomm(R) 6801 PCI-Express ethernet driver
#

obj-$(CONFIG_YT6801) += yt6801.o
yt6801-objs :=  yt6801_desc.o  yt6801_main.o
