# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_KUNPENG_HCCS)	+= kunpeng_hccs.o

obj-$(CONFIG_HISI_HBMDEV)	+= hisi_hbmdev.o
obj-$(CONFIG_HISI_HBMCACHE)	+= hisi_hbmcache.o

obj-$(CONFIG_HISI_SOC_CACHE)	+= hisi_soc_cache_framework.o
obj-$(CONFIG_HISI_SOC_HHA)	+= hisi_soc_hha.o
obj-$(CONFIG_HISI_SOC_L3C)	+= hisi_soc_l3c.o
