# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel UB device drivers.
#

ipourma-objs := \
ipourma_main.o \
ipourma_netdev.o \
ipourma_res.o \
ipourma_ub.o \
ipourma_err.o \
ipourma_addr_res.o \
ipourma_ip.o \
ipourma_ethtool.o \
ipourma_netlink.o \
ipourma_utils.o \
ipourma_sysfs.o \
ipourma_fs.o \

obj-$(CONFIG_UB_URMA) += ipourma.o
