/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_FEM_H
#define NBL_FEM_H 1

#include <linux/types.h>

#define NBL_FEM_BASE (0x00A04000)

#define NBL_FEM_INT_STATUS_ADDR  (0xa04000)
#define NBL_FEM_INT_STATUS_DEPTH (1)
#define NBL_FEM_INT_STATUS_WIDTH (32)
#define NBL_FEM_INT_STATUS_DWLEN (1)
union fem_int_status_u {
	struct fem_int_status {
		u32 rsv3:2;              /* [01:00] Default:0x0 RO */
		u32 fifo_ovf_err:1;      /* [02:02] Default:0x0 RWC */
		u32 fifo_udf_err:1;      /* [03:03] Default:0x0 RWC */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 bank_cflt_err:1;     /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_INT_STATUS_DWLEN];
} __packed;

#define NBL_FEM_INT_MASK_ADDR  (0xa04004)
#define NBL_FEM_INT_MASK_DEPTH (1)
#define NBL_FEM_INT_MASK_WIDTH (32)
#define NBL_FEM_INT_MASK_DWLEN (1)
union fem_int_mask_u {
	struct fem_int_mask {
		u32 rsv3:2;              /* [01:00] Default:0x0 RO */
		u32 fifo_ovf_err:1;      /* [02:02] Default:0x0 RW */
		u32 fifo_udf_err:1;      /* [03:03] Default:0x0 RW */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 bank_cflt_err:1;     /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_INT_MASK_DWLEN];
} __packed;

#define NBL_FEM_INT_SET_ADDR  (0xa04008)
#define NBL_FEM_INT_SET_DEPTH (1)
#define NBL_FEM_INT_SET_WIDTH (32)
#define NBL_FEM_INT_SET_DWLEN (1)
union fem_int_set_u {
	struct fem_int_set {
		u32 rsv3:2;              /* [01:00] Default:0x0 RO */
		u32 fifo_ovf_err:1;      /* [02:02] Default:0x0 WO */
		u32 fifo_udf_err:1;      /* [03:03] Default:0x0 WO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 bank_cflt_err:1;     /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_INT_SET_DWLEN];
} __packed;

#define NBL_FEM_INIT_DONE_ADDR  (0xa0400c)
#define NBL_FEM_INIT_DONE_DEPTH (1)
#define NBL_FEM_INIT_DONE_WIDTH (32)
#define NBL_FEM_INIT_DONE_DWLEN (1)
union fem_init_done_u {
	struct fem_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_INIT_DONE_DWLEN];
} __packed;

#define NBL_FEM_CIF_ERR_INFO_ADDR  (0xa04040)
#define NBL_FEM_CIF_ERR_INFO_DEPTH (1)
#define NBL_FEM_CIF_ERR_INFO_WIDTH (32)
#define NBL_FEM_CIF_ERR_INFO_DWLEN (1)
union fem_cif_err_info_u {
	struct fem_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_FEM_CFG_ERR_INFO_ADDR  (0xa04068)
#define NBL_FEM_CFG_ERR_INFO_DEPTH (1)
#define NBL_FEM_CFG_ERR_INFO_WIDTH (32)
#define NBL_FEM_CFG_ERR_INFO_DWLEN (1)
union fem_cfg_err_info_u {
	struct fem_cfg_err_info {
		u32 addr:24;             /* [23:00] Default:0x0 RO */
		u32 id:8;                /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_FEM_BANK_CFLT_ERR_INFO0_ADDR  (0xa04074)
#define NBL_FEM_BANK_CFLT_ERR_INFO0_DEPTH (1)
#define NBL_FEM_BANK_CFLT_ERR_INFO0_WIDTH (32)
#define NBL_FEM_BANK_CFLT_ERR_INFO0_DWLEN (1)
union fem_bank_cflt_err_info0_u {
	struct fem_bank_cflt_err_info0 {
		u32 addr0:24;            /* [23:00] Default:0x0 RO */
		u32 id:8;                /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_BANK_CFLT_ERR_INFO0_DWLEN];
} __packed;

#define NBL_FEM_BANK_CFLT_ERR_INFO1_ADDR  (0xa04078)
#define NBL_FEM_BANK_CFLT_ERR_INFO1_DEPTH (1)
#define NBL_FEM_BANK_CFLT_ERR_INFO1_WIDTH (32)
#define NBL_FEM_BANK_CFLT_ERR_INFO1_DWLEN (1)
union fem_bank_cflt_err_info1_u {
	struct fem_bank_cflt_err_info1 {
		u32 addr1:24;            /* [23:00] Default:0x0 RO */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_BANK_CFLT_ERR_INFO1_DWLEN];
} __packed;

#define NBL_FEM_CAR_CTRL_ADDR  (0xa04100)
#define NBL_FEM_CAR_CTRL_DEPTH (1)
#define NBL_FEM_CAR_CTRL_WIDTH (32)
#define NBL_FEM_CAR_CTRL_DWLEN (1)
union fem_car_ctrl_u {
	struct fem_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CAR_CTRL_DWLEN];
} __packed;

#define NBL_FEM_BP_TH_ADDR  (0xa04118)
#define NBL_FEM_BP_TH_DEPTH (1)
#define NBL_FEM_BP_TH_WIDTH (32)
#define NBL_FEM_BP_TH_DWLEN (1)
union fem_bp_th_u {
	struct fem_bp_th {
		u32 th:12;               /* [11:00] Default:0xf RW */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_BP_TH_DWLEN];
} __packed;

#define NBL_FEM_HT_BANK_SEL_BTM_ADDR  (0xa0411c)
#define NBL_FEM_HT_BANK_SEL_BTM_DEPTH (1)
#define NBL_FEM_HT_BANK_SEL_BTM_WIDTH (32)
#define NBL_FEM_HT_BANK_SEL_BTM_DWLEN (1)
union fem_ht_bank_sel_btm_u {
	struct fem_ht_bank_sel_btm {
		u32 port0_ht_depth:5;    /* [04:00] Default:0x8 RW */
		u32 rsv2:3;              /* [07:05] Default:0x0 RO */
		u32 port1_ht_depth:5;    /* [12:08] Default:0x8 RW */
		u32 rsv1:3;              /* [15:13] Default:0x0 RO */
		u32 port2_ht_depth:5;    /* [20:16] Default:0x8 RW */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_HT_BANK_SEL_BTM_DWLEN];
} __packed;

#define NBL_FEM_INIT_START_ADDR  (0xa04180)
#define NBL_FEM_INIT_START_DEPTH (1)
#define NBL_FEM_INIT_START_WIDTH (32)
#define NBL_FEM_INIT_START_DWLEN (1)
union fem_init_start_u {
	struct fem_init_start {
		u32 start:1;             /* [00:00] Default:0x0 WO */
		u32 ht_bank_init:7;      /* [07:01] Default:0x0 WO */
		u32 rsv:24;              /* [31:08] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_INIT_START_DWLEN];
} __packed;

#define NBL_FEM_MHASH_ADDR  (0xa04188)
#define NBL_FEM_MHASH_DEPTH (1)
#define NBL_FEM_MHASH_WIDTH (32)
#define NBL_FEM_MHASH_DWLEN (1)
union fem_mhash_u {
	struct fem_mhash {
		u32 mod_action_id:6;     /* [05:00] Default:0x12 RW */
		u32 hash0_action_id:6;   /* [11:06] Default:0x13 RW */
		u32 hash1_action_id:6;   /* [17:12] Default:0x14 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_MHASH_DWLEN];
} __packed;

#define NBL_FEM_CPU_ACCESS_CFG_ADDR  (0xa04190)
#define NBL_FEM_CPU_ACCESS_CFG_DEPTH (1)
#define NBL_FEM_CPU_ACCESS_CFG_WIDTH (32)
#define NBL_FEM_CPU_ACCESS_CFG_DWLEN (1)
union fem_cpu_access_cfg_u {
	struct fem_cpu_access_cfg {
		u32 cpu_access_bp_th:8;  /* [7:0] Default:0xf RW */
		u32 rsv1:8;              /* [15:8] Default:0x0 RO */
		u32 cpu_access_timeout_th:10; /* [25:16] Default:0x50 RW */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CPU_ACCESS_CFG_DWLEN];
} __packed;

#define NBL_FEM_HT_BANK_SEL_BITMAP_ADDR  (0xa04200)
#define NBL_FEM_HT_BANK_SEL_BITMAP_DEPTH (1)
#define NBL_FEM_HT_BANK_SEL_BITMAP_WIDTH (32)
#define NBL_FEM_HT_BANK_SEL_BITMAP_DWLEN (1)
union fem_ht_bank_sel_bitmap_u {
	struct fem_ht_bank_sel_bitmap {
		u32 port0_bank_sel:8;    /* [7:0] Default:0x1 RW */
		u32 port1_bank_sel:8;    /* [15:8] Default:0x6 RW */
		u32 port2_bank_sel:8;    /* [23:16] Default:0x78 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_HT_BANK_SEL_BITMAP_DWLEN];
} __packed;

#define NBL_FEM_KT_BANK_SEL_BITMAP_ADDR  (0xa04204)
#define NBL_FEM_KT_BANK_SEL_BITMAP_DEPTH (1)
#define NBL_FEM_KT_BANK_SEL_BITMAP_WIDTH (32)
#define NBL_FEM_KT_BANK_SEL_BITMAP_DWLEN (1)
union fem_kt_bank_sel_bitmap_u {
	struct fem_kt_bank_sel_bitmap {
		u32 port0_bank_sel:8;    /* [7:0] Default:0x1 RW */
		u32 port1_bank_sel:8;    /* [15:8] Default:0x6 RW */
		u32 port2_bank_sel:8;    /* [23:16] Default:0xF8 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_KT_BANK_SEL_BITMAP_DWLEN];
} __packed;

#define NBL_FEM_AT_BANK_SEL_BITMAP_ADDR  (0xa04208)
#define NBL_FEM_AT_BANK_SEL_BITMAP_DEPTH (1)
#define NBL_FEM_AT_BANK_SEL_BITMAP_WIDTH (32)
#define NBL_FEM_AT_BANK_SEL_BITMAP_DWLEN (1)
union fem_at_bank_sel_bitmap_u {
	struct fem_at_bank_sel_bitmap {
		u32 port0_bank_sel:12;   /* [11:0] Default:0x3 RW */
		u32 rsv1:4;              /* [15:12] Default:0x0 RO */
		u32 port1_bank_sel:12;   /* [27:16] Default:0x1C RW */
		u32 rsv:4;               /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AT_BANK_SEL_BITMAP_DWLEN];
} __packed;

#define NBL_FEM_AT_BANK_SEL_BITMAP2_ADDR  (0xa0420c)
#define NBL_FEM_AT_BANK_SEL_BITMAP2_DEPTH (1)
#define NBL_FEM_AT_BANK_SEL_BITMAP2_WIDTH (32)
#define NBL_FEM_AT_BANK_SEL_BITMAP2_DWLEN (1)
union fem_at_bank_sel_bitmap2_u {
	struct fem_at_bank_sel_bitmap2 {
		u32 port2_bank_sel:12;   /* [11:0] Default:0xFE0 RW */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AT_BANK_SEL_BITMAP2_DWLEN];
} __packed;

#define NBL_FEM_AGE_EN_ADDR  (0xa04210)
#define NBL_FEM_AGE_EN_DEPTH (1)
#define NBL_FEM_AGE_EN_WIDTH (32)
#define NBL_FEM_AGE_EN_DWLEN (1)
union fem_age_en_u {
	struct fem_age_en {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AGE_EN_DWLEN];
} __packed;

#define NBL_FEM_AGE_HARD_STEP_ADDR  (0xa04214)
#define NBL_FEM_AGE_HARD_STEP_DEPTH (1)
#define NBL_FEM_AGE_HARD_STEP_WIDTH (32)
#define NBL_FEM_AGE_HARD_STEP_DWLEN (1)
union fem_age_hard_step_u {
	struct fem_age_hard_step {
		u32 data:3;              /* [2:0] Default:0x6 RW */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AGE_HARD_STEP_DWLEN];
} __packed;

#define NBL_FEM_AGE_TIME_UNIT_ADDR  (0xa04218)
#define NBL_FEM_AGE_TIME_UNIT_DEPTH (1)
#define NBL_FEM_AGE_TIME_UNIT_WIDTH (32)
#define NBL_FEM_AGE_TIME_UNIT_DWLEN (1)
union fem_age_time_unit_u {
	struct fem_age_time_unit {
		u32 data:32;             /* [31:0] Default:0x17CB5 RW */
	} __packed info;
	u32 data[NBL_FEM_AGE_TIME_UNIT_DWLEN];
} __packed;

#define NBL_FEM_AGE_INFO_HEAD_ADDR  (0xa04220)
#define NBL_FEM_AGE_INFO_HEAD_DEPTH (1)
#define NBL_FEM_AGE_INFO_HEAD_WIDTH (32)
#define NBL_FEM_AGE_INFO_HEAD_DWLEN (1)
union fem_age_info_head_u {
	struct fem_age_info_head {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_FEM_AGE_INFO_HEAD_DWLEN];
} __packed;

#define NBL_FEM_KEY_IN_ADDR  (0xa04240)
#define NBL_FEM_KEY_IN_DEPTH (1)
#define NBL_FEM_KEY_IN_WIDTH (32)
#define NBL_FEM_KEY_IN_DWLEN (1)
union fem_key_in_u {
	struct fem_key_in {
		u32 em0_cap_mode:1;      /* [0:0] Default:0x1 RW */
		u32 em1_cap_mode:1;      /* [01:01] Default:0x1 RW */
		u32 em2_cap_mode:1;      /* [02:02] Default:0x1 RW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_KEY_IN_DWLEN];
} __packed;

#define NBL_FEM_CAP_ADDR  (0xa04244)
#define NBL_FEM_CAP_DEPTH (1)
#define NBL_FEM_CAP_WIDTH (32)
#define NBL_FEM_CAP_DWLEN (1)
union fem_cap_u {
	struct fem_cap {
		u32 em0_cap_start:1;     /* [0:0] Default:0x0 WO */
		u32 em1_cap_start:1;     /* [01:01] Default:0x0 WO */
		u32 em2_cap_start:1;     /* [02:02] Default:0x0 WO */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CAP_DWLEN];
} __packed;

#define NBL_FEM_HT_ACCESS_CTRL_ADDR  (0xa04300)
#define NBL_FEM_HT_ACCESS_CTRL_DEPTH (1)
#define NBL_FEM_HT_ACCESS_CTRL_WIDTH (32)
#define NBL_FEM_HT_ACCESS_CTRL_DWLEN (1)
union fem_ht_access_ctrl_u {
	struct fem_ht_access_ctrl {
		u32 addr:17;             /* [16:00] Default:0x0 RW */
		u32 port:2;              /* [18:17] Default:0x0 RW */
		u32 rsv:10;              /* [28:19] Default:0x0 RO */
		u32 access_size:1;       /* [29:29] Default:0x0 RW */
		u32 rw:1;                /* [30:30] Default:0x0 RW */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_HT_ACCESS_CTRL_DWLEN];
} __packed;

#define NBL_FEM_HT_ACCESS_ACK_ADDR  (0xa04304)
#define NBL_FEM_HT_ACCESS_ACK_DEPTH (1)
#define NBL_FEM_HT_ACCESS_ACK_WIDTH (32)
#define NBL_FEM_HT_ACCESS_ACK_DWLEN (1)
union fem_ht_access_ack_u {
	struct fem_ht_access_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:1;            /* [01:01] Default:0x0 RWW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_HT_ACCESS_ACK_DWLEN];
} __packed;

#define NBL_FEM_HT_ACCESS_DATA_ADDR  (0xa04308)
#define NBL_FEM_HT_ACCESS_DATA_DEPTH (4)
#define NBL_FEM_HT_ACCESS_DATA_WIDTH (32)
#define NBL_FEM_HT_ACCESS_DATA_DWLEN (1)
union fem_ht_access_data_u {
	struct fem_ht_access_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_HT_ACCESS_DATA_DWLEN];
} __packed;
#define NBL_FEM_HT_ACCESS_DATA_REG(r) (NBL_FEM_HT_ACCESS_DATA_ADDR + \
		(NBL_FEM_HT_ACCESS_DATA_DWLEN * 4) * (r))

#define NBL_FEM_KT_ACCESS_CTRL_ADDR  (0xa04340)
#define NBL_FEM_KT_ACCESS_CTRL_DEPTH (1)
#define NBL_FEM_KT_ACCESS_CTRL_WIDTH (32)
#define NBL_FEM_KT_ACCESS_CTRL_DWLEN (1)
union fem_kt_access_ctrl_u {
	struct fem_kt_access_ctrl {
		u32 addr:17;             /* [16:00] Default:0x0 RW */
		u32 rsv:12;              /* [28:17] Default:0x0 RO */
		u32 access_size:1;       /* [29:29] Default:0x0 RW */
		u32 rw:1;                /* [30:30] Default:0x0 RW */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_KT_ACCESS_CTRL_DWLEN];
} __packed;

#define NBL_FEM_KT_ACCESS_ACK_ADDR  (0xa04344)
#define NBL_FEM_KT_ACCESS_ACK_DEPTH (1)
#define NBL_FEM_KT_ACCESS_ACK_WIDTH (32)
#define NBL_FEM_KT_ACCESS_ACK_DWLEN (1)
union fem_kt_access_ack_u {
	struct fem_kt_access_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:1;            /* [01:01] Default:0x0 RWW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_KT_ACCESS_ACK_DWLEN];
} __packed;

#define NBL_FEM_KT_ACCESS_DATA_ADDR  (0xa04348)
#define NBL_FEM_KT_ACCESS_DATA_DEPTH (10)
#define NBL_FEM_KT_ACCESS_DATA_WIDTH (32)
#define NBL_FEM_KT_ACCESS_DATA_DWLEN (1)
union fem_kt_access_data_u {
	struct fem_kt_access_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_KT_ACCESS_DATA_DWLEN];
} __packed;
#define NBL_FEM_KT_ACCESS_DATA_REG(r) (NBL_FEM_KT_ACCESS_DATA_ADDR + \
		(NBL_FEM_KT_ACCESS_DATA_DWLEN * 4) * (r))

#define NBL_FEM_AT_ACCESS_CTRL_ADDR  (0xa04390)
#define NBL_FEM_AT_ACCESS_CTRL_DEPTH (1)
#define NBL_FEM_AT_ACCESS_CTRL_WIDTH (32)
#define NBL_FEM_AT_ACCESS_CTRL_DWLEN (1)
union fem_at_access_ctrl_u {
	struct fem_at_access_ctrl {
		u32 addr:17;             /* [16:00] Default:0x0 RW */
		u32 rsv:12;              /* [28:17] Default:0x0 RO */
		u32 access_size:1;       /* [29:29] Default:0x0 RW */
		u32 rw:1;                /* [30:30] Default:0x0 RW */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_AT_ACCESS_CTRL_DWLEN];
} __packed;

#define NBL_FEM_AT_ACCESS_ACK_ADDR  (0xa04394)
#define NBL_FEM_AT_ACCESS_ACK_DEPTH (1)
#define NBL_FEM_AT_ACCESS_ACK_WIDTH (32)
#define NBL_FEM_AT_ACCESS_ACK_DWLEN (1)
union fem_at_access_ack_u {
	struct fem_at_access_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:1;            /* [01:01] Default:0x0 RWW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AT_ACCESS_ACK_DWLEN];
} __packed;

#define NBL_FEM_AT_ACCESS_DATA_ADDR  (0xa04398)
#define NBL_FEM_AT_ACCESS_DATA_DEPTH (6)
#define NBL_FEM_AT_ACCESS_DATA_WIDTH (32)
#define NBL_FEM_AT_ACCESS_DATA_DWLEN (1)
union fem_at_access_data_u {
	struct fem_at_access_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_AT_ACCESS_DATA_DWLEN];
} __packed;
#define NBL_FEM_AT_ACCESS_DATA_REG(r) (NBL_FEM_AT_ACCESS_DATA_ADDR + \
		(NBL_FEM_AT_ACCESS_DATA_DWLEN * 4) * (r))

#define NBL_FEM_AGE_TBL_ACCESS_CTRL_ADDR  (0xa04400)
#define NBL_FEM_AGE_TBL_ACCESS_CTRL_DEPTH (1)
#define NBL_FEM_AGE_TBL_ACCESS_CTRL_WIDTH (32)
#define NBL_FEM_AGE_TBL_ACCESS_CTRL_DWLEN (1)
union fem_age_tbl_access_ctrl_u {
	struct fem_age_tbl_access_ctrl {
		u32 addr:17;             /* [16:0] Default:0x0 RW */
		u32 rsv:13;              /* [29:17] Default:0x0 RO */
		u32 rw:1;                /* [30:30] Default:0x0 RW */
		u32 start:1;             /* [31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_AGE_TBL_ACCESS_CTRL_DWLEN];
} __packed;

#define NBL_FEM_AGE_TBL_ACCESS_ACK_ADDR  (0xa04404)
#define NBL_FEM_AGE_TBL_ACCESS_ACK_DEPTH (1)
#define NBL_FEM_AGE_TBL_ACCESS_ACK_WIDTH (32)
#define NBL_FEM_AGE_TBL_ACCESS_ACK_DWLEN (1)
union fem_age_tbl_access_ack_u {
	struct fem_age_tbl_access_ack {
		u32 done:1;              /* [0] Default:0x0 RC */
		u32 status:1;            /* [1] Default:0x0 RWW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_AGE_TBL_ACCESS_ACK_DWLEN];
} __packed;

#define NBL_FEM_AGE_TBL_ACCESS_DATA_ADDR  (0xa04408)
#define NBL_FEM_AGE_TBL_ACCESS_DATA_DEPTH (12)
#define NBL_FEM_AGE_TBL_ACCESS_DATA_WIDTH (32)
#define NBL_FEM_AGE_TBL_ACCESS_DATA_DWLEN (1)
union fem_age_tbl_access_data_u {
	struct fem_age_tbl_access_data {
		u32 data:32;             /* [31:0] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_AGE_TBL_ACCESS_DATA_DWLEN];
} __packed;
#define NBL_FEM_AGE_TBL_ACCESS_DATA_REG(r) (NBL_FEM_AGE_TBL_ACCESS_DATA_ADDR + \
		(NBL_FEM_AGE_TBL_ACCESS_DATA_DWLEN * 4) * (r))

#define NBL_FEM_CPU_INSERT_SEARCH0_CTRL_ADDR  (0xa04500)
#define NBL_FEM_CPU_INSERT_SEARCH0_CTRL_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH0_CTRL_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH0_CTRL_DWLEN (1)
union fem_cpu_insert_search0_ctrl_u {
	struct fem_cpu_insert_search0_ctrl {
		u32 rsv:31;              /* [30:00] Default:0x0 RO */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH0_CTRL_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH0_ACK_ADDR  (0xa04504)
#define NBL_FEM_CPU_INSERT_SEARCH0_ACK_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH0_ACK_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH0_ACK_DWLEN (1)
union fem_cpu_insert_search0_ack_u {
	struct fem_cpu_insert_search0_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:2;            /* [02:01] Default:0x0 RWW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH0_ACK_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH0_DATA_ADDR  (0xa04508)
#define NBL_FEM_CPU_INSERT_SEARCH0_DATA_DEPTH (11)
#define NBL_FEM_CPU_INSERT_SEARCH0_DATA_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH0_DATA_DWLEN (1)
union fem_cpu_insert_search0_data_u {
	struct fem_cpu_insert_search0_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH0_DATA_DWLEN];
} __packed;
#define NBL_FEM_CPU_INSERT_SEARCH0_DATA_REG(r) (NBL_FEM_CPU_INSERT_SEARCH0_DATA_ADDR + \
		(NBL_FEM_CPU_INSERT_SEARCH0_DATA_DWLEN * 4) * (r))

#define NBL_FEM_CPU_INSERT_SEARCH1_CTRL_ADDR  (0xa04550)
#define NBL_FEM_CPU_INSERT_SEARCH1_CTRL_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH1_CTRL_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH1_CTRL_DWLEN (1)
union fem_cpu_insert_search1_ctrl_u {
	struct fem_cpu_insert_search1_ctrl {
		u32 rsv:31;              /* [30:00] Default:0x0 RO */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH1_CTRL_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH1_ACK_ADDR  (0xa04554)
#define NBL_FEM_CPU_INSERT_SEARCH1_ACK_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH1_ACK_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH1_ACK_DWLEN (1)
union fem_cpu_insert_search1_ack_u {
	struct fem_cpu_insert_search1_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:2;            /* [02:01] Default:0x0 RWW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH1_ACK_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH1_DATA_ADDR  (0xa04558)
#define NBL_FEM_CPU_INSERT_SEARCH1_DATA_DEPTH (11)
#define NBL_FEM_CPU_INSERT_SEARCH1_DATA_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH1_DATA_DWLEN (1)
union fem_cpu_insert_search1_data_u {
	struct fem_cpu_insert_search1_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH1_DATA_DWLEN];
} __packed;
#define NBL_FEM_CPU_INSERT_SEARCH1_DATA_REG(r) (NBL_FEM_CPU_INSERT_SEARCH1_DATA_ADDR + \
		(NBL_FEM_CPU_INSERT_SEARCH1_DATA_DWLEN * 4) * (r))

#define NBL_FEM_CPU_INSERT_SEARCH2_CTRL_ADDR  (0xa045a0)
#define NBL_FEM_CPU_INSERT_SEARCH2_CTRL_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH2_CTRL_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH2_CTRL_DWLEN (1)
union fem_cpu_insert_search2_ctrl_u {
	struct fem_cpu_insert_search2_ctrl {
		u32 rsv:31;              /* [30:00] Default:0x0 RO */
		u32 start:1;             /* [31:31] Default:0x0 WO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH2_CTRL_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH2_ACK_ADDR  (0xa045a4)
#define NBL_FEM_CPU_INSERT_SEARCH2_ACK_DEPTH (1)
#define NBL_FEM_CPU_INSERT_SEARCH2_ACK_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH2_ACK_DWLEN (1)
union fem_cpu_insert_search2_ack_u {
	struct fem_cpu_insert_search2_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:2;            /* [02:01] Default:0x0 RWW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH2_ACK_DWLEN];
} __packed;

#define NBL_FEM_CPU_INSERT_SEARCH2_DATA_ADDR  (0xa045a8)
#define NBL_FEM_CPU_INSERT_SEARCH2_DATA_DEPTH (11)
#define NBL_FEM_CPU_INSERT_SEARCH2_DATA_WIDTH (32)
#define NBL_FEM_CPU_INSERT_SEARCH2_DATA_DWLEN (1)
union fem_cpu_insert_search2_data_u {
	struct fem_cpu_insert_search2_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_FEM_CPU_INSERT_SEARCH2_DATA_DWLEN];
} __packed;
#define NBL_FEM_CPU_INSERT_SEARCH2_DATA_REG(r) (NBL_FEM_CPU_INSERT_SEARCH2_DATA_ADDR + \
		(NBL_FEM_CPU_INSERT_SEARCH2_DATA_DWLEN * 4) * (r))

#define NBL_FEM_CFG_TEST_ADDR  (0xa0480c)
#define NBL_FEM_CFG_TEST_DEPTH (1)
#define NBL_FEM_CFG_TEST_WIDTH (32)
#define NBL_FEM_CFG_TEST_DWLEN (1)
union fem_cfg_test_u {
	struct fem_cfg_test {
		u32 test:32;             /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_FEM_CFG_TEST_DWLEN];
} __packed;

#define NBL_FEM_RCV_CMDQ_ADDR  (0xa04818)
#define NBL_FEM_RCV_CMDQ_DEPTH (1)
#define NBL_FEM_RCV_CMDQ_WIDTH (32)
#define NBL_FEM_RCV_CMDQ_DWLEN (1)
union fem_rcv_cmdq_u {
	struct fem_rcv_cmdq {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_RCV_CMDQ_DWLEN];
} __packed;

#define NBL_FEM_SND_CMDQ_ADDR  (0xa0481c)
#define NBL_FEM_SND_CMDQ_DEPTH (1)
#define NBL_FEM_SND_CMDQ_WIDTH (32)
#define NBL_FEM_SND_CMDQ_DWLEN (1)
union fem_snd_cmdq_u {
	struct fem_snd_cmdq {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_SND_CMDQ_DWLEN];
} __packed;

#define NBL_FEM_CMDQ_PRO_ADDR  (0xa04820)
#define NBL_FEM_CMDQ_PRO_DEPTH (1)
#define NBL_FEM_CMDQ_PRO_WIDTH (32)
#define NBL_FEM_CMDQ_PRO_DWLEN (1)
union fem_cmdq_pro_u {
	struct fem_cmdq_pro {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_CMDQ_PRO_DWLEN];
} __packed;

#define NBL_FEM_PP0_REQ_ADDR  (0xa04850)
#define NBL_FEM_PP0_REQ_DEPTH (1)
#define NBL_FEM_PP0_REQ_WIDTH (32)
#define NBL_FEM_PP0_REQ_DWLEN (1)
union fem_pp0_req_u {
	struct fem_pp0_req {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP0_REQ_DWLEN];
} __packed;

#define NBL_FEM_PP0_ALL_RSP_ADDR  (0xa04854)
#define NBL_FEM_PP0_ALL_RSP_DEPTH (1)
#define NBL_FEM_PP0_ALL_RSP_WIDTH (32)
#define NBL_FEM_PP0_ALL_RSP_DWLEN (1)
union fem_pp0_all_rsp_u {
	struct fem_pp0_all_rsp {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP0_ALL_RSP_DWLEN];
} __packed;

#define NBL_FEM_PP0_RSP_ADDR  (0xa04858)
#define NBL_FEM_PP0_RSP_DEPTH (1)
#define NBL_FEM_PP0_RSP_WIDTH (32)
#define NBL_FEM_PP0_RSP_DWLEN (1)
union fem_pp0_rsp_u {
	struct fem_pp0_rsp {
		u32 miss_cnt:16;         /* [15:00] Default:0x0 RCTR */
		u32 err_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP0_RSP_DWLEN];
} __packed;

#define NBL_FEM_EM0_HT_LOOKUP_ADDR  (0xa04878)
#define NBL_FEM_EM0_HT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM0_HT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM0_HT_LOOKUP_DWLEN (1)
union fem_em0_ht_lookup_u {
	struct fem_em0_ht_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_HT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM0_HT_HIT_ADDR  (0xa0487c)
#define NBL_FEM_EM0_HT_HIT_DEPTH (1)
#define NBL_FEM_EM0_HT_HIT_WIDTH (32)
#define NBL_FEM_EM0_HT_HIT_DWLEN (1)
union fem_em0_ht_hit_u {
	struct fem_em0_ht_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_HT_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM0_TCAM_LOOKUP_ADDR  (0xa04880)
#define NBL_FEM_EM0_TCAM_LOOKUP_DEPTH (1)
#define NBL_FEM_EM0_TCAM_LOOKUP_WIDTH (32)
#define NBL_FEM_EM0_TCAM_LOOKUP_DWLEN (1)
union fem_em0_tcam_lookup_u {
	struct fem_em0_tcam_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_TCAM_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM0_TCAM_HIT_ADDR  (0xa04884)
#define NBL_FEM_EM0_TCAM_HIT_DEPTH (1)
#define NBL_FEM_EM0_TCAM_HIT_WIDTH (32)
#define NBL_FEM_EM0_TCAM_HIT_DWLEN (1)
union fem_em0_tcam_hit_u {
	struct fem_em0_tcam_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_TCAM_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM0_KT_LOOKUP_ADDR  (0xa04888)
#define NBL_FEM_EM0_KT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM0_KT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM0_KT_LOOKUP_DWLEN (1)
union fem_em0_kt_lookup_u {
	struct fem_em0_kt_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_KT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM0_KT_HIT_ADDR  (0xa0488c)
#define NBL_FEM_EM0_KT_HIT_DEPTH (1)
#define NBL_FEM_EM0_KT_HIT_WIDTH (32)
#define NBL_FEM_EM0_KT_HIT_DWLEN (1)
union fem_em0_kt_hit_u {
	struct fem_em0_kt_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_KT_HIT_DWLEN];
} __packed;

#define NBL_FEM_PP1_REQ_ADDR  (0xa048b0)
#define NBL_FEM_PP1_REQ_DEPTH (1)
#define NBL_FEM_PP1_REQ_WIDTH (32)
#define NBL_FEM_PP1_REQ_DWLEN (1)
union fem_pp1_req_u {
	struct fem_pp1_req {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP1_REQ_DWLEN];
} __packed;

#define NBL_FEM_PP1_ALL_RSP_ADDR  (0xa048b4)
#define NBL_FEM_PP1_ALL_RSP_DEPTH (1)
#define NBL_FEM_PP1_ALL_RSP_WIDTH (32)
#define NBL_FEM_PP1_ALL_RSP_DWLEN (1)
union fem_pp1_all_rsp_u {
	struct fem_pp1_all_rsp {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP1_ALL_RSP_DWLEN];
} __packed;

#define NBL_FEM_PP1_RSP_ADDR  (0xa048b8)
#define NBL_FEM_PP1_RSP_DEPTH (1)
#define NBL_FEM_PP1_RSP_WIDTH (32)
#define NBL_FEM_PP1_RSP_DWLEN (1)
union fem_pp1_rsp_u {
	struct fem_pp1_rsp {
		u32 miss_cnt:16;         /* [15:00] Default:0x0 RCTR */
		u32 err_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP1_RSP_DWLEN];
} __packed;

#define NBL_FEM_EM1_HT_LOOKUP_ADDR  (0xa048d8)
#define NBL_FEM_EM1_HT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM1_HT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM1_HT_LOOKUP_DWLEN (1)
union fem_em1_ht_lookup_u {
	struct fem_em1_ht_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_HT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM1_HT_HIT_ADDR  (0xa048dc)
#define NBL_FEM_EM1_HT_HIT_DEPTH (1)
#define NBL_FEM_EM1_HT_HIT_WIDTH (32)
#define NBL_FEM_EM1_HT_HIT_DWLEN (1)
union fem_em1_ht_hit_u {
	struct fem_em1_ht_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_HT_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM1_TCAM_LOOKUP_ADDR  (0xa048e0)
#define NBL_FEM_EM1_TCAM_LOOKUP_DEPTH (1)
#define NBL_FEM_EM1_TCAM_LOOKUP_WIDTH (32)
#define NBL_FEM_EM1_TCAM_LOOKUP_DWLEN (1)
union fem_em1_tcam_lookup_u {
	struct fem_em1_tcam_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_TCAM_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM1_TCAM_HIT_ADDR  (0xa048e4)
#define NBL_FEM_EM1_TCAM_HIT_DEPTH (1)
#define NBL_FEM_EM1_TCAM_HIT_WIDTH (32)
#define NBL_FEM_EM1_TCAM_HIT_DWLEN (1)
union fem_em1_tcam_hit_u {
	struct fem_em1_tcam_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_TCAM_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM1_KT_LOOKUP_ADDR  (0xa048e8)
#define NBL_FEM_EM1_KT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM1_KT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM1_KT_LOOKUP_DWLEN (1)
union fem_em1_kt_lookup_u {
	struct fem_em1_kt_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_KT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM1_KT_HIT_ADDR  (0xa048ec)
#define NBL_FEM_EM1_KT_HIT_DEPTH (1)
#define NBL_FEM_EM1_KT_HIT_WIDTH (32)
#define NBL_FEM_EM1_KT_HIT_DWLEN (1)
union fem_em1_kt_hit_u {
	struct fem_em1_kt_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_KT_HIT_DWLEN];
} __packed;

#define NBL_FEM_PP2_REQ_ADDR  (0xa04910)
#define NBL_FEM_PP2_REQ_DEPTH (1)
#define NBL_FEM_PP2_REQ_WIDTH (32)
#define NBL_FEM_PP2_REQ_DWLEN (1)
union fem_pp2_req_u {
	struct fem_pp2_req {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP2_REQ_DWLEN];
} __packed;

#define NBL_FEM_PP2_ALL_RSP_ADDR  (0xa04914)
#define NBL_FEM_PP2_ALL_RSP_DEPTH (1)
#define NBL_FEM_PP2_ALL_RSP_WIDTH (32)
#define NBL_FEM_PP2_ALL_RSP_DWLEN (1)
union fem_pp2_all_rsp_u {
	struct fem_pp2_all_rsp {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP2_ALL_RSP_DWLEN];
} __packed;

#define NBL_FEM_PP2_RSP_ADDR  (0xa04918)
#define NBL_FEM_PP2_RSP_DEPTH (1)
#define NBL_FEM_PP2_RSP_WIDTH (32)
#define NBL_FEM_PP2_RSP_DWLEN (1)
union fem_pp2_rsp_u {
	struct fem_pp2_rsp {
		u32 miss_cnt:16;         /* [15:00] Default:0x0 RCTR */
		u32 err_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_FEM_PP2_RSP_DWLEN];
} __packed;

#define NBL_FEM_EM2_HT_LOOKUP_ADDR  (0xa04938)
#define NBL_FEM_EM2_HT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM2_HT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM2_HT_LOOKUP_DWLEN (1)
union fem_em2_ht_lookup_u {
	struct fem_em2_ht_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_HT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM2_HT_HIT_ADDR  (0xa0493c)
#define NBL_FEM_EM2_HT_HIT_DEPTH (1)
#define NBL_FEM_EM2_HT_HIT_WIDTH (32)
#define NBL_FEM_EM2_HT_HIT_DWLEN (1)
union fem_em2_ht_hit_u {
	struct fem_em2_ht_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_HT_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM2_TCAM_LOOKUP_ADDR  (0xa04940)
#define NBL_FEM_EM2_TCAM_LOOKUP_DEPTH (1)
#define NBL_FEM_EM2_TCAM_LOOKUP_WIDTH (32)
#define NBL_FEM_EM2_TCAM_LOOKUP_DWLEN (1)
union fem_em2_tcam_lookup_u {
	struct fem_em2_tcam_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_TCAM_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM2_TCAM_HIT_ADDR  (0xa04944)
#define NBL_FEM_EM2_TCAM_HIT_DEPTH (1)
#define NBL_FEM_EM2_TCAM_HIT_WIDTH (32)
#define NBL_FEM_EM2_TCAM_HIT_DWLEN (1)
union fem_em2_tcam_hit_u {
	struct fem_em2_tcam_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_TCAM_HIT_DWLEN];
} __packed;

#define NBL_FEM_EM2_KT_LOOKUP_ADDR  (0xa04948)
#define NBL_FEM_EM2_KT_LOOKUP_DEPTH (1)
#define NBL_FEM_EM2_KT_LOOKUP_WIDTH (32)
#define NBL_FEM_EM2_KT_LOOKUP_DWLEN (1)
union fem_em2_kt_lookup_u {
	struct fem_em2_kt_lookup {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_KT_LOOKUP_DWLEN];
} __packed;

#define NBL_FEM_EM2_KT_HIT_ADDR  (0xa0494c)
#define NBL_FEM_EM2_KT_HIT_DEPTH (1)
#define NBL_FEM_EM2_KT_HIT_WIDTH (32)
#define NBL_FEM_EM2_KT_HIT_DWLEN (1)
union fem_em2_kt_hit_u {
	struct fem_em2_kt_hit {
		u32 cnt:16;              /* [15:00] Default:0x0 RCTR */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_KT_HIT_DWLEN];
} __packed;

#define NBL_FEM_AGE_INFO_DROP_ADDR  (0xa04950)
#define NBL_FEM_AGE_INFO_DROP_DEPTH (1)
#define NBL_FEM_AGE_INFO_DROP_WIDTH (32)
#define NBL_FEM_AGE_INFO_DROP_DWLEN (1)
union fem_age_info_drop_u {
	struct fem_age_info_drop {
		u32 cnt:32;              /* [31:00] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_FEM_AGE_INFO_DROP_DWLEN];
} __packed;

#define NBL_FEM_EM0_PP_KEY_CHANGE_ADDR  (0xa04954)
#define NBL_FEM_EM0_PP_KEY_CHANGE_DEPTH (1)
#define NBL_FEM_EM0_PP_KEY_CHANGE_WIDTH (32)
#define NBL_FEM_EM0_PP_KEY_CHANGE_DWLEN (1)
union fem_em0_pp_key_change_u {
	struct fem_em0_pp_key_change {
		u32 cnt:32;              /* [31:00] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_FEM_EM0_PP_KEY_CHANGE_DWLEN];
} __packed;

#define NBL_FEM_EM1_PP_KEY_CHANGE_ADDR  (0xa04958)
#define NBL_FEM_EM1_PP_KEY_CHANGE_DEPTH (1)
#define NBL_FEM_EM1_PP_KEY_CHANGE_WIDTH (32)
#define NBL_FEM_EM1_PP_KEY_CHANGE_DWLEN (1)
union fem_em1_pp_key_change_u {
	struct fem_em1_pp_key_change {
		u32 cnt:32;              /* [31:00] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_FEM_EM1_PP_KEY_CHANGE_DWLEN];
} __packed;

#define NBL_FEM_EM2_PP_KEY_CHANGE_ADDR  (0xa0495c)
#define NBL_FEM_EM2_PP_KEY_CHANGE_DEPTH (1)
#define NBL_FEM_EM2_PP_KEY_CHANGE_WIDTH (32)
#define NBL_FEM_EM2_PP_KEY_CHANGE_DWLEN (1)
union fem_em2_pp_key_change_u {
	struct fem_em2_pp_key_change {
		u32 cnt:32;              /* [31:00] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_FEM_EM2_PP_KEY_CHANGE_DWLEN];
} __packed;

#define NBL_FEM_BP_STATE_ADDR  (0xa04b00)
#define NBL_FEM_BP_STATE_DEPTH (1)
#define NBL_FEM_BP_STATE_WIDTH (32)
#define NBL_FEM_BP_STATE_DWLEN (1)
union fem_bp_state_u {
	struct fem_bp_state {
		u32 fem_pp0_bp:1;        /* [00:00] Default:0x0 RO */
		u32 fem_pp1_bp:1;        /* [01:01] Default:0x0 RO */
		u32 fem_pp2_bp:1;        /* [02:02] Default:0x0 RO */
		u32 up_cmdq_bp:1;        /* [03:03] Default:0x0 RO */
		u32 dn_acl_cmdq_bp:1;    /* [04:04] Default:0x0 RO */
		u32 dn_age_msgq_bp:1;    /* [05:05] Default:0x0 RO */
		u32 p0_ht0_cpu_acc_bp:1; /* [06:06] Default:0x0 RO */
		u32 p1_ht0_cpu_acc_bp:1; /* [07:07] Default:0x0 RO */
		u32 p2_ht0_cpu_acc_bp:1; /* [08:08] Default:0x0 RO */
		u32 p0_ht1_cpu_acc_bp:1; /* [09:09] Default:0x0 RO */
		u32 p1_ht1_cpu_acc_bp:1; /* [10:10] Default:0x0 RO */
		u32 p2_ht1_cpu_acc_bp:1; /* [11:11] Default:0x0 RO */
		u32 p0_kt_cpu_acc_bp:1;  /* [12:12] Default:0x0 RO */
		u32 p1_kt_cpu_acc_bp:1;  /* [13:13] Default:0x0 RO */
		u32 p2_kt_cpu_acc_bp:1;  /* [14:14] Default:0x0 RO */
		u32 p0_at_cpu_acc_bp:1;  /* [15:15] Default:0x0 RO */
		u32 p1_at_cpu_acc_bp:1;  /* [16:16] Default:0x0 RO */
		u32 p2_at_cpu_acc_bp:1;  /* [17:17] Default:0x0 RO */
		u32 p0_age_cpu_acc_bp:1; /* [18:18] Default:0x0 RO */
		u32 p1_age_cpu_acc_bp:1; /* [19:19] Default:0x0 RO */
		u32 p2_age_cpu_acc_bp:1; /* [20:20] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_BP_STATE_DWLEN];
} __packed;

#define NBL_FEM_BP_HISTORY_ADDR  (0xa04b04)
#define NBL_FEM_BP_HISTORY_DEPTH (1)
#define NBL_FEM_BP_HISTORY_WIDTH (32)
#define NBL_FEM_BP_HISTORY_DWLEN (1)
union fem_bp_history_u {
	struct fem_bp_history {
		u32 fem_pp0_bp:1;        /* [00:00] Default:0x0 RC */
		u32 fem_pp1_bp:1;        /* [01:01] Default:0x0 RC */
		u32 fem_pp2_bp:1;        /* [02:02] Default:0x0 RC */
		u32 up_cmdq_bp:1;        /* [03:03] Default:0x0 RC */
		u32 dn_acl_cmdq_bp:1;    /* [04:04] Default:0x0 RC */
		u32 dn_age_msgq_bp:1;    /* [05:05] Default:0x0 RC */
		u32 p0_ht0_cpu_acc_bp:1; /* [06:06] Default:0x0 RC */
		u32 p1_ht0_cpu_acc_bp:1; /* [07:07] Default:0x0 RC */
		u32 p2_ht0_cpu_acc_bp:1; /* [08:08] Default:0x0 RC */
		u32 p0_ht1_cpu_acc_bp:1; /* [09:09] Default:0x0 RC */
		u32 p1_ht1_cpu_acc_bp:1; /* [10:10] Default:0x0 RC */
		u32 p2_ht1_cpu_acc_bp:1; /* [11:11] Default:0x0 RC */
		u32 p0_kt_cpu_acc_bp:1;  /* [12:12] Default:0x0 RC */
		u32 p1_kt_cpu_acc_bp:1;  /* [13:13] Default:0x0 RC */
		u32 p2_kt_cpu_acc_bp:1;  /* [14:14] Default:0x0 RC */
		u32 p0_at_cpu_acc_bp:1;  /* [15:15] Default:0x0 RC */
		u32 p1_at_cpu_acc_bp:1;  /* [16:16] Default:0x0 RC */
		u32 p2_at_cpu_acc_bp:1;  /* [17:17] Default:0x0 RC */
		u32 p0_age_cpu_acc_bp:1; /* [18:18] Default:0x0 RC */
		u32 p1_age_cpu_acc_bp:1; /* [19:19] Default:0x0 RC */
		u32 p2_age_cpu_acc_bp:1; /* [20:20] Default:0x0 RC */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_BP_HISTORY_DWLEN];
} __packed;

#define NBL_FEM_EM0_LOCK_SEARCH_ADDR  (0xa04c00)
#define NBL_FEM_EM0_LOCK_SEARCH_DEPTH (10)
#define NBL_FEM_EM0_LOCK_SEARCH_WIDTH (32)
#define NBL_FEM_EM0_LOCK_SEARCH_DWLEN (1)
union fem_em0_lock_search_u {
	struct fem_em0_lock_search {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_LOCK_SEARCH_DWLEN];
} __packed;
#define NBL_FEM_EM0_LOCK_SEARCH_REG(r) (NBL_FEM_EM0_LOCK_SEARCH_ADDR + \
		(NBL_FEM_EM0_LOCK_SEARCH_DWLEN * 4) * (r))

#define NBL_FEM_EM0_HT_VALUE_ADDR  (0xa04c28)
#define NBL_FEM_EM0_HT_VALUE_DEPTH (1)
#define NBL_FEM_EM0_HT_VALUE_WIDTH (32)
#define NBL_FEM_EM0_HT_VALUE_DWLEN (1)
union fem_em0_ht_value_u {
	struct fem_em0_ht_value {
		u32 ht0_value:16;        /* [15:00] Default:0x0 RO */
		u32 ht1_value:16;        /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_HT_VALUE_DWLEN];
} __packed;

#define NBL_FEM_EM0_HT_INDEX_ADDR  (0xa04c2c)
#define NBL_FEM_EM0_HT_INDEX_DEPTH (1)
#define NBL_FEM_EM0_HT_INDEX_WIDTH (32)
#define NBL_FEM_EM0_HT_INDEX_DWLEN (1)
union fem_em0_ht_index_u {
	struct fem_em0_ht_index {
		u32 ht0_idx:14;          /* [13:00] Default:0x0 RO */
		u32 rsv1:2;              /* [15:14] Default:0x0 RO */
		u32 ht1_idx:14;          /* [29:16] Default:0x0 RO */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_HT_INDEX_DWLEN];
} __packed;

#define NBL_FEM_EM1_LOCK_SEARCH_ADDR  (0xa04c30)
#define NBL_FEM_EM1_LOCK_SEARCH_DEPTH (10)
#define NBL_FEM_EM1_LOCK_SEARCH_WIDTH (32)
#define NBL_FEM_EM1_LOCK_SEARCH_DWLEN (1)
union fem_em1_lock_search_u {
	struct fem_em1_lock_search {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_LOCK_SEARCH_DWLEN];
} __packed;
#define NBL_FEM_EM1_LOCK_SEARCH_REG(r) (NBL_FEM_EM1_LOCK_SEARCH_ADDR + \
		(NBL_FEM_EM1_LOCK_SEARCH_DWLEN * 4) * (r))

#define NBL_FEM_EM1_HT_VALUE_ADDR  (0xa04c58)
#define NBL_FEM_EM1_HT_VALUE_DEPTH (1)
#define NBL_FEM_EM1_HT_VALUE_WIDTH (32)
#define NBL_FEM_EM1_HT_VALUE_DWLEN (1)
union fem_em1_ht_value_u {
	struct fem_em1_ht_value {
		u32 ht0_value:16;        /* [15:00] Default:0x0 RO */
		u32 ht1_value:16;        /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_HT_VALUE_DWLEN];
} __packed;

#define NBL_FEM_EM1_HT_INDEX_ADDR  (0xa04c5c)
#define NBL_FEM_EM1_HT_INDEX_DEPTH (1)
#define NBL_FEM_EM1_HT_INDEX_WIDTH (32)
#define NBL_FEM_EM1_HT_INDEX_DWLEN (1)
union fem_em1_ht_index_u {
	struct fem_em1_ht_index {
		u32 ht0_idx:14;          /* [13:00] Default:0x0 RO */
		u32 rsv1:2;              /* [15:14] Default:0x0 RO */
		u32 ht1_idx:14;          /* [29:16] Default:0x0 RO */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_HT_INDEX_DWLEN];
} __packed;

#define NBL_FEM_EM2_LOCK_SEARCH_ADDR  (0xa04c60)
#define NBL_FEM_EM2_LOCK_SEARCH_DEPTH (10)
#define NBL_FEM_EM2_LOCK_SEARCH_WIDTH (32)
#define NBL_FEM_EM2_LOCK_SEARCH_DWLEN (1)
union fem_em2_lock_search_u {
	struct fem_em2_lock_search {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_LOCK_SEARCH_DWLEN];
} __packed;
#define NBL_FEM_EM2_LOCK_SEARCH_REG(r) (NBL_FEM_EM2_LOCK_SEARCH_ADDR + \
		(NBL_FEM_EM2_LOCK_SEARCH_DWLEN * 4) * (r))

#define NBL_FEM_EM2_HT_VALUE_ADDR  (0xa04c88)
#define NBL_FEM_EM2_HT_VALUE_DEPTH (1)
#define NBL_FEM_EM2_HT_VALUE_WIDTH (32)
#define NBL_FEM_EM2_HT_VALUE_DWLEN (1)
union fem_em2_ht_value_u {
	struct fem_em2_ht_value {
		u32 ht0_value:16;        /* [15:00] Default:0x0 RO */
		u32 ht1_value:16;        /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_HT_VALUE_DWLEN];
} __packed;

#define NBL_FEM_EM2_HT_INDEX_ADDR  (0xa04c8c)
#define NBL_FEM_EM2_HT_INDEX_DEPTH (1)
#define NBL_FEM_EM2_HT_INDEX_WIDTH (32)
#define NBL_FEM_EM2_HT_INDEX_DWLEN (1)
union fem_em2_ht_index_u {
	struct fem_em2_ht_index {
		u32 ht0_idx:14;          /* [13:00] Default:0x0 RO */
		u32 rsv1:2;              /* [15:14] Default:0x0 RO */
		u32 ht1_idx:14;          /* [29:16] Default:0x0 RO */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_HT_INDEX_DWLEN];
} __packed;

#define NBL_FEM_EM0_LOCK_MISS_ADDR  (0xa04c90)
#define NBL_FEM_EM0_LOCK_MISS_DEPTH (10)
#define NBL_FEM_EM0_LOCK_MISS_WIDTH (32)
#define NBL_FEM_EM0_LOCK_MISS_DWLEN (1)
union fem_em0_lock_miss_u {
	struct fem_em0_lock_miss {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_LOCK_MISS_DWLEN];
} __packed;
#define NBL_FEM_EM0_LOCK_MISS_REG(r) (NBL_FEM_EM0_LOCK_MISS_ADDR + \
		(NBL_FEM_EM0_LOCK_MISS_DWLEN * 4) * (r))

#define NBL_FEM_EM1_LOCK_MISS_ADDR  (0xa04cb8)
#define NBL_FEM_EM1_LOCK_MISS_DEPTH (10)
#define NBL_FEM_EM1_LOCK_MISS_WIDTH (32)
#define NBL_FEM_EM1_LOCK_MISS_DWLEN (1)
union fem_em1_lock_miss_u {
	struct fem_em1_lock_miss {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_LOCK_MISS_DWLEN];
} __packed;
#define NBL_FEM_EM1_LOCK_MISS_REG(r) (NBL_FEM_EM1_LOCK_MISS_ADDR + \
		(NBL_FEM_EM1_LOCK_MISS_DWLEN * 4) * (r))

#define NBL_FEM_EM2_LOCK_MISS_ADDR  (0xa04ce0)
#define NBL_FEM_EM2_LOCK_MISS_DEPTH (10)
#define NBL_FEM_EM2_LOCK_MISS_WIDTH (32)
#define NBL_FEM_EM2_LOCK_MISS_DWLEN (1)
union fem_em2_lock_miss_u {
	struct fem_em2_lock_miss {
		u32 key:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_LOCK_MISS_DWLEN];
} __packed;
#define NBL_FEM_EM2_LOCK_MISS_REG(r) (NBL_FEM_EM2_LOCK_MISS_ADDR + \
		(NBL_FEM_EM2_LOCK_MISS_DWLEN * 4) * (r))

#define NBL_FEM_EM0_PROFILE_TABLE_ADDR  (0xa05000)
#define NBL_FEM_EM0_PROFILE_TABLE_DEPTH (16)
#define NBL_FEM_EM0_PROFILE_TABLE_WIDTH (512)
#define NBL_FEM_EM0_PROFILE_TABLE_DWLEN (16)
union fem_em0_profile_table_u {
	struct fem_em0_profile_table {
		u32 cmd:1;               /* [0] Default:0x0 RW */
		u32 key_size:1;          /* [1] Default:0x0 RW */
		u32 mask_btm:16;         /* [81:2] Default:0x0 RW */
		u32 mask_btm_arr[2];     /* [81:2] Default:0x0 RW */
		u32 hash_sel0:2;         /* [83:82] Default:0x0 RW */
		u32 hash_sel1:2;         /* [85:84] Default:0x0 RW */
		u32 action0:22;          /* [107:86] Default:0x0 RW */
		u32 action1:22;          /* [129:108] Default:0x0 RW */
		u32 action2:22;          /* [151:130] Default:0x0 RW */
		u32 action3:22;          /* [173:152] Default:0x0 RW */
		u32 action4:22;          /* [195:174] Default:0x0 RW */
		u32 action5:22;          /* [217:196] Default:0x0 RW */
		u32 action6:22;          /* [239:218] Default:0x0 RW */
		u32 action7:22;          /* [261:240] Default:0x0 RW */
		u32 act_num:4;           /* [265:262] Default:0x0 RW */
		u32 vld:1;               /* [266] Default:0x0 RW */
		u32 rsv_l:32;            /* [511:267] Default:0x0 RO */
		u32 rsv_h:21;            /* [511:267] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:267] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_PROFILE_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM0_PROFILE_TABLE_REG(r) (NBL_FEM_EM0_PROFILE_TABLE_ADDR + \
		(NBL_FEM_EM0_PROFILE_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM1_PROFILE_TABLE_ADDR  (0xa06000)
#define NBL_FEM_EM1_PROFILE_TABLE_DEPTH (16)
#define NBL_FEM_EM1_PROFILE_TABLE_WIDTH (512)
#define NBL_FEM_EM1_PROFILE_TABLE_DWLEN (16)
union fem_em1_profile_table_u {
	struct fem_em1_profile_table {
		u32 cmd:1;               /* [0] Default:0x0 RW */
		u32 key_size:1;          /* [1] Default:0x0 RW */
		u32 mask_btm:16;         /* [81:2] Default:0x0 RW */
		u32 mask_btm_arr[2];     /* [81:2] Default:0x0 RW */
		u32 hash_sel0:2;         /* [83:82] Default:0x0 RW */
		u32 hash_sel1:2;         /* [85:84] Default:0x0 RW */
		u32 action0:22;          /* [107:86] Default:0x0 RW */
		u32 action1:22;          /* [129:108] Default:0x0 RW */
		u32 action2:22;          /* [151:130] Default:0x0 RW */
		u32 action3:22;          /* [173:152] Default:0x0 RW */
		u32 action4:22;          /* [195:174] Default:0x0 RW */
		u32 action5:22;          /* [217:196] Default:0x0 RW */
		u32 action6:22;          /* [239:218] Default:0x0 RW */
		u32 action7:22;          /* [261:240] Default:0x0 RW */
		u32 act_num:4;           /* [265:262] Default:0x0 RW */
		u32 vld:1;               /* [266] Default:0x0 RW */
		u32 rsv_l:32;            /* [511:267] Default:0x0 RO */
		u32 rsv_h:21;            /* [511:267] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:267] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_PROFILE_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM1_PROFILE_TABLE_REG(r) (NBL_FEM_EM1_PROFILE_TABLE_ADDR + \
		(NBL_FEM_EM1_PROFILE_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM2_PROFILE_TABLE_ADDR  (0xa07000)
#define NBL_FEM_EM2_PROFILE_TABLE_DEPTH (16)
#define NBL_FEM_EM2_PROFILE_TABLE_WIDTH (512)
#define NBL_FEM_EM2_PROFILE_TABLE_DWLEN (16)
union fem_em2_profile_table_u {
	struct fem_em2_profile_table {
		u32 cmd:1;               /* [0] Default:0x0 RW */
		u32 key_size:1;          /* [1] Default:0x0 RW */
		u32 mask_btm:16;         /* [81:2] Default:0x0 RW */
		u32 mask_btm_arr[2];     /* [81:2] Default:0x0 RW */
		u32 hash_sel0:2;         /* [83:82] Default:0x0 RW */
		u32 hash_sel1:2;         /* [85:84] Default:0x0 RW */
		u32 action0:22;          /* [107:86] Default:0x0 RW */
		u32 action1:22;          /* [129:108] Default:0x0 RW */
		u32 action2:22;          /* [151:130] Default:0x0 RW */
		u32 action3:22;          /* [173:152] Default:0x0 RW */
		u32 action4:22;          /* [195:174] Default:0x0 RW */
		u32 action5:22;          /* [217:196] Default:0x0 RW */
		u32 action6:22;          /* [239:218] Default:0x0 RW */
		u32 action7:22;          /* [261:240] Default:0x0 RW */
		u32 act_num:4;           /* [265:262] Default:0x0 RW */
		u32 vld:1;               /* [266] Default:0x0 RW */
		u32 rsv_l:32;            /* [511:267] Default:0x0 RO */
		u32 rsv_h:21;            /* [511:267] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:267] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_PROFILE_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM2_PROFILE_TABLE_REG(r) (NBL_FEM_EM2_PROFILE_TABLE_ADDR + \
		(NBL_FEM_EM2_PROFILE_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM0_AD_TABLE_ADDR  (0xa08000)
#define NBL_FEM_EM0_AD_TABLE_DEPTH (64)
#define NBL_FEM_EM0_AD_TABLE_WIDTH (512)
#define NBL_FEM_EM0_AD_TABLE_DWLEN (16)
union fem_em0_ad_table_u {
	struct fem_em0_ad_table {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 action4:22;          /* [109:88] Default:0x0 RW */
		u32 action5:22;          /* [131:110] Default:0x0 RW */
		u32 action6:22;          /* [153:132] Default:0x0 RW */
		u32 action7:22;          /* [175:154] Default:0x0 RW */
		u32 action8:22;          /* [197:176] Default:0x0 RW */
		u32 action9:22;          /* [219:198] Default:0x0 RW */
		u32 action10:22;         /* [241:220] Default:0x0 RW */
		u32 action11:22;         /* [263:242] Default:0x0 RW */
		u32 action12:22;         /* [285:264] Default:0x0 RW */
		u32 action13:22;         /* [307:286] Default:0x0 RW */
		u32 action14:22;         /* [329:308] Default:0x0 RW */
		u32 action15:22;         /* [351:330] Default:0x0 RW */
		u32 rsv:32;              /* [511:352] Default:0x0 RO */
		u32 rsv_arr[4];          /* [511:352] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_AD_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM0_AD_TABLE_REG(r) (NBL_FEM_EM0_AD_TABLE_ADDR + \
		(NBL_FEM_EM0_AD_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM1_AD_TABLE_ADDR  (0xa09000)
#define NBL_FEM_EM1_AD_TABLE_DEPTH (64)
#define NBL_FEM_EM1_AD_TABLE_WIDTH (512)
#define NBL_FEM_EM1_AD_TABLE_DWLEN (16)
union fem_em1_ad_table_u {
	struct fem_em1_ad_table {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 action4:22;          /* [109:88] Default:0x0 RW */
		u32 action5:22;          /* [131:110] Default:0x0 RW */
		u32 action6:22;          /* [153:132] Default:0x0 RW */
		u32 action7:22;          /* [175:154] Default:0x0 RW */
		u32 action8:22;          /* [197:176] Default:0x0 RW */
		u32 action9:22;          /* [219:198] Default:0x0 RW */
		u32 action10:22;         /* [241:220] Default:0x0 RW */
		u32 action11:22;         /* [263:242] Default:0x0 RW */
		u32 action12:22;         /* [285:264] Default:0x0 RW */
		u32 action13:22;         /* [307:286] Default:0x0 RW */
		u32 action14:22;         /* [329:308] Default:0x0 RW */
		u32 action15:22;         /* [351:330] Default:0x0 RW */
		u32 rsv:32;              /* [511:352] Default:0x0 RO */
		u32 rsv_arr[4];          /* [511:352] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_AD_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM1_AD_TABLE_REG(r) (NBL_FEM_EM1_AD_TABLE_ADDR + \
		(NBL_FEM_EM1_AD_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM2_AD_TABLE_ADDR  (0xa0a000)
#define NBL_FEM_EM2_AD_TABLE_DEPTH (64)
#define NBL_FEM_EM2_AD_TABLE_WIDTH (512)
#define NBL_FEM_EM2_AD_TABLE_DWLEN (16)
union fem_em2_ad_table_u {
	struct fem_em2_ad_table {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 action4:22;          /* [109:88] Default:0x0 RW */
		u32 action5:22;          /* [131:110] Default:0x0 RW */
		u32 action6:22;          /* [153:132] Default:0x0 RW */
		u32 action7:22;          /* [175:154] Default:0x0 RW */
		u32 action8:22;          /* [197:176] Default:0x0 RW */
		u32 action9:22;          /* [219:198] Default:0x0 RW */
		u32 action10:22;         /* [241:220] Default:0x0 RW */
		u32 action11:22;         /* [263:242] Default:0x0 RW */
		u32 action12:22;         /* [285:264] Default:0x0 RW */
		u32 action13:22;         /* [307:286] Default:0x0 RW */
		u32 action14:22;         /* [329:308] Default:0x0 RW */
		u32 action15:22;         /* [351:330] Default:0x0 RW */
		u32 rsv:32;              /* [511:352] Default:0x0 RO */
		u32 rsv_arr[4];          /* [511:352] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_AD_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM2_AD_TABLE_REG(r) (NBL_FEM_EM2_AD_TABLE_ADDR + \
		(NBL_FEM_EM2_AD_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM0_TCAM_TABLE_ADDR  (0xa0b000)
#define NBL_FEM_EM0_TCAM_TABLE_DEPTH (64)
#define NBL_FEM_EM0_TCAM_TABLE_WIDTH (256)
#define NBL_FEM_EM0_TCAM_TABLE_DWLEN (8)
union fem_em0_tcam_table_u {
	struct fem_em0_tcam_table {
		u32 key:32;              /* [159:0] Default:0x0 RW */
		u32 key_arr[4];          /* [159:0] Default:0x0 RW */
		u32 key_vld:1;           /* [160] Default:0x0 RW */
		u32 key_size:1;          /* [161] Default:0x0 RW */
		u32 rsv:30;              /* [255:162] Default:0x0 RO */
		u32 rsv_arr[2];          /* [255:162] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM0_TCAM_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM0_TCAM_TABLE_REG(r) (NBL_FEM_EM0_TCAM_TABLE_ADDR + \
		(NBL_FEM_EM0_TCAM_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM1_TCAM_TABLE_ADDR  (0xa0c000)
#define NBL_FEM_EM1_TCAM_TABLE_DEPTH (64)
#define NBL_FEM_EM1_TCAM_TABLE_WIDTH (256)
#define NBL_FEM_EM1_TCAM_TABLE_DWLEN (8)
union fem_em1_tcam_table_u {
	struct fem_em1_tcam_table {
		u32 key:32;              /* [159:0] Default:0x0 RW */
		u32 key_arr[4];          /* [159:0] Default:0x0 RW */
		u32 key_vld:1;           /* [160] Default:0x0 RW */
		u32 key_size:1;          /* [161] Default:0x0 RW */
		u32 rsv:30;              /* [255:162] Default:0x0 RO */
		u32 rsv_arr[2];          /* [255:162] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM1_TCAM_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM1_TCAM_TABLE_REG(r) (NBL_FEM_EM1_TCAM_TABLE_ADDR + \
		(NBL_FEM_EM1_TCAM_TABLE_DWLEN * 4) * (r))

#define NBL_FEM_EM2_TCAM_TABLE_ADDR  (0xa0d000)
#define NBL_FEM_EM2_TCAM_TABLE_DEPTH (64)
#define NBL_FEM_EM2_TCAM_TABLE_WIDTH (256)
#define NBL_FEM_EM2_TCAM_TABLE_DWLEN (8)
union fem_em2_tcam_table_u {
	struct fem_em2_tcam_table {
		u32 key:32;              /* [159:0] Default:0x0 RW */
		u32 key_arr[4];          /* [159:0] Default:0x0 RW */
		u32 key_vld:1;           /* [160] Default:0x0 RW */
		u32 key_size:1;          /* [161] Default:0x0 RW */
		u32 rsv:30;              /* [255:162] Default:0x0 RO */
		u32 rsv_arr[2];          /* [255:162] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FEM_EM2_TCAM_TABLE_DWLEN];
} __packed;
#define NBL_FEM_EM2_TCAM_TABLE_REG(r) (NBL_FEM_EM2_TCAM_TABLE_ADDR + \
		(NBL_FEM_EM2_TCAM_TABLE_DWLEN * 4) * (r))

#endif
