/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_ACL_H
#define NBL_ACL_H 1

#include <linux/types.h>

#define NBL_ACL_BASE (0x00B64000)

#define NBL_ACL_INT_STATUS_ADDR  (0xb64000)
#define NBL_ACL_INT_STATUS_DEPTH (1)
#define NBL_ACL_INT_STATUS_WIDTH (32)
#define NBL_ACL_INT_STATUS_DWLEN (1)
union acl_int_status_u {
	struct acl_int_status {
		u32 fifo_uflw_err:1;     /* [00:00] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [02:02] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [03:03] Default:0x0 RWC */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 set_dport_encode_cfg_err:1; /* [05:05] Default:0x0 RWC */
		u32 tcam_cor_err:1;      /* [06:06] Default:0x0 RWC */
		u32 tcam_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 flow_id_err:1;       /* [08:08] Default:0x0 RWC */
		u32 stat_id_conflict_int:1; /* [09:09] Default:0x0 RWC */
		u32 flow_id_conflict_int:1; /* [10:10] Default:0x0 RWC */
		u32 fsm_err:1;           /* [11:11] Default:0x0 RWC */
		u32 nxt_stage_lp_cfg_err:1; /* [12:12] Default:0x0 RWC */
		u32 input_err:1;         /* [13:13] Default:0x0 RWC */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INT_STATUS_DWLEN];
} __packed;

#define NBL_ACL_INT_MASK_ADDR  (0xb64004)
#define NBL_ACL_INT_MASK_DEPTH (1)
#define NBL_ACL_INT_MASK_WIDTH (32)
#define NBL_ACL_INT_MASK_DWLEN (1)
union acl_int_mask_u {
	struct acl_int_mask {
		u32 fifo_uflw_err:1;     /* [00:00] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [02:02] Default:0x0 RW */
		u32 data_cor_err:1;      /* [03:03] Default:0x0 RW */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 set_dport_encode_cfg_err:1; /* [05:05] Default:0x0 RW */
		u32 tcam_cor_err:1;      /* [06:06] Default:0x0 RW */
		u32 tcam_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 flow_id_err:1;       /* [08:08] Default:0x0 RW */
		u32 stat_id_conflict_int:1; /* [09:09] Default:0x0 RW */
		u32 flow_id_conflict_int:1; /* [10:10] Default:0x0 RW */
		u32 fsm_err:1;           /* [11:11] Default:0x0 RW */
		u32 nxt_stage_lp_cfg_err:1; /* [12:12] Default:0x0 RW */
		u32 input_err:1;         /* [13:13] Default:0x0 RW */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INT_MASK_DWLEN];
} __packed;

#define NBL_ACL_INT_SET_ADDR  (0xb64008)
#define NBL_ACL_INT_SET_DEPTH (1)
#define NBL_ACL_INT_SET_WIDTH (32)
#define NBL_ACL_INT_SET_DWLEN (1)
union acl_int_set_u {
	struct acl_int_set {
		u32 fifo_uflw_err:1;     /* [00:00] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [02:02] Default:0x0 WO */
		u32 data_cor_err:1;      /* [03:03] Default:0x0 WO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 set_dport_encode_cfg_err:1; /* [05:05] Default:0x0 WO */
		u32 tcam_cor_err:1;      /* [06:06] Default:0x0 WO */
		u32 tcam_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 flow_id_err:1;       /* [08:08] Default:0x0 WO */
		u32 stat_id_conflict_int:1; /* [09:09] Default:0x0 WO */
		u32 flow_id_conflict_int:1; /* [10:10] Default:0x0 WO */
		u32 fsm_err:1;           /* [11:11] Default:0x0 WO */
		u32 nxt_stage_lp_cfg_err:1; /* [12:12] Default:0x0 WO */
		u32 input_err:1;         /* [13:13] Default:0x0 WO */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INT_SET_DWLEN];
} __packed;

#define NBL_ACL_INIT_DONE_ADDR  (0xb6400c)
#define NBL_ACL_INIT_DONE_DEPTH (1)
#define NBL_ACL_INIT_DONE_WIDTH (32)
#define NBL_ACL_INIT_DONE_DWLEN (1)
union acl_init_done_u {
	struct acl_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INIT_DONE_DWLEN];
} __packed;

#define NBL_ACL_CIF_ERR_INFO_ADDR  (0xb64084)
#define NBL_ACL_CIF_ERR_INFO_DEPTH (1)
#define NBL_ACL_CIF_ERR_INFO_WIDTH (32)
#define NBL_ACL_CIF_ERR_INFO_DWLEN (1)
union acl_cif_err_info_u {
	struct acl_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_ACL_INIT_START_ADDR  (0xb6409c)
#define NBL_ACL_INIT_START_DEPTH (1)
#define NBL_ACL_INIT_START_WIDTH (32)
#define NBL_ACL_INIT_START_DWLEN (1)
union acl_init_start_u {
	struct acl_init_start {
		u32 start:1;             /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INIT_START_DWLEN];
} __packed;

#define NBL_ACL_BYPASS_REG_ADDR  (0xb64100)
#define NBL_ACL_BYPASS_REG_DEPTH (1)
#define NBL_ACL_BYPASS_REG_WIDTH (32)
#define NBL_ACL_BYPASS_REG_DWLEN (1)
union acl_bypass_reg_u {
	struct acl_bypass_reg {
		u32 acl_bypass:1;        /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_BYPASS_REG_DWLEN];
} __packed;

#define NBL_ACL_LOOP_BACK_EN_ADDR  (0xb64108)
#define NBL_ACL_LOOP_BACK_EN_DEPTH (1)
#define NBL_ACL_LOOP_BACK_EN_WIDTH (32)
#define NBL_ACL_LOOP_BACK_EN_DWLEN (1)
union acl_loop_back_en_u {
	struct acl_loop_back_en {
		u32 loop_back_en:1;      /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_LOOP_BACK_EN_DWLEN];
} __packed;

#define NBL_ACL_LOOP_FLAG_EN_ADDR  (0xb6410c)
#define NBL_ACL_LOOP_FLAG_EN_DEPTH (1)
#define NBL_ACL_LOOP_FLAG_EN_WIDTH (32)
#define NBL_ACL_LOOP_FLAG_EN_DWLEN (1)
union acl_loop_flag_en_u {
	struct acl_loop_flag_en {
		u32 flag_en:1;           /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_LOOP_FLAG_EN_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION0_ADDR  (0xb64160)
#define NBL_ACL_DEFAULT_ACTION0_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION0_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION0_DWLEN (1)
union acl_default_action0_u {
	struct acl_default_action0 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION0_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION1_ADDR  (0xb64164)
#define NBL_ACL_DEFAULT_ACTION1_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION1_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION1_DWLEN (1)
union acl_default_action1_u {
	struct acl_default_action1 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION1_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION2_ADDR  (0xb64168)
#define NBL_ACL_DEFAULT_ACTION2_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION2_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION2_DWLEN (1)
union acl_default_action2_u {
	struct acl_default_action2 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION2_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION3_ADDR  (0xb6416c)
#define NBL_ACL_DEFAULT_ACTION3_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION3_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION3_DWLEN (1)
union acl_default_action3_u {
	struct acl_default_action3 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION3_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION4_ADDR  (0xb64170)
#define NBL_ACL_DEFAULT_ACTION4_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION4_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION4_DWLEN (1)
union acl_default_action4_u {
	struct acl_default_action4 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION4_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION5_ADDR  (0xb64174)
#define NBL_ACL_DEFAULT_ACTION5_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION5_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION5_DWLEN (1)
union acl_default_action5_u {
	struct acl_default_action5 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION5_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION6_ADDR  (0xb64178)
#define NBL_ACL_DEFAULT_ACTION6_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION6_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION6_DWLEN (1)
union acl_default_action6_u {
	struct acl_default_action6 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION6_DWLEN];
} __packed;

#define NBL_ACL_DEFAULT_ACTION7_ADDR  (0xb6417c)
#define NBL_ACL_DEFAULT_ACTION7_DEPTH (1)
#define NBL_ACL_DEFAULT_ACTION7_WIDTH (32)
#define NBL_ACL_DEFAULT_ACTION7_DWLEN (1)
union acl_default_action7_u {
	struct acl_default_action7 {
		u32 data:22;             /* [21:0] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION7_DWLEN];
} __packed;

#define NBL_ACL_SET_FLAG_ADDR  (0xb64200)
#define NBL_ACL_SET_FLAG_DEPTH (1)
#define NBL_ACL_SET_FLAG_WIDTH (32)
#define NBL_ACL_SET_FLAG_DWLEN (1)
union acl_set_flag_u {
	struct acl_set_flag {
		u32 set_flag0:32;        /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_SET_FLAG_DWLEN];
} __packed;

#define NBL_ACL_CLEAR_FLAG_ADDR  (0xb64204)
#define NBL_ACL_CLEAR_FLAG_DEPTH (1)
#define NBL_ACL_CLEAR_FLAG_WIDTH (32)
#define NBL_ACL_CLEAR_FLAG_DWLEN (1)
union acl_clear_flag_u {
	struct acl_clear_flag {
		u32 clear_flag0:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_CLEAR_FLAG_DWLEN];
} __packed;

#define NBL_ACL_SET_FLAG0_ADDR  (0xb64208)
#define NBL_ACL_SET_FLAG0_DEPTH (1)
#define NBL_ACL_SET_FLAG0_WIDTH (32)
#define NBL_ACL_SET_FLAG0_DWLEN (1)
union acl_set_flag0_u {
	struct acl_set_flag0 {
		u32 set_flag0:32;        /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_SET_FLAG0_DWLEN];
} __packed;

#define NBL_ACL_CLEAR_FLAG0_ADDR  (0xb6420c)
#define NBL_ACL_CLEAR_FLAG0_DEPTH (1)
#define NBL_ACL_CLEAR_FLAG0_WIDTH (32)
#define NBL_ACL_CLEAR_FLAG0_DWLEN (1)
union acl_clear_flag0_u {
	struct acl_clear_flag0 {
		u32 clear_flag0:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_CLEAR_FLAG0_DWLEN];
} __packed;

#define NBL_ACL_DPORT_CFG_ADDR  (0xb64220)
#define NBL_ACL_DPORT_CFG_DEPTH (1)
#define NBL_ACL_DPORT_CFG_WIDTH (32)
#define NBL_ACL_DPORT_CFG_DWLEN (1)
union acl_dport_cfg_u {
	struct acl_dport_cfg {
		u32 act_id:6;            /* [05:00] Default:0x9 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DPORT_CFG_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY0_ADDR  (0xb64230)
#define NBL_ACL_ACTION_PRIORITY0_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY0_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY0_DWLEN (1)
union acl_action_priority0_u {
	struct acl_action_priority0 {
		u32 action_id3_pri:2;    /* [01:00] Default:0x0 RW */
		u32 action_id4_pri:2;    /* [03:02] Default:0x0 RW */
		u32 action_id5_pri:2;    /* [05:04] Default:0x0 RW */
		u32 action_id6_pri:2;    /* [07:06] Default:0x0 RW */
		u32 action_id7_pri:2;    /* [09:08] Default:0x0 RW */
		u32 action_id8_pri:2;    /* [11:10] Default:0x0 RW */
		u32 action_id9_pri:2;    /* [13:12] Default:0x0 RW */
		u32 action_id10_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id11_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id12_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id13_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id14_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id15_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id16_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id17_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id18_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY0_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY1_ADDR  (0xb64234)
#define NBL_ACL_ACTION_PRIORITY1_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY1_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY1_DWLEN (1)
union acl_action_priority1_u {
	struct acl_action_priority1 {
		u32 action_id19_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id20_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id21_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id22_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id23_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id24_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id25_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id26_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id27_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id28_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id29_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id30_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id31_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id32_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id33_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id34_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY1_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY2_ADDR  (0xb64238)
#define NBL_ACL_ACTION_PRIORITY2_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY2_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY2_DWLEN (1)
union acl_action_priority2_u {
	struct acl_action_priority2 {
		u32 action_id35_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id36_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id37_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id38_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id39_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id40_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id41_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id42_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id43_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id44_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id45_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id46_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id47_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id48_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id49_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id50_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY2_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY3_ADDR  (0xb6423c)
#define NBL_ACL_ACTION_PRIORITY3_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY3_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY3_DWLEN (1)
union acl_action_priority3_u {
	struct acl_action_priority3 {
		u32 action_id51_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id52_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id53_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id54_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id55_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id56_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id57_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id58_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id59_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id60_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id61_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id62_pri:2;   /* [23:22] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY3_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY4_ADDR  (0xb64240)
#define NBL_ACL_ACTION_PRIORITY4_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY4_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY4_DWLEN (1)
union acl_action_priority4_u {
	struct acl_action_priority4 {
		u32 action_id3_pri:2;    /* [01:00] Default:0x0 RW */
		u32 action_id4_pri:2;    /* [03:02] Default:0x0 RW */
		u32 action_id5_pri:2;    /* [05:04] Default:0x0 RW */
		u32 action_id6_pri:2;    /* [07:06] Default:0x0 RW */
		u32 action_id7_pri:2;    /* [09:08] Default:0x0 RW */
		u32 action_id8_pri:2;    /* [11:10] Default:0x0 RW */
		u32 action_id9_pri:2;    /* [13:12] Default:0x0 RW */
		u32 action_id10_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id11_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id12_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id13_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id14_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id15_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id16_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id17_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id18_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY4_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY5_ADDR  (0xb64244)
#define NBL_ACL_ACTION_PRIORITY5_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY5_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY5_DWLEN (1)
union acl_action_priority5_u {
	struct acl_action_priority5 {
		u32 action_id19_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id20_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id21_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id22_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id23_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id24_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id25_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id26_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id27_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id28_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id29_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id30_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id31_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id32_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id33_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id34_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY5_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY6_ADDR  (0xb64248)
#define NBL_ACL_ACTION_PRIORITY6_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY6_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY6_DWLEN (1)
union acl_action_priority6_u {
	struct acl_action_priority6 {
		u32 action_id35_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id36_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id37_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id38_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id39_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id40_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id41_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id42_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id43_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id44_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id45_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id46_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id47_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id48_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id49_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id50_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY6_DWLEN];
} __packed;

#define NBL_ACL_ACTION_PRIORITY7_ADDR  (0xb6424c)
#define NBL_ACL_ACTION_PRIORITY7_DEPTH (1)
#define NBL_ACL_ACTION_PRIORITY7_WIDTH (32)
#define NBL_ACL_ACTION_PRIORITY7_DWLEN (1)
union acl_action_priority7_u {
	struct acl_action_priority7 {
		u32 action_id51_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id52_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id53_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id54_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id55_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id56_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id57_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id58_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id59_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id60_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id61_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id62_pri:2;   /* [23:22] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_PRIORITY7_DWLEN];
} __packed;

#define NBL_ACL_TCAM_MASK_ADDR_ADDR  (0xb64280)
#define NBL_ACL_TCAM_MASK_ADDR_DEPTH (1)
#define NBL_ACL_TCAM_MASK_ADDR_WIDTH (32)
#define NBL_ACL_TCAM_MASK_ADDR_DWLEN (1)
union acl_tcam_mask_addr_u {
	struct acl_tcam_mask_addr {
		u32 addr0:9;             /* [08:00] Default:0x0 RW */
		u32 addr0_en:1;          /* [09:09] Default:0x0 RW */
		u32 addr1:9;             /* [18:10] Default:0x0 RW */
		u32 addr1_en:1;          /* [19:19] Default:0x0 RW */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_MASK_ADDR_DWLEN];
} __packed;

#define NBL_ACL_TCAM_MASK_BTM_ADDR  (0xb64284)
#define NBL_ACL_TCAM_MASK_BTM_DEPTH (1)
#define NBL_ACL_TCAM_MASK_BTM_WIDTH (32)
#define NBL_ACL_TCAM_MASK_BTM_DWLEN (1)
union acl_tcam_mask_btm_u {
	struct acl_tcam_mask_btm {
		u32 btm:16;              /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_MASK_BTM_DWLEN];
} __packed;

#define NBL_ACL_CAP_ADDR  (0xb64288)
#define NBL_ACL_CAP_DEPTH (1)
#define NBL_ACL_CAP_WIDTH (32)
#define NBL_ACL_CAP_DWLEN (1)
union acl_cap_u {
	struct acl_cap {
		u32 onloop_cap_mode:1;   /* [00:00] Default:0x0 RW */
		u32 noloop_cap_start:1;  /* [01:01] Default:0x0 WO */
		u32 loop_cap_mode:1;     /* [02:02] Default:0x0 RW */
		u32 loop_cap_start:1;    /* [03:03] Default:0x0 WO */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_CAP_DWLEN];
} __packed;

#define NBL_ACL_FLOW_ID_STAT_ACT_ADDR  (0xb64300)
#define NBL_ACL_FLOW_ID_STAT_ACT_DEPTH (1)
#define NBL_ACL_FLOW_ID_STAT_ACT_WIDTH (32)
#define NBL_ACL_FLOW_ID_STAT_ACT_DWLEN (1)
union acl_flow_id_stat_act_u {
	struct acl_flow_id_stat_act {
		u32 flow_id_en:1;        /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_FLOW_ID_STAT_ACT_DWLEN];
} __packed;

#define NBL_ACL_FLOW_ID_STAT_GLB_CLR_ADDR  (0xb64304)
#define NBL_ACL_FLOW_ID_STAT_GLB_CLR_DEPTH (1)
#define NBL_ACL_FLOW_ID_STAT_GLB_CLR_WIDTH (32)
#define NBL_ACL_FLOW_ID_STAT_GLB_CLR_DWLEN (1)
union acl_flow_id_stat_glb_clr_u {
	struct acl_flow_id_stat_glb_clr {
		u32 glb_clr:1;           /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_FLOW_ID_STAT_GLB_CLR_DWLEN];
} __packed;

#define NBL_ACL_FLOW_ID_STAT_RD_CLR_ADDR  (0xb64308)
#define NBL_ACL_FLOW_ID_STAT_RD_CLR_DEPTH (1)
#define NBL_ACL_FLOW_ID_STAT_RD_CLR_WIDTH (32)
#define NBL_ACL_FLOW_ID_STAT_RD_CLR_DWLEN (1)
union acl_flow_id_stat_rd_clr_u {
	struct acl_flow_id_stat_rd_clr {
		u32 cpu_rd_clr:1;        /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_FLOW_ID_STAT_RD_CLR_DWLEN];
} __packed;

#define NBL_ACL_FLOW_ID_STAT_DONE_ADDR  (0xb64310)
#define NBL_ACL_FLOW_ID_STAT_DONE_DEPTH (1)
#define NBL_ACL_FLOW_ID_STAT_DONE_WIDTH (32)
#define NBL_ACL_FLOW_ID_STAT_DONE_DWLEN (1)
union acl_flow_id_stat_done_u {
	struct acl_flow_id_stat_done {
		u32 glb_clr_done:1;      /* [00:00] Default:0x0 RO */
		u32 stat_init_done:1;    /* [01:01] Default:0x0 RO */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_FLOW_ID_STAT_DONE_DWLEN];
} __packed;

#define NBL_ACL_SCAN_TH_ADDR  (0xb64318)
#define NBL_ACL_SCAN_TH_DEPTH (1)
#define NBL_ACL_SCAN_TH_WIDTH (32)
#define NBL_ACL_SCAN_TH_DWLEN (1)
union acl_scan_th_u {
	struct acl_scan_th {
		u32 scan_th:10;          /* [09:00] Default:0xff RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_SCAN_TH_DWLEN];
} __packed;

#define NBL_ACL_SCAN_EN_ADDR  (0xb6431c)
#define NBL_ACL_SCAN_EN_DEPTH (1)
#define NBL_ACL_SCAN_EN_WIDTH (32)
#define NBL_ACL_SCAN_EN_DWLEN (1)
union acl_scan_en_u {
	struct acl_scan_en {
		u32 scan_en:1;           /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_SCAN_EN_DWLEN];
} __packed;

#define NBL_ACL_STAT_ID_STAT_GLB_CLR_ADDR  (0xb64320)
#define NBL_ACL_STAT_ID_STAT_GLB_CLR_DEPTH (1)
#define NBL_ACL_STAT_ID_STAT_GLB_CLR_WIDTH (32)
#define NBL_ACL_STAT_ID_STAT_GLB_CLR_DWLEN (1)
union acl_stat_id_stat_glb_clr_u {
	struct acl_stat_id_stat_glb_clr {
		u32 glb_clr:1;           /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_STAT_ID_STAT_GLB_CLR_DWLEN];
} __packed;

#define NBL_ACL_STAT_ID_STAT_RD_CLR_ADDR  (0xb64324)
#define NBL_ACL_STAT_ID_STAT_RD_CLR_DEPTH (1)
#define NBL_ACL_STAT_ID_STAT_RD_CLR_WIDTH (32)
#define NBL_ACL_STAT_ID_STAT_RD_CLR_DWLEN (1)
union acl_stat_id_stat_rd_clr_u {
	struct acl_stat_id_stat_rd_clr {
		u32 cpu_rd_clr:1;        /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_STAT_ID_STAT_RD_CLR_DWLEN];
} __packed;

#define NBL_ACL_STAT_ID_STAT_DONE_ADDR  (0xb64328)
#define NBL_ACL_STAT_ID_STAT_DONE_DEPTH (1)
#define NBL_ACL_STAT_ID_STAT_DONE_WIDTH (32)
#define NBL_ACL_STAT_ID_STAT_DONE_DWLEN (1)
union acl_stat_id_stat_done_u {
	struct acl_stat_id_stat_done {
		u32 glb_clr_done:1;      /* [00:00] Default:0x0 RO */
		u32 stat_init_done:1;    /* [01:01] Default:0x0 RO */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_STAT_ID_STAT_DONE_DWLEN];
} __packed;

#define NBL_ACL_STAT_ID_ACT_ADDR  (0xb6432c)
#define NBL_ACL_STAT_ID_ACT_DEPTH (1)
#define NBL_ACL_STAT_ID_ACT_WIDTH (32)
#define NBL_ACL_STAT_ID_ACT_DWLEN (1)
union acl_stat_id_act_u {
	struct acl_stat_id_act {
		u32 act_id:6;            /* [05:00] Default:0x10 RW */
		u32 act_en:1;            /* [06:06] Default:0x0 RW */
		u32 rsv:25;              /* [31:07] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_STAT_ID_ACT_DWLEN];
} __packed;

#define NBL_ACL_CAR_CTRL_ADDR  (0xb64410)
#define NBL_ACL_CAR_CTRL_DEPTH (1)
#define NBL_ACL_CAR_CTRL_WIDTH (32)
#define NBL_ACL_CAR_CTRL_DWLEN (1)
union acl_car_ctrl_u {
	struct acl_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_CAR_CTRL_DWLEN];
} __packed;

#define NBL_ACL_IN_ADDR  (0xb64600)
#define NBL_ACL_IN_DEPTH (1)
#define NBL_ACL_IN_WIDTH (32)
#define NBL_ACL_IN_DWLEN (1)
union acl_in_u {
	struct acl_in {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_IN_DWLEN];
} __packed;

#define NBL_ACL_OUT_ADDR  (0xb64608)
#define NBL_ACL_OUT_DEPTH (1)
#define NBL_ACL_OUT_WIDTH (32)
#define NBL_ACL_OUT_DWLEN (1)
union acl_out_u {
	struct acl_out {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_OUT_DWLEN];
} __packed;

#define NBL_ACL_TCAM_SE_ADDR  (0xb6461c)
#define NBL_ACL_TCAM_SE_DEPTH (1)
#define NBL_ACL_TCAM_SE_WIDTH (32)
#define NBL_ACL_TCAM_SE_DWLEN (1)
union acl_tcam_se_u {
	struct acl_tcam_se {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_TCAM_SE_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR  (0xb64624)
#define NBL_ACL_TCAM_HIT_DEPTH (1)
#define NBL_ACL_TCAM_HIT_WIDTH (32)
#define NBL_ACL_TCAM_HIT_DWLEN (1)
union acl_tcam_hit_u {
	struct acl_tcam_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR0_ADDR  (0xb6462c)
#define NBL_ACL_TCAM_HIT_ADDR0_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR0_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR0_DWLEN (1)
union acl_tcam_hit_addr0_u {
	struct acl_tcam_hit_addr0 {
		u32 addr0:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id0:4;          /* [12:09] Default:0x0 RO */
		u32 addr1:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id1:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR0_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR1_ADDR  (0xb64630)
#define NBL_ACL_TCAM_HIT_ADDR1_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR1_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR1_DWLEN (1)
union acl_tcam_hit_addr1_u {
	struct acl_tcam_hit_addr1 {
		u32 addr2:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id2:4;          /* [12:09] Default:0x0 RO */
		u32 addr3:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id3:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR1_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR2_ADDR  (0xb64634)
#define NBL_ACL_TCAM_HIT_ADDR2_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR2_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR2_DWLEN (1)
union acl_tcam_hit_addr2_u {
	struct acl_tcam_hit_addr2 {
		u32 addr4:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id4:4;          /* [12:09] Default:0x0 RO */
		u32 addr5:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id5:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR2_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR3_ADDR  (0xb64638)
#define NBL_ACL_TCAM_HIT_ADDR3_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR3_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR3_DWLEN (1)
union acl_tcam_hit_addr3_u {
	struct acl_tcam_hit_addr3 {
		u32 addr6:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id6:4;          /* [12:09] Default:0x0 RO */
		u32 addr7:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id7:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR3_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR4_ADDR  (0xb6463c)
#define NBL_ACL_TCAM_HIT_ADDR4_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR4_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR4_DWLEN (1)
union acl_tcam_hit_addr4_u {
	struct acl_tcam_hit_addr4 {
		u32 addr8:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id8:4;          /* [12:09] Default:0x0 RO */
		u32 addr9:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id9:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR4_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR5_ADDR  (0xb64640)
#define NBL_ACL_TCAM_HIT_ADDR5_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR5_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR5_DWLEN (1)
union acl_tcam_hit_addr5_u {
	struct acl_tcam_hit_addr5 {
		u32 addr10:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id10:4;         /* [12:09] Default:0x0 RO */
		u32 addr11:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id11:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR5_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR6_ADDR  (0xb64644)
#define NBL_ACL_TCAM_HIT_ADDR6_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR6_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR6_DWLEN (1)
union acl_tcam_hit_addr6_u {
	struct acl_tcam_hit_addr6 {
		u32 addr12:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id12:4;         /* [12:09] Default:0x0 RO */
		u32 addr13:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id13:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR6_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_ADDR7_ADDR  (0xb64648)
#define NBL_ACL_TCAM_HIT_ADDR7_DEPTH (1)
#define NBL_ACL_TCAM_HIT_ADDR7_WIDTH (32)
#define NBL_ACL_TCAM_HIT_ADDR7_DWLEN (1)
union acl_tcam_hit_addr7_u {
	struct acl_tcam_hit_addr7 {
		u32 addr14:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id14:4;         /* [12:09] Default:0x0 RO */
		u32 addr15:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id15:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_ADDR7_DWLEN];
} __packed;

#define NBL_ACL_CMP_SET_VEC_ADDR  (0xb64650)
#define NBL_ACL_CMP_SET_VEC_DEPTH (1)
#define NBL_ACL_CMP_SET_VEC_WIDTH (32)
#define NBL_ACL_CMP_SET_VEC_DWLEN (1)
union acl_cmp_set_vec_u {
	struct acl_cmp_set_vec {
		u32 vec:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_CMP_SET_VEC_DWLEN];
} __packed;

#define NBL_ACL_TCAM_NOLOOP_HIT_VLD_ADDR  (0xb64670)
#define NBL_ACL_TCAM_NOLOOP_HIT_VLD_DEPTH (1)
#define NBL_ACL_TCAM_NOLOOP_HIT_VLD_WIDTH (32)
#define NBL_ACL_TCAM_NOLOOP_HIT_VLD_DWLEN (1)
union acl_tcam_noloop_hit_vld_u {
	struct acl_tcam_noloop_hit_vld {
		u32 hit_vld:16;          /* [15:00] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_NOLOOP_HIT_VLD_DWLEN];
} __packed;

#define NBL_ACL_TCAM_LOOP_HIT_VLD_ADDR  (0xb64674)
#define NBL_ACL_TCAM_LOOP_HIT_VLD_DEPTH (1)
#define NBL_ACL_TCAM_LOOP_HIT_VLD_WIDTH (32)
#define NBL_ACL_TCAM_LOOP_HIT_VLD_DWLEN (1)
union acl_tcam_loop_hit_vld_u {
	struct acl_tcam_loop_hit_vld {
		u32 hit_vld:16;          /* [15:00] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_LOOP_HIT_VLD_DWLEN];
} __packed;

#define NBL_ACL_ISE_TCAM_HIT_ADDR  (0xb64680)
#define NBL_ACL_ISE_TCAM_HIT_DEPTH (1)
#define NBL_ACL_ISE_TCAM_HIT_WIDTH (32)
#define NBL_ACL_ISE_TCAM_HIT_DWLEN (1)
union acl_ise_tcam_hit_u {
	struct acl_ise_tcam_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_ISE_TCAM_HIT_DWLEN];
} __packed;

#define NBL_ACL_ISE_TCAM_NOHIT_ADDR  (0xb64684)
#define NBL_ACL_ISE_TCAM_NOHIT_DEPTH (1)
#define NBL_ACL_ISE_TCAM_NOHIT_WIDTH (32)
#define NBL_ACL_ISE_TCAM_NOHIT_DWLEN (1)
union acl_ise_tcam_nohit_u {
	struct acl_ise_tcam_nohit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_ISE_TCAM_NOHIT_DWLEN];
} __packed;

#define NBL_ACL_LOOP_TCAM_HIT_ADDR  (0xb64688)
#define NBL_ACL_LOOP_TCAM_HIT_DEPTH (1)
#define NBL_ACL_LOOP_TCAM_HIT_WIDTH (32)
#define NBL_ACL_LOOP_TCAM_HIT_DWLEN (1)
union acl_loop_tcam_hit_u {
	struct acl_loop_tcam_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_LOOP_TCAM_HIT_DWLEN];
} __packed;

#define NBL_ACL_NOLOOP_TCAM_HIT_ADDR  (0xb6468c)
#define NBL_ACL_NOLOOP_TCAM_HIT_DEPTH (1)
#define NBL_ACL_NOLOOP_TCAM_HIT_WIDTH (32)
#define NBL_ACL_NOLOOP_TCAM_HIT_DWLEN (1)
union acl_noloop_tcam_hit_u {
	struct acl_noloop_tcam_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_NOLOOP_TCAM_HIT_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR0_ADDR  (0xb64690)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR0_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR0_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR0_DWLEN (1)
union acl_tcam_hit_loop_addr0_u {
	struct acl_tcam_hit_loop_addr0 {
		u32 addr0:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id0:4;          /* [12:09] Default:0x0 RO */
		u32 addr1:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id1:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR0_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR1_ADDR  (0xb64694)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR1_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR1_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR1_DWLEN (1)
union acl_tcam_hit_loop_addr1_u {
	struct acl_tcam_hit_loop_addr1 {
		u32 addr2:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id2:4;          /* [12:09] Default:0x0 RO */
		u32 addr3:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id3:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR1_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR2_ADDR  (0xb64698)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR2_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR2_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR2_DWLEN (1)
union acl_tcam_hit_loop_addr2_u {
	struct acl_tcam_hit_loop_addr2 {
		u32 addr4:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id4:4;          /* [12:09] Default:0x0 RO */
		u32 addr5:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id5:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR2_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR3_ADDR  (0xb6469c)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR3_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR3_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR3_DWLEN (1)
union acl_tcam_hit_loop_addr3_u {
	struct acl_tcam_hit_loop_addr3 {
		u32 addr6:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id6:4;          /* [12:09] Default:0x0 RO */
		u32 addr7:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id7:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR3_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR4_ADDR  (0xb646a0)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR4_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR4_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR4_DWLEN (1)
union acl_tcam_hit_loop_addr4_u {
	struct acl_tcam_hit_loop_addr4 {
		u32 addr8:9;             /* [08:00] Default:0x0 RO */
		u32 tcam_id8:4;          /* [12:09] Default:0x0 RO */
		u32 addr9:9;             /* [21:13] Default:0x0 RO */
		u32 tcam_id9:4;          /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR4_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR5_ADDR  (0xb646a4)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR5_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR5_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR5_DWLEN (1)
union acl_tcam_hit_loop_addr5_u {
	struct acl_tcam_hit_loop_addr5 {
		u32 addr10:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id10:4;         /* [12:09] Default:0x0 RO */
		u32 addr11:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id11:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR5_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR6_ADDR  (0xb646a8)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR6_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR6_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR6_DWLEN (1)
union acl_tcam_hit_loop_addr6_u {
	struct acl_tcam_hit_loop_addr6 {
		u32 addr12:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id12:4;         /* [12:09] Default:0x0 RO */
		u32 addr13:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id13:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR6_DWLEN];
} __packed;

#define NBL_ACL_TCAM_HIT_LOOP_ADDR7_ADDR  (0xb646ac)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR7_DEPTH (1)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR7_WIDTH (32)
#define NBL_ACL_TCAM_HIT_LOOP_ADDR7_DWLEN (1)
union acl_tcam_hit_loop_addr7_u {
	struct acl_tcam_hit_loop_addr7 {
		u32 addr14:9;            /* [08:00] Default:0x0 RO */
		u32 tcam_id14:4;         /* [12:09] Default:0x0 RO */
		u32 addr15:9;            /* [21:13] Default:0x0 RO */
		u32 tcam_id15:4;         /* [25:22] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_HIT_LOOP_ADDR7_DWLEN];
} __packed;

#define NBL_ACL_OUT_DROP_ADDR  (0xb646c8)
#define NBL_ACL_OUT_DROP_DEPTH (1)
#define NBL_ACL_OUT_DROP_WIDTH (32)
#define NBL_ACL_OUT_DROP_DWLEN (1)
union acl_out_drop_u {
	struct acl_out_drop {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_OUT_DROP_DWLEN];
} __packed;

#define NBL_ACL_NXT_STAGE_ADDR  (0xb646d0)
#define NBL_ACL_NXT_STAGE_DEPTH (1)
#define NBL_ACL_NXT_STAGE_WIDTH (32)
#define NBL_ACL_NXT_STAGE_DWLEN (1)
union acl_nxt_stage_u {
	struct acl_nxt_stage {
		u32 in_nxt_stage:4;      /* [03:00] Default:0x0 RO */
		u32 out_nxt_satge:4;     /* [07:04] Default:0x0 RO */
		u32 rsv:24;              /* [31:08] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_NXT_STAGE_DWLEN];
} __packed;

#define NBL_ACL_BP_STATE_ADDR  (0xb64700)
#define NBL_ACL_BP_STATE_DEPTH (1)
#define NBL_ACL_BP_STATE_WIDTH (32)
#define NBL_ACL_BP_STATE_DWLEN (1)
union acl_bp_state_u {
	struct acl_bp_state {
		u32 in_bp:1;             /* [00:00] Default:0x0 RO */
		u32 out_bp:1;            /* [01:01] Default:0x0 RO */
		u32 inter_bp:1;          /* [02:02] Default:0x0 RO */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_BP_STATE_DWLEN];
} __packed;

#define NBL_ACL_CMDQ_REQ_HIT_ADDR  (0xb647a0)
#define NBL_ACL_CMDQ_REQ_HIT_DEPTH (1)
#define NBL_ACL_CMDQ_REQ_HIT_WIDTH (32)
#define NBL_ACL_CMDQ_REQ_HIT_DWLEN (1)
union acl_cmdq_req_hit_u {
	struct acl_cmdq_req_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_CMDQ_REQ_HIT_DWLEN];
} __packed;

#define NBL_ACL_CMDQ_REQ_NO_HIT_ADDR  (0xb647a8)
#define NBL_ACL_CMDQ_REQ_NO_HIT_DEPTH (1)
#define NBL_ACL_CMDQ_REQ_NO_HIT_WIDTH (32)
#define NBL_ACL_CMDQ_REQ_NO_HIT_DWLEN (1)
union acl_cmdq_req_no_hit_u {
	struct acl_cmdq_req_no_hit {
		u32 cnt:32;              /* [31:00] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_ACL_CMDQ_REQ_NO_HIT_DWLEN];
} __packed;

#define NBL_ACL_INSERT_SEARCH_CTRL_ADDR  (0xb64880)
#define NBL_ACL_INSERT_SEARCH_CTRL_DEPTH (1)
#define NBL_ACL_INSERT_SEARCH_CTRL_WIDTH (32)
#define NBL_ACL_INSERT_SEARCH_CTRL_DWLEN (1)
union acl_insert_search_ctrl_u {
	struct acl_insert_search_ctrl {
		u32 profile_idx:4;       /* [03:00] Default:0x0 RW */
		u32 start:1;             /* [04:04] Default:0x0 WO */
		u32 rsv:27;              /* [31:05] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INSERT_SEARCH_CTRL_DWLEN];
} __packed;

#define NBL_ACL_INSERT_SEARCH_ACK_ADDR  (0xb64884)
#define NBL_ACL_INSERT_SEARCH_ACK_DEPTH (1)
#define NBL_ACL_INSERT_SEARCH_ACK_WIDTH (32)
#define NBL_ACL_INSERT_SEARCH_ACK_DWLEN (1)
union acl_insert_search_ack_u {
	struct acl_insert_search_ack {
		u32 ack:1;               /* [00:00] Default:0x0 RC */
		u32 status:2;            /* [02:01] Default:0x0 RWW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INSERT_SEARCH_ACK_DWLEN];
} __packed;

#define NBL_ACL_INSERT_SEARCH_DATA_ADDR  (0xb64890)
#define NBL_ACL_INSERT_SEARCH_DATA_DEPTH (20)
#define NBL_ACL_INSERT_SEARCH_DATA_WIDTH (32)
#define NBL_ACL_INSERT_SEARCH_DATA_DWLEN (1)
union acl_insert_search_data_u {
	struct acl_insert_search_data {
		u32 data:32;             /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INSERT_SEARCH_DATA_DWLEN];
} __packed;
#define NBL_ACL_INSERT_SEARCH_DATA_REG(r) (NBL_ACL_INSERT_SEARCH_DATA_ADDR + \
		(NBL_ACL_INSERT_SEARCH_DATA_DWLEN * 4) * (r))

#define NBL_ACL_INDIRECT_ACCESS_ACK_ADDR  (0xb648f0)
#define NBL_ACL_INDIRECT_ACCESS_ACK_DEPTH (1)
#define NBL_ACL_INDIRECT_ACCESS_ACK_WIDTH (32)
#define NBL_ACL_INDIRECT_ACCESS_ACK_DWLEN (1)
union acl_indirect_access_ack_u {
	struct acl_indirect_access_ack {
		u32 done:1;              /* [00:00] Default:0x0 RC */
		u32 status:16;           /* [16:01] Default:0x0 RWW */
		u32 rsv:15;              /* [31:17] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_ACCESS_ACK_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_CTRL_ADDR  (0xb648f4)
#define NBL_ACL_INDIRECT_CTRL_DEPTH (1)
#define NBL_ACL_INDIRECT_CTRL_WIDTH (32)
#define NBL_ACL_INDIRECT_CTRL_DWLEN (1)
union acl_indirect_ctrl_u {
	struct acl_indirect_ctrl {
		u32 tcam_addr:9;         /* [08:00] Default:0x0 RW */
		u32 cpu_acl_cfg_start:1; /* [09:09] Default:0x0 WO */
		u32 cpu_acl_cfg_rw:1;    /* [10:10] Default:0x0 RW */
		u32 rsv:5;               /* [15:11] Default:0x0 WO */
		u32 acc_btm:16;          /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_CTRL_DWLEN];
} __packed;

#define NBL_ACL_VALID_BIT_ADDR  (0xb64900)
#define NBL_ACL_VALID_BIT_DEPTH (1)
#define NBL_ACL_VALID_BIT_WIDTH (32)
#define NBL_ACL_VALID_BIT_DWLEN (1)
union acl_valid_bit_u {
	struct acl_valid_bit {
		u32 valid_bit:16;        /* [15:00] Default:0x0 RWW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_VALID_BIT_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM0_XL_ADDR  (0xb64904)
#define NBL_ACL_INDIRECT_TCAM0_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM0_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM0_XL_DWLEN (1)
union acl_indirect_tcam0_xl_u {
	struct acl_indirect_tcam0_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM0_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM0_XH_ADDR  (0xb64908)
#define NBL_ACL_INDIRECT_TCAM0_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM0_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM0_XH_DWLEN (1)
union acl_indirect_tcam0_xh_u {
	struct acl_indirect_tcam0_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM0_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM1_XL_ADDR  (0xb6490c)
#define NBL_ACL_INDIRECT_TCAM1_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM1_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM1_XL_DWLEN (1)
union acl_indirect_tcam1_xl_u {
	struct acl_indirect_tcam1_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM1_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM1_XH_ADDR  (0xb64910)
#define NBL_ACL_INDIRECT_TCAM1_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM1_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM1_XH_DWLEN (1)
union acl_indirect_tcam1_xh_u {
	struct acl_indirect_tcam1_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM1_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM2_XL_ADDR  (0xb64914)
#define NBL_ACL_INDIRECT_TCAM2_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM2_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM2_XL_DWLEN (1)
union acl_indirect_tcam2_xl_u {
	struct acl_indirect_tcam2_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM2_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM2_XH_ADDR  (0xb64918)
#define NBL_ACL_INDIRECT_TCAM2_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM2_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM2_XH_DWLEN (1)
union acl_indirect_tcam2_xh_u {
	struct acl_indirect_tcam2_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM2_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM3_XL_ADDR  (0xb6491c)
#define NBL_ACL_INDIRECT_TCAM3_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM3_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM3_XL_DWLEN (1)
union acl_indirect_tcam3_xl_u {
	struct acl_indirect_tcam3_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM3_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM3_XH_ADDR  (0xb64920)
#define NBL_ACL_INDIRECT_TCAM3_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM3_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM3_XH_DWLEN (1)
union acl_indirect_tcam3_xh_u {
	struct acl_indirect_tcam3_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM3_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM4_XL_ADDR  (0xb64924)
#define NBL_ACL_INDIRECT_TCAM4_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM4_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM4_XL_DWLEN (1)
union acl_indirect_tcam4_xl_u {
	struct acl_indirect_tcam4_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM4_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM4_XH_ADDR  (0xb64928)
#define NBL_ACL_INDIRECT_TCAM4_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM4_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM4_XH_DWLEN (1)
union acl_indirect_tcam4_xh_u {
	struct acl_indirect_tcam4_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM4_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM5_XL_ADDR  (0xb6492c)
#define NBL_ACL_INDIRECT_TCAM5_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM5_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM5_XL_DWLEN (1)
union acl_indirect_tcam5_xl_u {
	struct acl_indirect_tcam5_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM5_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM5_XH_ADDR  (0xb64930)
#define NBL_ACL_INDIRECT_TCAM5_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM5_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM5_XH_DWLEN (1)
union acl_indirect_tcam5_xh_u {
	struct acl_indirect_tcam5_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM5_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM6_XL_ADDR  (0xb64934)
#define NBL_ACL_INDIRECT_TCAM6_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM6_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM6_XL_DWLEN (1)
union acl_indirect_tcam6_xl_u {
	struct acl_indirect_tcam6_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM6_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM6_XH_ADDR  (0xb64938)
#define NBL_ACL_INDIRECT_TCAM6_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM6_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM6_XH_DWLEN (1)
union acl_indirect_tcam6_xh_u {
	struct acl_indirect_tcam6_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM6_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM7_XL_ADDR  (0xb6493c)
#define NBL_ACL_INDIRECT_TCAM7_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM7_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM7_XL_DWLEN (1)
union acl_indirect_tcam7_xl_u {
	struct acl_indirect_tcam7_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM7_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM7_XH_ADDR  (0xb64940)
#define NBL_ACL_INDIRECT_TCAM7_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM7_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM7_XH_DWLEN (1)
union acl_indirect_tcam7_xh_u {
	struct acl_indirect_tcam7_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM7_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM8_XL_ADDR  (0xb64944)
#define NBL_ACL_INDIRECT_TCAM8_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM8_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM8_XL_DWLEN (1)
union acl_indirect_tcam8_xl_u {
	struct acl_indirect_tcam8_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM8_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM8_XH_ADDR  (0xb64948)
#define NBL_ACL_INDIRECT_TCAM8_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM8_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM8_XH_DWLEN (1)
union acl_indirect_tcam8_xh_u {
	struct acl_indirect_tcam8_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM8_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM9_XL_ADDR  (0xb6494c)
#define NBL_ACL_INDIRECT_TCAM9_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM9_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM9_XL_DWLEN (1)
union acl_indirect_tcam9_xl_u {
	struct acl_indirect_tcam9_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM9_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM9_XH_ADDR  (0xb64950)
#define NBL_ACL_INDIRECT_TCAM9_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM9_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM9_XH_DWLEN (1)
union acl_indirect_tcam9_xh_u {
	struct acl_indirect_tcam9_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM9_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM10_XL_ADDR  (0xb64954)
#define NBL_ACL_INDIRECT_TCAM10_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM10_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM10_XL_DWLEN (1)
union acl_indirect_tcam10_xl_u {
	struct acl_indirect_tcam10_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM10_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM10_XH_ADDR  (0xb64958)
#define NBL_ACL_INDIRECT_TCAM10_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM10_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM10_XH_DWLEN (1)
union acl_indirect_tcam10_xh_u {
	struct acl_indirect_tcam10_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM10_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM11_XL_ADDR  (0xb6495c)
#define NBL_ACL_INDIRECT_TCAM11_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM11_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM11_XL_DWLEN (1)
union acl_indirect_tcam11_xl_u {
	struct acl_indirect_tcam11_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM11_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM11_XH_ADDR  (0xb64960)
#define NBL_ACL_INDIRECT_TCAM11_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM11_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM11_XH_DWLEN (1)
union acl_indirect_tcam11_xh_u {
	struct acl_indirect_tcam11_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM11_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM12_XL_ADDR  (0xb64964)
#define NBL_ACL_INDIRECT_TCAM12_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM12_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM12_XL_DWLEN (1)
union acl_indirect_tcam12_xl_u {
	struct acl_indirect_tcam12_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM12_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM12_XH_ADDR  (0xb64968)
#define NBL_ACL_INDIRECT_TCAM12_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM12_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM12_XH_DWLEN (1)
union acl_indirect_tcam12_xh_u {
	struct acl_indirect_tcam12_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM12_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM13_XL_ADDR  (0xb6496c)
#define NBL_ACL_INDIRECT_TCAM13_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM13_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM13_XL_DWLEN (1)
union acl_indirect_tcam13_xl_u {
	struct acl_indirect_tcam13_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM13_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM13_XH_ADDR  (0xb64970)
#define NBL_ACL_INDIRECT_TCAM13_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM13_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM13_XH_DWLEN (1)
union acl_indirect_tcam13_xh_u {
	struct acl_indirect_tcam13_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM13_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM14_XL_ADDR  (0xb64974)
#define NBL_ACL_INDIRECT_TCAM14_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM14_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM14_XL_DWLEN (1)
union acl_indirect_tcam14_xl_u {
	struct acl_indirect_tcam14_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM14_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM14_XH_ADDR  (0xb64978)
#define NBL_ACL_INDIRECT_TCAM14_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM14_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM14_XH_DWLEN (1)
union acl_indirect_tcam14_xh_u {
	struct acl_indirect_tcam14_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM14_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM15_XL_ADDR  (0xb6497c)
#define NBL_ACL_INDIRECT_TCAM15_XL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM15_XL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM15_XL_DWLEN (1)
union acl_indirect_tcam15_xl_u {
	struct acl_indirect_tcam15_xl {
		u32 xl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM15_XL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM15_XH_ADDR  (0xb64980)
#define NBL_ACL_INDIRECT_TCAM15_XH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM15_XH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM15_XH_DWLEN (1)
union acl_indirect_tcam15_xh_u {
	struct acl_indirect_tcam15_xh {
		u32 xh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM15_XH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM0_YL_ADDR  (0xb64990)
#define NBL_ACL_INDIRECT_TCAM0_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM0_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM0_YL_DWLEN (1)
union acl_indirect_tcam0_yl_u {
	struct acl_indirect_tcam0_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM0_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM0_YH_ADDR  (0xb64994)
#define NBL_ACL_INDIRECT_TCAM0_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM0_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM0_YH_DWLEN (1)
union acl_indirect_tcam0_yh_u {
	struct acl_indirect_tcam0_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM0_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM1_YL_ADDR  (0xb64998)
#define NBL_ACL_INDIRECT_TCAM1_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM1_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM1_YL_DWLEN (1)
union acl_indirect_tcam1_yl_u {
	struct acl_indirect_tcam1_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM1_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM1_YH_ADDR  (0xb6499c)
#define NBL_ACL_INDIRECT_TCAM1_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM1_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM1_YH_DWLEN (1)
union acl_indirect_tcam1_yh_u {
	struct acl_indirect_tcam1_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM1_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM2_YL_ADDR  (0xb649a0)
#define NBL_ACL_INDIRECT_TCAM2_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM2_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM2_YL_DWLEN (1)
union acl_indirect_tcam2_yl_u {
	struct acl_indirect_tcam2_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM2_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM2_YH_ADDR  (0xb649a4)
#define NBL_ACL_INDIRECT_TCAM2_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM2_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM2_YH_DWLEN (1)
union acl_indirect_tcam2_yh_u {
	struct acl_indirect_tcam2_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM2_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM3_YL_ADDR  (0xb649a8)
#define NBL_ACL_INDIRECT_TCAM3_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM3_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM3_YL_DWLEN (1)
union acl_indirect_tcam3_yl_u {
	struct acl_indirect_tcam3_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM3_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM3_YH_ADDR  (0xb649ac)
#define NBL_ACL_INDIRECT_TCAM3_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM3_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM3_YH_DWLEN (1)
union acl_indirect_tcam3_yh_u {
	struct acl_indirect_tcam3_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM3_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM4_YL_ADDR  (0xb649b0)
#define NBL_ACL_INDIRECT_TCAM4_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM4_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM4_YL_DWLEN (1)
union acl_indirect_tcam4_yl_u {
	struct acl_indirect_tcam4_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM4_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM4_YH_ADDR  (0xb649b4)
#define NBL_ACL_INDIRECT_TCAM4_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM4_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM4_YH_DWLEN (1)
union acl_indirect_tcam4_yh_u {
	struct acl_indirect_tcam4_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM4_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM5_YL_ADDR  (0xb649b8)
#define NBL_ACL_INDIRECT_TCAM5_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM5_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM5_YL_DWLEN (1)
union acl_indirect_tcam5_yl_u {
	struct acl_indirect_tcam5_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM5_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM5_YH_ADDR  (0xb649bc)
#define NBL_ACL_INDIRECT_TCAM5_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM5_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM5_YH_DWLEN (1)
union acl_indirect_tcam5_yh_u {
	struct acl_indirect_tcam5_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM5_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM6_YL_ADDR  (0xb649c0)
#define NBL_ACL_INDIRECT_TCAM6_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM6_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM6_YL_DWLEN (1)
union acl_indirect_tcam6_yl_u {
	struct acl_indirect_tcam6_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM6_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM6_YH_ADDR  (0xb649c4)
#define NBL_ACL_INDIRECT_TCAM6_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM6_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM6_YH_DWLEN (1)
union acl_indirect_tcam6_yh_u {
	struct acl_indirect_tcam6_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM6_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM7_YL_ADDR  (0xb649c8)
#define NBL_ACL_INDIRECT_TCAM7_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM7_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM7_YL_DWLEN (1)
union acl_indirect_tcam7_yl_u {
	struct acl_indirect_tcam7_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM7_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM7_YH_ADDR  (0xb649cc)
#define NBL_ACL_INDIRECT_TCAM7_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM7_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM7_YH_DWLEN (1)
union acl_indirect_tcam7_yh_u {
	struct acl_indirect_tcam7_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM7_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM8_YL_ADDR  (0xb649d0)
#define NBL_ACL_INDIRECT_TCAM8_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM8_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM8_YL_DWLEN (1)
union acl_indirect_tcam8_yl_u {
	struct acl_indirect_tcam8_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM8_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM8_YH_ADDR  (0xb649d4)
#define NBL_ACL_INDIRECT_TCAM8_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM8_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM8_YH_DWLEN (1)
union acl_indirect_tcam8_yh_u {
	struct acl_indirect_tcam8_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM8_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM9_YL_ADDR  (0xb649d8)
#define NBL_ACL_INDIRECT_TCAM9_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM9_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM9_YL_DWLEN (1)
union acl_indirect_tcam9_yl_u {
	struct acl_indirect_tcam9_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM9_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM9_YH_ADDR  (0xb649dc)
#define NBL_ACL_INDIRECT_TCAM9_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM9_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM9_YH_DWLEN (1)
union acl_indirect_tcam9_yh_u {
	struct acl_indirect_tcam9_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM9_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM10_YL_ADDR  (0xb649e0)
#define NBL_ACL_INDIRECT_TCAM10_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM10_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM10_YL_DWLEN (1)
union acl_indirect_tcam10_yl_u {
	struct acl_indirect_tcam10_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM10_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM10_YH_ADDR  (0xb649e4)
#define NBL_ACL_INDIRECT_TCAM10_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM10_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM10_YH_DWLEN (1)
union acl_indirect_tcam10_yh_u {
	struct acl_indirect_tcam10_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM10_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM11_YL_ADDR  (0xb649e8)
#define NBL_ACL_INDIRECT_TCAM11_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM11_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM11_YL_DWLEN (1)
union acl_indirect_tcam11_yl_u {
	struct acl_indirect_tcam11_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM11_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM11_YH_ADDR  (0xb649ec)
#define NBL_ACL_INDIRECT_TCAM11_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM11_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM11_YH_DWLEN (1)
union acl_indirect_tcam11_yh_u {
	struct acl_indirect_tcam11_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM11_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM12_YL_ADDR  (0xb649f0)
#define NBL_ACL_INDIRECT_TCAM12_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM12_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM12_YL_DWLEN (1)
union acl_indirect_tcam12_yl_u {
	struct acl_indirect_tcam12_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM12_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM12_YH_ADDR  (0xb649f4)
#define NBL_ACL_INDIRECT_TCAM12_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM12_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM12_YH_DWLEN (1)
union acl_indirect_tcam12_yh_u {
	struct acl_indirect_tcam12_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM12_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM13_YL_ADDR  (0xb649f8)
#define NBL_ACL_INDIRECT_TCAM13_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM13_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM13_YL_DWLEN (1)
union acl_indirect_tcam13_yl_u {
	struct acl_indirect_tcam13_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM13_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM13_YH_ADDR  (0xb649fc)
#define NBL_ACL_INDIRECT_TCAM13_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM13_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM13_YH_DWLEN (1)
union acl_indirect_tcam13_yh_u {
	struct acl_indirect_tcam13_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM13_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM14_YL_ADDR  (0xb64a00)
#define NBL_ACL_INDIRECT_TCAM14_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM14_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM14_YL_DWLEN (1)
union acl_indirect_tcam14_yl_u {
	struct acl_indirect_tcam14_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM14_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM14_YH_ADDR  (0xb64a04)
#define NBL_ACL_INDIRECT_TCAM14_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM14_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM14_YH_DWLEN (1)
union acl_indirect_tcam14_yh_u {
	struct acl_indirect_tcam14_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM14_YH_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM15_YL_ADDR  (0xb64a08)
#define NBL_ACL_INDIRECT_TCAM15_YL_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM15_YL_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM15_YL_DWLEN (1)
union acl_indirect_tcam15_yl_u {
	struct acl_indirect_tcam15_yl {
		u32 yl:32;               /* [31:00] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM15_YL_DWLEN];
} __packed;

#define NBL_ACL_INDIRECT_TCAM15_YH_ADDR  (0xb64a0c)
#define NBL_ACL_INDIRECT_TCAM15_YH_DEPTH (1)
#define NBL_ACL_INDIRECT_TCAM15_YH_WIDTH (32)
#define NBL_ACL_INDIRECT_TCAM15_YH_DWLEN (1)
union acl_indirect_tcam15_yh_u {
	struct acl_indirect_tcam15_yh {
		u32 yh:8;                /* [07:00] Default:0x0 RWW */
		u32 rsv:24;              /* [31:08] Default:0x0 RWW */
	} __packed info;
	u32 data[NBL_ACL_INDIRECT_TCAM15_YH_DWLEN];
} __packed;

#define NBL_ACL_KGEN_TCAM_ADDR  (0xb65800)
#define NBL_ACL_KGEN_TCAM_DEPTH (16)
#define NBL_ACL_KGEN_TCAM_WIDTH (64)
#define NBL_ACL_KGEN_TCAM_DWLEN (2)
union acl_kgen_tcam_u {
	struct acl_kgen_tcam {
		u32 mask:16;
		u32 data:16;
		u32 valid_bit:1;
		u32 rsv:31;
	} __packed info;
	u32 data[NBL_ACL_KGEN_TCAM_DWLEN];
} __packed;
#define NBL_ACL_KGEN_TCAM_REG(r) (NBL_ACL_KGEN_TCAM_ADDR + \
		(NBL_ACL_KGEN_TCAM_DWLEN * 4) * (r))

#define NBL_ACL_TCAM_CFG_ADDR  (0xb65a00)
#define NBL_ACL_TCAM_CFG_DEPTH (16)
#define NBL_ACL_TCAM_CFG_WIDTH (128)
#define NBL_ACL_TCAM_CFG_DWLEN (4)
union acl_tcam_cfg_u {
	struct acl_tcam_cfg {
		u32 startcompare0:1;     /* [00:00] Default:0x1 RW */
		u32 startset0:1;         /* [01:01] Default:0x1 RW */
		u32 tcam0_enable:1;      /* [02:02] Default:0x0 RW */
		u32 startcompare1:1;     /* [03:03] Default:0x1 RW */
		u32 startset1:1;         /* [04:04] Default:0x1 RW */
		u32 tcam1_enable:1;      /* [05:05] Default:0x0 RW */
		u32 startcompare2:1;     /* [06:06] Default:0x1 RW */
		u32 startset2:1;         /* [07:07] Default:0x1 RW */
		u32 tcam2_enable:1;      /* [08:08] Default:0x0 RW */
		u32 startcompare3:1;     /* [09:09] Default:0x1 RW */
		u32 startset3:1;         /* [10:10] Default:0x1 RW */
		u32 tcam3_enable:1;      /* [11:11] Default:0x0 RW */
		u32 startcompare4:1;     /* [12:12] Default:0x1 RW */
		u32 startset4:1;         /* [13:13] Default:0x1 RW */
		u32 tcam4_enable:1;      /* [14:14] Default:0x0 RW */
		u32 startcompare5:1;     /* [15:15] Default:0x1 RW */
		u32 startset5:1;         /* [16:16] Default:0x1 RW */
		u32 tcam5_enable:1;      /* [17:17] Default:0x0 RW */
		u32 startcompare6:1;     /* [18:18] Default:0x1 RW */
		u32 startset6:1;         /* [19:19] Default:0x1 RW */
		u32 tcam6_enable:1;      /* [20:20] Default:0x0 RW */
		u32 startcompare7:1;     /* [21:21] Default:0x1 RW */
		u32 startset7:1;         /* [22:22] Default:0x1 RW */
		u32 tcam7_enable:1;      /* [23:23] Default:0x0 RW */
		u32 startcompare8:1;     /* [24:24] Default:0x1 RW */
		u32 startset8:1;         /* [25:25] Default:0x1 RW */
		u32 tcam8_enable:1;      /* [26:26] Default:0x0 RW */
		u32 startcompare9:1;     /* [27:27] Default:0x1 RW */
		u32 startset9:1;         /* [28:28] Default:0x1 RW */
		u32 tcam9_enable:1;      /* [29:29] Default:0x0 RW */
		u32 startcompare10:1;    /* [30:30] Default:0x1 RW */
		u32 startset10:1;        /* [31:31] Default:0x1 RW */
		u32 tcam10_enable:1;     /* [32:32] Default:0x0 RW */
		u32 startcompare11:1;    /* [33:33] Default:0x1 RW */
		u32 startset11:1;        /* [34:34] Default:0x1 RW */
		u32 tcam11_enable:1;     /* [35:35] Default:0x0 RW */
		u32 startcompare12:1;    /* [36:36] Default:0x1 RW */
		u32 startset12:1;        /* [37:37] Default:0x1 RW */
		u32 tcam12_enable:1;     /* [38:38] Default:0x0 RW */
		u32 startcompare13:1;    /* [39:39] Default:0x1 RW */
		u32 startset13:1;        /* [40:40] Default:0x1 RW */
		u32 tcam13_enable:1;     /* [41:41] Default:0x0 RW */
		u32 startcompare14:1;    /* [42:42] Default:0x1 RW */
		u32 startset14:1;        /* [43:43] Default:0x1 RW */
		u32 tcam14_enable:1;     /* [44:44] Default:0x0 RW */
		u32 startcompare15:1;    /* [45:45] Default:0x1 RW */
		u32 startset15:1;        /* [46:46] Default:0x1 RW */
		u32 tcam15_enable:1;     /* [47:47] Default:0x0 RW */
		u32 key_id0:4;           /* [51:48] Default:0x0 RW */
		u32 key_id1:4;           /* [55:52] Default:0x0 RW */
		u32 key_id2:4;           /* [59:56] Default:0x0 RW */
		u32 key_id3:4;           /* [63:60] Default:0x0 RW */
		u32 key_id4:4;           /* [67:64] Default:0x0 RW */
		u32 key_id5:4;           /* [71:68] Default:0x0 RW */
		u32 key_id6:4;           /* [75:72] Default:0x0 RW */
		u32 key_id7:4;           /* [79:76] Default:0x0 RW */
		u32 key_id8:4;           /* [83:80] Default:0x0 RW */
		u32 key_id9:4;           /* [87:84] Default:0x0 RW */
		u32 key_id10:4;          /* [91:88] Default:0x0 RW */
		u32 key_id11:4;          /* [95:92] Default:0x0 RW */
		u32 key_id12:4;          /* [99:96] Default:0x0 RW */
		u32 key_id13:4;          /* [103:100] Default:0x0 RW */
		u32 key_id14:4;          /* [107:104] Default:0x0 RW */
		u32 key_id15:4;          /* [111:108] Default:0x0 RW */
		u32 rsv:16;              /* [127:112] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_TCAM_CFG_DWLEN];
} __packed;
#define NBL_ACL_TCAM_CFG_REG(r) (NBL_ACL_TCAM_CFG_ADDR + \
		(NBL_ACL_TCAM_CFG_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM_CFG_ADDR  (0xb65c00)
#define NBL_ACL_ACTION_RAM_CFG_DEPTH (16)
#define NBL_ACL_ACTION_RAM_CFG_WIDTH (128)
#define NBL_ACL_ACTION_RAM_CFG_DWLEN (4)
union acl_action_ram_cfg_u {
	struct acl_action_ram_cfg {
		u32 action_ram0_alloc_id:4; /* [03:00] Default:0x0 RW */
		u32 action_ram0_enable:1; /* [04:04] Default:0x0 RW */
		u32 action_ram1_alloc_id:4; /* [08:05] Default:0x0 RW */
		u32 action_ram1_enable:1; /* [09:09] Default:0x0 RW */
		u32 action_ram2_alloc_id:4; /* [13:10] Default:0x0 RW */
		u32 action_ram2_enable:1; /* [14:14] Default:0x0 RW */
		u32 action_ram3_alloc_id:4; /* [18:15] Default:0x0 RW */
		u32 action_ram3_enable:1; /* [19:19] Default:0x0 RW */
		u32 action_ram4_alloc_id:4; /* [23:20] Default:0x0 RW */
		u32 action_ram4_enable:1; /* [24:24] Default:0x0 RW */
		u32 action_ram5_alloc_id:4; /* [28:25] Default:0x0 RW */
		u32 action_ram5_enable:1; /* [29:29] Default:0x0 RW */
		u32 action_ram6_alloc_id:4; /* [33:30] Default:0x0 RW */
		u32 action_ram6_enable:1; /* [34:34] Default:0x0 RW */
		u32 action_ram7_alloc_id:4; /* [38:35] Default:0x0 RW */
		u32 action_ram7_enable:1; /* [39:39] Default:0x0 RW */
		u32 action_ram8_alloc_id:4; /* [43:40] Default:0x0 RW */
		u32 action_ram8_enable:1; /* [44:44] Default:0x0 RW */
		u32 action_ram9_alloc_id:4; /* [48:45] Default:0x0 RW */
		u32 action_ram9_enable:1; /* [49:49] Default:0x0 RW */
		u32 action_ram10_alloc_id:4; /* [53:50] Default:0x0 RW */
		u32 action_ram10_enable:1; /* [54:54] Default:0x0 RW */
		u32 action_ram11_alloc_id:4; /* [58:55] Default:0x0 RW */
		u32 action_ram11_enable:1; /* [59:59] Default:0x0 RW */
		u32 action_ram12_alloc_id:4; /* [63:60] Default:0x0 RW */
		u32 action_ram12_enable:1; /* [64:64] Default:0x0 RW */
		u32 action_ram13_alloc_id:4; /* [68:65] Default:0x0 RW */
		u32 action_ram13_enable:1; /* [69:69] Default:0x0 RW */
		u32 action_ram14_alloc_id:4; /* [73:70] Default:0x0 RW */
		u32 action_ram14_enable:1; /* [74:74] Default:0x0 RW */
		u32 action_ram15_alloc_id:4; /* [78:75] Default:0x0 RW */
		u32 action_ram15_enable:1; /* [79:79] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:80] Default:0x0 RO */
		u32 rsv_h:16;            /* [127:80] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM_CFG_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM_CFG_REG(r) (NBL_ACL_ACTION_RAM_CFG_ADDR + \
		(NBL_ACL_ACTION_RAM_CFG_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM0_ADDR  (0xb66000)
#define NBL_ACL_ACTION_RAM0_DEPTH (512)
#define NBL_ACL_ACTION_RAM0_WIDTH (128)
#define NBL_ACL_ACTION_RAM0_DWLEN (4)
union acl_action_ram0_u {
	struct acl_action_ram0 {
		u32 action0:22;          /* [21:00] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM0_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM0_REG(r) (NBL_ACL_ACTION_RAM0_ADDR + \
		(NBL_ACL_ACTION_RAM0_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM1_ADDR  (0xb68000)
#define NBL_ACL_ACTION_RAM1_DEPTH (512)
#define NBL_ACL_ACTION_RAM1_WIDTH (128)
#define NBL_ACL_ACTION_RAM1_DWLEN (4)
union acl_action_ram1_u {
	struct acl_action_ram1 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM1_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM1_REG(r) (NBL_ACL_ACTION_RAM1_ADDR + \
		(NBL_ACL_ACTION_RAM1_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM2_ADDR  (0xb6a000)
#define NBL_ACL_ACTION_RAM2_DEPTH (512)
#define NBL_ACL_ACTION_RAM2_WIDTH (128)
#define NBL_ACL_ACTION_RAM2_DWLEN (4)
union acl_action_ram2_u {
	struct acl_action_ram2 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM2_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM2_REG(r) (NBL_ACL_ACTION_RAM2_ADDR + \
		(NBL_ACL_ACTION_RAM2_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM3_ADDR  (0xb6c000)
#define NBL_ACL_ACTION_RAM3_DEPTH (512)
#define NBL_ACL_ACTION_RAM3_WIDTH (128)
#define NBL_ACL_ACTION_RAM3_DWLEN (4)
union acl_action_ram3_u {
	struct acl_action_ram3 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM3_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM3_REG(r) (NBL_ACL_ACTION_RAM3_ADDR + \
		(NBL_ACL_ACTION_RAM3_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM4_ADDR  (0xb6e000)
#define NBL_ACL_ACTION_RAM4_DEPTH (512)
#define NBL_ACL_ACTION_RAM4_WIDTH (128)
#define NBL_ACL_ACTION_RAM4_DWLEN (4)
union acl_action_ram4_u {
	struct acl_action_ram4 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM4_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM4_REG(r) (NBL_ACL_ACTION_RAM4_ADDR + \
		(NBL_ACL_ACTION_RAM4_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM5_ADDR  (0xb70000)
#define NBL_ACL_ACTION_RAM5_DEPTH (512)
#define NBL_ACL_ACTION_RAM5_WIDTH (128)
#define NBL_ACL_ACTION_RAM5_DWLEN (4)
union acl_action_ram5_u {
	struct acl_action_ram5 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM5_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM5_REG(r) (NBL_ACL_ACTION_RAM5_ADDR + \
		(NBL_ACL_ACTION_RAM5_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM6_ADDR  (0xb72000)
#define NBL_ACL_ACTION_RAM6_DEPTH (512)
#define NBL_ACL_ACTION_RAM6_WIDTH (128)
#define NBL_ACL_ACTION_RAM6_DWLEN (4)
union acl_action_ram6_u {
	struct acl_action_ram6 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM6_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM6_REG(r) (NBL_ACL_ACTION_RAM6_ADDR + \
		(NBL_ACL_ACTION_RAM6_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM7_ADDR  (0xb74000)
#define NBL_ACL_ACTION_RAM7_DEPTH (512)
#define NBL_ACL_ACTION_RAM7_WIDTH (128)
#define NBL_ACL_ACTION_RAM7_DWLEN (4)
union acl_action_ram7_u {
	struct acl_action_ram7 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM7_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM7_REG(r) (NBL_ACL_ACTION_RAM7_ADDR + \
		(NBL_ACL_ACTION_RAM7_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM8_ADDR  (0xb76000)
#define NBL_ACL_ACTION_RAM8_DEPTH (512)
#define NBL_ACL_ACTION_RAM8_WIDTH (128)
#define NBL_ACL_ACTION_RAM8_DWLEN (4)
union acl_action_ram8_u {
	struct acl_action_ram8 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM8_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM8_REG(r) (NBL_ACL_ACTION_RAM8_ADDR + \
		(NBL_ACL_ACTION_RAM8_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM9_ADDR  (0xb78000)
#define NBL_ACL_ACTION_RAM9_DEPTH (512)
#define NBL_ACL_ACTION_RAM9_WIDTH (128)
#define NBL_ACL_ACTION_RAM9_DWLEN (4)
union acl_action_ram9_u {
	struct acl_action_ram9 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM9_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM9_REG(r) (NBL_ACL_ACTION_RAM9_ADDR + \
		(NBL_ACL_ACTION_RAM9_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM10_ADDR  (0xb7a000)
#define NBL_ACL_ACTION_RAM10_DEPTH (512)
#define NBL_ACL_ACTION_RAM10_WIDTH (128)
#define NBL_ACL_ACTION_RAM10_DWLEN (4)
union acl_action_ram10_u {
	struct acl_action_ram10 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM10_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM10_REG(r) (NBL_ACL_ACTION_RAM10_ADDR + \
		(NBL_ACL_ACTION_RAM10_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM11_ADDR  (0xb7c000)
#define NBL_ACL_ACTION_RAM11_DEPTH (512)
#define NBL_ACL_ACTION_RAM11_WIDTH (128)
#define NBL_ACL_ACTION_RAM11_DWLEN (4)
union acl_action_ram11_u {
	struct acl_action_ram11 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM11_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM11_REG(r) (NBL_ACL_ACTION_RAM11_ADDR + \
		(NBL_ACL_ACTION_RAM11_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM12_ADDR  (0xb7e000)
#define NBL_ACL_ACTION_RAM12_DEPTH (512)
#define NBL_ACL_ACTION_RAM12_WIDTH (128)
#define NBL_ACL_ACTION_RAM12_DWLEN (4)
union acl_action_ram12_u {
	struct acl_action_ram12 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM12_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM12_REG(r) (NBL_ACL_ACTION_RAM12_ADDR + \
		(NBL_ACL_ACTION_RAM12_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM13_ADDR  (0xb80000)
#define NBL_ACL_ACTION_RAM13_DEPTH (512)
#define NBL_ACL_ACTION_RAM13_WIDTH (128)
#define NBL_ACL_ACTION_RAM13_DWLEN (4)
union acl_action_ram13_u {
	struct acl_action_ram13 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM13_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM13_REG(r) (NBL_ACL_ACTION_RAM13_ADDR + \
		(NBL_ACL_ACTION_RAM13_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM14_ADDR  (0xb82000)
#define NBL_ACL_ACTION_RAM14_DEPTH (512)
#define NBL_ACL_ACTION_RAM14_WIDTH (128)
#define NBL_ACL_ACTION_RAM14_DWLEN (4)
union acl_action_ram14_u {
	struct acl_action_ram14 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM14_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM14_REG(r) (NBL_ACL_ACTION_RAM14_ADDR + \
		(NBL_ACL_ACTION_RAM14_DWLEN * 4) * (r))

#define NBL_ACL_ACTION_RAM15_ADDR  (0xb84000)
#define NBL_ACL_ACTION_RAM15_DEPTH (512)
#define NBL_ACL_ACTION_RAM15_WIDTH (128)
#define NBL_ACL_ACTION_RAM15_DWLEN (4)
union acl_action_ram15_u {
	struct acl_action_ram15 {
		u32 action0:22;          /* [21:0] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_ACTION_RAM15_DWLEN];
} __packed;
#define NBL_ACL_ACTION_RAM15_REG(r) (NBL_ACL_ACTION_RAM15_ADDR + \
		(NBL_ACL_ACTION_RAM15_DWLEN * 4) * (r))

#define NBL_ACL_DEFAULT_ACTION_RAM_ADDR  (0xb86000)
#define NBL_ACL_DEFAULT_ACTION_RAM_DEPTH (16)
#define NBL_ACL_DEFAULT_ACTION_RAM_WIDTH (256)
#define NBL_ACL_DEFAULT_ACTION_RAM_DWLEN (8)
union acl_default_action_ram_u {
	struct acl_default_action_ram {
		u32 action0:22;          /* [21:00] Default:0x0 RW */
		u32 action1:22;          /* [43:22] Default:0x0 RW */
		u32 action2:22;          /* [65:44] Default:0x0 RW */
		u32 action3:22;          /* [87:66] Default:0x0 RW */
		u32 action4:22;          /* [109:88] Default:0x0 RW */
		u32 action5:22;          /* [131:110] Default:0x0 RW */
		u32 actoin6:22;          /* [153:132] Default:0x0 RW */
		u32 action7:22;          /* [175:154] Default:0x0 RW */
		u32 rsv:16;              /* [255:176] Default:0x0 RO */
		u32 rsv_arr[2];          /* [255:176] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_DEFAULT_ACTION_RAM_DWLEN];
} __packed;
#define NBL_ACL_DEFAULT_ACTION_RAM_REG(r) (NBL_ACL_DEFAULT_ACTION_RAM_ADDR + \
		(NBL_ACL_DEFAULT_ACTION_RAM_DWLEN * 4) * (r))

#define NBL_ACL_FLOW_ID_STAT_RAM_ADDR  (0xb94000)
#define NBL_ACL_FLOW_ID_STAT_RAM_DEPTH (131072)
#define NBL_ACL_FLOW_ID_STAT_RAM_WIDTH (128)
#define NBL_ACL_FLOW_ID_STAT_RAM_DWLEN (4)
union acl_flow_id_stat_ram_u {
	struct acl_flow_id_stat_ram {
		u32 pkt_byte_l:32;       /* [47:00] Default:0x0 RO */
		u32 pkt_byte_h:16;       /* [47:00] Default:0x0 RO */
		u32 pkt_cnt_l:32;        /* [87:48] Default:0x0 RO */
		u32 pkt_cnt_h:8;         /* [87:48] Default:0x0 RO */
		u32 rsv_l:32;            /* [127:88] Default:0x0 RO */
		u32 rsv_h:8;             /* [127:88] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_FLOW_ID_STAT_RAM_DWLEN];
} __packed;
#define NBL_ACL_FLOW_ID_STAT_RAM_REG(r) (NBL_ACL_FLOW_ID_STAT_RAM_ADDR + \
		(NBL_ACL_FLOW_ID_STAT_RAM_DWLEN * 4) * (r))

#define NBL_ACL_STAT_ID_STAT_RAM_ADDR  (0xd94000)
#define NBL_ACL_STAT_ID_STAT_RAM_DEPTH (2048)
#define NBL_ACL_STAT_ID_STAT_RAM_WIDTH (128)
#define NBL_ACL_STAT_ID_STAT_RAM_DWLEN (4)
union acl_stat_id_stat_ram_u {
	struct acl_stat_id_stat_ram {
		u32 pkt_byte_arr[2];     /* [63:0] Default:0x0 RO */
		u32 pkt_cnt_arr[2];      /* [127:64] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_ACL_STAT_ID_STAT_RAM_DWLEN];
} __packed;
#define NBL_ACL_STAT_ID_STAT_RAM_REG(r) (NBL_ACL_STAT_ID_STAT_RAM_ADDR + \
		(NBL_ACL_STAT_ID_STAT_RAM_DWLEN * 4) * (r))

#endif
