/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
 // Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_DPED_H
#define NBL_DPED_H 1

#include <linux/types.h>

#define NBL_DPED_BASE (0x0075C000)

#define NBL_DPED_INT_STATUS_ADDR  (0x75c000)
#define NBL_DPED_INT_STATUS_DEPTH (1)
#define NBL_DPED_INT_STATUS_WIDTH (32)
#define NBL_DPED_INT_STATUS_DWLEN (1)
union dped_int_status_u {
	struct dped_int_status {
		u32 pkt_length_err:1;    /* [0] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fsm_err:1;           /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 input_err:1;         /* [5] Default:0x0 RWC */
		u32 cfg_err:1;           /* [6] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [7] Default:0x0 RWC */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 RWC */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 RWC */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 RWC */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x0 RWC */
		u32 meta_value_err:1;    /* [12] Default:0x0 RWC */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 RWC */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 RWC */
		u32 edit_pos_err:1;      /* [15] Default:0x0 RWC */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 RWC */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 RWC */
		u32 add_head_ovf:1;      /* [18] Default:0x0 RWC */
		u32 rsv:13;              /* [31:19] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INT_STATUS_DWLEN];
} __packed;

#define NBL_DPED_INT_MASK_ADDR  (0x75c004)
#define NBL_DPED_INT_MASK_DEPTH (1)
#define NBL_DPED_INT_MASK_WIDTH (32)
#define NBL_DPED_INT_MASK_DWLEN (1)
union dped_int_mask_u {
	struct dped_int_mask {
		u32 pkt_length_err:1;    /* [0] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RW */
		u32 fsm_err:1;           /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 input_err:1;         /* [5] Default:0x0 RW */
		u32 cfg_err:1;           /* [6] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [7] Default:0x0 RW */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 RW */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 RW */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 RW */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x1 RW */
		u32 meta_value_err:1;    /* [12] Default:0x0 RW */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 RW */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 RW */
		u32 edit_pos_err:1;      /* [15] Default:0x0 RW */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 RW */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 RW */
		u32 add_head_ovf:1;      /* [18] Default:0x0 RW */
		u32 rsv:13;              /* [31:19] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INT_MASK_DWLEN];
} __packed;

#define NBL_DPED_INT_SET_ADDR  (0x75c008)
#define NBL_DPED_INT_SET_DEPTH (1)
#define NBL_DPED_INT_SET_WIDTH (32)
#define NBL_DPED_INT_SET_DWLEN (1)
union dped_int_set_u {
	struct dped_int_set {
		u32 pkt_length_err:1;    /* [0] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 WO */
		u32 fsm_err:1;           /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 input_err:1;         /* [5] Default:0x0 WO */
		u32 cfg_err:1;           /* [6] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [7] Default:0x0 WO */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 WO */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 WO */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 WO */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x0 WO */
		u32 meta_value_err:1;    /* [12] Default:0x0 WO */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 WO */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 WO */
		u32 edit_pos_err:1;      /* [15] Default:0x0 WO */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 WO */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 WO */
		u32 add_head_ovf:1;      /* [18] Default:0x0 WO */
		u32 rsv:13;              /* [31:19] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INT_SET_DWLEN];
} __packed;

#define NBL_DPED_INIT_DONE_ADDR  (0x75c00c)
#define NBL_DPED_INIT_DONE_DEPTH (1)
#define NBL_DPED_INIT_DONE_WIDTH (32)
#define NBL_DPED_INIT_DONE_DWLEN (1)
union dped_init_done_u {
	struct dped_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INIT_DONE_DWLEN];
} __packed;

#define NBL_DPED_PKT_LENGTH_ERR_INFO_ADDR  (0x75c020)
#define NBL_DPED_PKT_LENGTH_ERR_INFO_DEPTH (1)
#define NBL_DPED_PKT_LENGTH_ERR_INFO_WIDTH (32)
#define NBL_DPED_PKT_LENGTH_ERR_INFO_DWLEN (1)
union dped_pkt_length_err_info_u {
	struct dped_pkt_length_err_info {
		u32 ptr_eop:1;           /* [0] Default:0x0 RC */
		u32 pkt_eop:1;           /* [1] Default:0x0 RC */
		u32 pkt_mod:1;           /* [2] Default:0x0 RC */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_PKT_LENGTH_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_CIF_ERR_INFO_ADDR  (0x75c040)
#define NBL_DPED_CIF_ERR_INFO_DEPTH (1)
#define NBL_DPED_CIF_ERR_INFO_WIDTH (32)
#define NBL_DPED_CIF_ERR_INFO_DWLEN (1)
union dped_cif_err_info_u {
	struct dped_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_INPUT_ERR_INFO_ADDR  (0x75c048)
#define NBL_DPED_INPUT_ERR_INFO_DEPTH (1)
#define NBL_DPED_INPUT_ERR_INFO_WIDTH (32)
#define NBL_DPED_INPUT_ERR_INFO_DWLEN (1)
union dped_input_err_info_u {
	struct dped_input_err_info {
		u32 eoc_miss:1;          /* [0] Default:0x0 RC */
		u32 soc_miss:1;          /* [1] Default:0x0 RC */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INPUT_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_CFG_ERR_INFO_ADDR  (0x75c050)
#define NBL_DPED_CFG_ERR_INFO_DEPTH (1)
#define NBL_DPED_CFG_ERR_INFO_WIDTH (32)
#define NBL_DPED_CFG_ERR_INFO_DWLEN (1)
union dped_cfg_err_info_u {
	struct dped_cfg_err_info {
		u32 length:1;            /* [0] Default:0x0 RC */
		u32 rd_conflict:1;       /* [1] Default:0x0 RC */
		u32 rd_addr:8;           /* [9:2] Default:0x0 RC */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_FWD_ATID_NOMAT_ERR_INFO_ADDR  (0x75c06c)
#define NBL_DPED_FWD_ATID_NOMAT_ERR_INFO_DEPTH (1)
#define NBL_DPED_FWD_ATID_NOMAT_ERR_INFO_WIDTH (32)
#define NBL_DPED_FWD_ATID_NOMAT_ERR_INFO_DWLEN (1)
union dped_fwd_atid_nomat_err_info_u {
	struct dped_fwd_atid_nomat_err_info {
		u32 dport:1;             /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_ATID_NOMAT_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_META_VALUE_ERR_INFO_ADDR  (0x75c070)
#define NBL_DPED_META_VALUE_ERR_INFO_DEPTH (1)
#define NBL_DPED_META_VALUE_ERR_INFO_WIDTH (32)
#define NBL_DPED_META_VALUE_ERR_INFO_DWLEN (1)
union dped_meta_value_err_info_u {
	struct dped_meta_value_err_info {
		u32 sport:1;             /* [0] Default:0x0 RC */
		u32 dport:1;             /* [1] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [2] Default:0x0 RC */
		u32 tnl:1;               /* [3] Default:0x0 RC */
		u32 vni:1;               /* [4] Default:0x0 RC */
		u32 vni_one:1;           /* [5] Default:0x0 RC */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_META_VALUE_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_EDIT_ATNUM_ERR_INFO_ADDR  (0x75c078)
#define NBL_DPED_EDIT_ATNUM_ERR_INFO_DEPTH (1)
#define NBL_DPED_EDIT_ATNUM_ERR_INFO_WIDTH (32)
#define NBL_DPED_EDIT_ATNUM_ERR_INFO_DWLEN (1)
union dped_edit_atnum_err_info_u {
	struct dped_edit_atnum_err_info {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 del_add:1;           /* [1] Default:0x0 RC */
		u32 ttl:1;               /* [2] Default:0x0 RC */
		u32 dscp:1;              /* [3] Default:0x0 RC */
		u32 tnl:1;               /* [4] Default:0x0 RC */
		u32 sport:1;             /* [5] Default:0x0 RC */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_EDIT_ATNUM_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPED_HEADER_OFT_OVF_ADDR  (0x75c080)
#define NBL_DPED_HEADER_OFT_OVF_DEPTH (1)
#define NBL_DPED_HEADER_OFT_OVF_WIDTH (32)
#define NBL_DPED_HEADER_OFT_OVF_DWLEN (1)
union dped_header_oft_ovf_u {
	struct dped_header_oft_ovf {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 rsv2:7;              /* [7:1] Default:0x0 RO */
		u32 add_del:6;           /* [13:8] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [14] Default:0x0 RC */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 ttl:1;               /* [16] Default:0x0 RC */
		u32 sctp:1;              /* [17] Default:0x0 RC */
		u32 dscp:1;              /* [18] Default:0x0 RC */
		u32 pri:1;               /* [19] Default:0x0 RC */
		u32 len0:1;              /* [20] Default:0x0 RC */
		u32 len1:1;              /* [21] Default:0x0 RC */
		u32 ck0:1;               /* [22] Default:0x0 RC */
		u32 ck1:1;               /* [23] Default:0x0 RC */
		u32 ck_start0_0:1;       /* [24] Default:0x0 RC */
		u32 ck_start0_1:1;       /* [25] Default:0x0 RC */
		u32 ck_start1_0:1;       /* [26] Default:0x0 RC */
		u32 ck_start1_1:1;       /* [27] Default:0x0 RC */
		u32 head:1;              /* [28] Default:0x0 RC */
		u32 ck_len0:1;           /* [29] Default:0x0 RC */
		u32 ck_len1:1;           /* [30] Default:0x0 RC */
		u32 rsv:1;               /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HEADER_OFT_OVF_DWLEN];
} __packed;

#define NBL_DPED_EDIT_POS_ERR_ADDR  (0x75c088)
#define NBL_DPED_EDIT_POS_ERR_DEPTH (1)
#define NBL_DPED_EDIT_POS_ERR_WIDTH (32)
#define NBL_DPED_EDIT_POS_ERR_DWLEN (1)
union dped_edit_pos_err_u {
	struct dped_edit_pos_err {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 cross_level:6;       /* [6:1] Default:0x0 RC */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 add_del:6;           /* [13:8] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [14] Default:0x0 RC */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 ttl:1;               /* [16] Default:0x0 RC */
		u32 sctp:1;              /* [17] Default:0x0 RC */
		u32 dscp:1;              /* [18] Default:0x0 RC */
		u32 pri:1;               /* [19] Default:0x0 RC */
		u32 len0:1;              /* [20] Default:0x0 RC */
		u32 len1:1;              /* [21] Default:0x0 RC */
		u32 ck0:1;               /* [22] Default:0x0 RC */
		u32 ck1:1;               /* [23] Default:0x0 RC */
		u32 ck_start0_0:1;       /* [24] Default:0x0 RC */
		u32 ck_start0_1:1;       /* [25] Default:0x0 RC */
		u32 ck_start1_0:1;       /* [26] Default:0x0 RC */
		u32 ck_start1_1:1;       /* [27] Default:0x0 RC */
		u32 ck_len0:1;           /* [28] Default:0x0 RC */
		u32 ck_len1:1;           /* [29] Default:0x0 RC */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_EDIT_POS_ERR_DWLEN];
} __packed;

#define NBL_DPED_DA_OFT_LEN_OVF_ADDR  (0x75c090)
#define NBL_DPED_DA_OFT_LEN_OVF_DEPTH (1)
#define NBL_DPED_DA_OFT_LEN_OVF_WIDTH (32)
#define NBL_DPED_DA_OFT_LEN_OVF_DWLEN (1)
union dped_da_oft_len_ovf_u {
	struct dped_da_oft_len_ovf {
		u32 at0:5;               /* [4:0] Default:0x0 RC */
		u32 at1:5;               /* [9:5] Default:0x0 RC */
		u32 at2:5;               /* [14:10] Default:0x0 RC */
		u32 at3:5;               /* [19:15] Default:0x0 RC */
		u32 at4:5;               /* [24:20] Default:0x0 RC */
		u32 at5:5;               /* [29:25] Default:0x0 RC */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_DA_OFT_LEN_OVF_DWLEN];
} __packed;

#define NBL_DPED_LXOFFSET_OVF_ADDR  (0x75c098)
#define NBL_DPED_LXOFFSET_OVF_DEPTH (1)
#define NBL_DPED_LXOFFSET_OVF_WIDTH (32)
#define NBL_DPED_LXOFFSET_OVF_DWLEN (1)
union dped_lxoffset_ovf_u {
	struct dped_lxoffset_ovf {
		u32 l2:1;                /* [0] Default:0x0 RC */
		u32 l3:1;                /* [1] Default:0x0 RC */
		u32 l4:1;                /* [2] Default:0x0 RC */
		u32 pld:1;               /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_LXOFFSET_OVF_DWLEN];
} __packed;

#define NBL_DPED_ADD_HEAD_OVF_ADDR  (0x75c0a0)
#define NBL_DPED_ADD_HEAD_OVF_DEPTH (1)
#define NBL_DPED_ADD_HEAD_OVF_WIDTH (32)
#define NBL_DPED_ADD_HEAD_OVF_DWLEN (1)
union dped_add_head_ovf_u {
	struct dped_add_head_ovf {
		u32 tnl_l2:1;            /* [0] Default:0x0 RC */
		u32 tnl_pkt:1;           /* [1] Default:0x0 RC */
		u32 rsv1:14;             /* [15:2] Default:0x0 RO */
		u32 mir_l2:1;            /* [16] Default:0x0 RC */
		u32 mir_pkt:1;           /* [17] Default:0x0 RC */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_ADD_HEAD_OVF_DWLEN];
} __packed;

#define NBL_DPED_CAR_CTRL_ADDR  (0x75c100)
#define NBL_DPED_CAR_CTRL_DEPTH (1)
#define NBL_DPED_CAR_CTRL_WIDTH (32)
#define NBL_DPED_CAR_CTRL_DWLEN (1)
union dped_car_ctrl_u {
	struct dped_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_CAR_CTRL_DWLEN];
} __packed;

#define NBL_DPED_INIT_START_ADDR  (0x75c10c)
#define NBL_DPED_INIT_START_DEPTH (1)
#define NBL_DPED_INIT_START_WIDTH (32)
#define NBL_DPED_INIT_START_DWLEN (1)
union dped_init_start_u {
	struct dped_init_start {
		u32 start:1;             /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INIT_START_DWLEN];
} __packed;

#define NBL_DPED_TIMEOUT_CFG_ADDR  (0x75c110)
#define NBL_DPED_TIMEOUT_CFG_DEPTH (1)
#define NBL_DPED_TIMEOUT_CFG_WIDTH (32)
#define NBL_DPED_TIMEOUT_CFG_DWLEN (1)
union dped_timeout_cfg_u {
	struct dped_timeout_cfg {
		u32 fsm_max_num:16;      /* [15:00] Default:0xfff RW */
		u32 tab:8;               /* [23:16] Default:0x40 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TIMEOUT_CFG_DWLEN];
} __packed;

#define NBL_DPED_TNL_MAX_LENGTH_ADDR  (0x75c154)
#define NBL_DPED_TNL_MAX_LENGTH_DEPTH (1)
#define NBL_DPED_TNL_MAX_LENGTH_WIDTH (32)
#define NBL_DPED_TNL_MAX_LENGTH_DWLEN (1)
union dped_tnl_max_length_u {
	struct dped_tnl_max_length {
		u32 th:7;                /* [6:0] Default:0x5A RW */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TNL_MAX_LENGTH_DWLEN];
} __packed;

#define NBL_DPED_PKT_DROP_EN_ADDR  (0x75c170)
#define NBL_DPED_PKT_DROP_EN_DEPTH (1)
#define NBL_DPED_PKT_DROP_EN_WIDTH (32)
#define NBL_DPED_PKT_DROP_EN_DWLEN (1)
union dped_pkt_drop_en_u {
	struct dped_pkt_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_PKT_DROP_EN_DWLEN];
} __packed;

#define NBL_DPED_PKT_HERR_DROP_EN_ADDR  (0x75c174)
#define NBL_DPED_PKT_HERR_DROP_EN_DEPTH (1)
#define NBL_DPED_PKT_HERR_DROP_EN_WIDTH (32)
#define NBL_DPED_PKT_HERR_DROP_EN_DWLEN (1)
union dped_pkt_herr_drop_en_u {
	struct dped_pkt_herr_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_PKT_HERR_DROP_EN_DWLEN];
} __packed;

#define NBL_DPED_PKT_PARITY_DROP_EN_ADDR  (0x75c178)
#define NBL_DPED_PKT_PARITY_DROP_EN_DEPTH (1)
#define NBL_DPED_PKT_PARITY_DROP_EN_WIDTH (32)
#define NBL_DPED_PKT_PARITY_DROP_EN_DWLEN (1)
union dped_pkt_parity_drop_en_u {
	struct dped_pkt_parity_drop_en {
		u32 en0:1;               /* [0] Default:0x1 RW */
		u32 en1:1;               /* [1] Default:0x1 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_PKT_PARITY_DROP_EN_DWLEN];
} __packed;

#define NBL_DPED_TTL_DROP_EN_ADDR  (0x75c17c)
#define NBL_DPED_TTL_DROP_EN_DEPTH (1)
#define NBL_DPED_TTL_DROP_EN_WIDTH (32)
#define NBL_DPED_TTL_DROP_EN_DWLEN (1)
union dped_ttl_drop_en_u {
	struct dped_ttl_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TTL_DROP_EN_DWLEN];
} __packed;

#define NBL_DPED_TTL_ERROR_CODE_ADDR  (0x75c188)
#define NBL_DPED_TTL_ERROR_CODE_DEPTH (1)
#define NBL_DPED_TTL_ERROR_CODE_WIDTH (32)
#define NBL_DPED_TTL_ERROR_CODE_DWLEN (1)
union dped_ttl_error_code_u {
	struct dped_ttl_error_code {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv1:7;              /* [7:1] Default:0x0 RO */
		u32 id:4;                /* [11:8] Default:0x6 RW */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TTL_ERROR_CODE_DWLEN];
} __packed;

#define NBL_DPED_HIGH_PRI_PKT_EN_ADDR  (0x75c190)
#define NBL_DPED_HIGH_PRI_PKT_EN_DEPTH (1)
#define NBL_DPED_HIGH_PRI_PKT_EN_WIDTH (32)
#define NBL_DPED_HIGH_PRI_PKT_EN_DWLEN (1)
union dped_high_pri_pkt_en_u {
	struct dped_high_pri_pkt_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HIGH_PRI_PKT_EN_DWLEN];
} __packed;

#define NBL_DPED_PADDING_CFG_ADDR  (0x75c194)
#define NBL_DPED_PADDING_CFG_DEPTH (1)
#define NBL_DPED_PADDING_CFG_WIDTH (32)
#define NBL_DPED_PADDING_CFG_DWLEN (1)
union dped_padding_cfg_u {
	struct dped_padding_cfg {
		u32 th:6;                /* [5:0] Default:0x3B RW */
		u32 rsv1:2;              /* [7:6] Default:0x0 RO */
		u32 mode:2;              /* [9:8] Default:0x0 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_PADDING_CFG_DWLEN];
} __packed;

#define NBL_DPED_HW_EDIT_FLAG_SEL0_ADDR  (0x75c204)
#define NBL_DPED_HW_EDIT_FLAG_SEL0_DEPTH (1)
#define NBL_DPED_HW_EDIT_FLAG_SEL0_WIDTH (32)
#define NBL_DPED_HW_EDIT_FLAG_SEL0_DWLEN (1)
union dped_hw_edit_flag_sel0_u {
	struct dped_hw_edit_flag_sel0 {
		u32 oft:5;               /* [4:0] Default:0x1 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDIT_FLAG_SEL0_DWLEN];
} __packed;

#define NBL_DPED_HW_EDIT_FLAG_SEL1_ADDR  (0x75c208)
#define NBL_DPED_HW_EDIT_FLAG_SEL1_DEPTH (1)
#define NBL_DPED_HW_EDIT_FLAG_SEL1_WIDTH (32)
#define NBL_DPED_HW_EDIT_FLAG_SEL1_DWLEN (1)
union dped_hw_edit_flag_sel1_u {
	struct dped_hw_edit_flag_sel1 {
		u32 oft:5;               /* [4:0] Default:0x2 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDIT_FLAG_SEL1_DWLEN];
} __packed;

#define NBL_DPED_HW_EDIT_FLAG_SEL2_ADDR  (0x75c20c)
#define NBL_DPED_HW_EDIT_FLAG_SEL2_DEPTH (1)
#define NBL_DPED_HW_EDIT_FLAG_SEL2_WIDTH (32)
#define NBL_DPED_HW_EDIT_FLAG_SEL2_DWLEN (1)
union dped_hw_edit_flag_sel2_u {
	struct dped_hw_edit_flag_sel2 {
		u32 oft:5;               /* [4:0] Default:0x3 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDIT_FLAG_SEL2_DWLEN];
} __packed;

#define NBL_DPED_HW_EDIT_FLAG_SEL3_ADDR  (0x75c210)
#define NBL_DPED_HW_EDIT_FLAG_SEL3_DEPTH (1)
#define NBL_DPED_HW_EDIT_FLAG_SEL3_WIDTH (32)
#define NBL_DPED_HW_EDIT_FLAG_SEL3_DWLEN (1)
union dped_hw_edit_flag_sel3_u {
	struct dped_hw_edit_flag_sel3 {
		u32 oft:5;               /* [4:0] Default:0x4 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDIT_FLAG_SEL3_DWLEN];
} __packed;

#define NBL_DPED_HW_EDIT_FLAG_SEL4_ADDR  (0x75c214)
#define NBL_DPED_HW_EDIT_FLAG_SEL4_DEPTH (1)
#define NBL_DPED_HW_EDIT_FLAG_SEL4_WIDTH (32)
#define NBL_DPED_HW_EDIT_FLAG_SEL4_DWLEN (1)
union dped_hw_edit_flag_sel4_u {
	struct dped_hw_edit_flag_sel4 {
		u32 oft:5;               /* [4:0] Default:0xe RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDIT_FLAG_SEL4_DWLEN];
} __packed;

#define NBL_DPED_RDMA_FLAG_ADDR  (0x75c22c)
#define NBL_DPED_RDMA_FLAG_DEPTH (1)
#define NBL_DPED_RDMA_FLAG_WIDTH (32)
#define NBL_DPED_RDMA_FLAG_DWLEN (1)
union dped_rdma_flag_u {
	struct dped_rdma_flag {
		u32 oft:5;               /* [4:0] Default:0xa RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_RDMA_FLAG_DWLEN];
} __packed;

#define NBL_DPED_FWD_DPORT_ADDR  (0x75c230)
#define NBL_DPED_FWD_DPORT_DEPTH (1)
#define NBL_DPED_FWD_DPORT_WIDTH (32)
#define NBL_DPED_FWD_DPORT_DWLEN (1)
union dped_fwd_dport_u {
	struct dped_fwd_dport {
		u32 id:6;                /* [5:0] Default:0x9 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_DPORT_DWLEN];
} __packed;

#define NBL_DPED_FWD_MIRID_ADDR  (0x75c238)
#define NBL_DPED_FWD_MIRID_DEPTH (1)
#define NBL_DPED_FWD_MIRID_WIDTH (32)
#define NBL_DPED_FWD_MIRID_DWLEN (1)
union dped_fwd_mirid_u {
	struct dped_fwd_mirid {
		u32 id:6;                /* [5:0] Default:0x8 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_MIRID_DWLEN];
} __packed;

#define NBL_DPED_FWD_VNI0_ADDR  (0x75c244)
#define NBL_DPED_FWD_VNI0_DEPTH (1)
#define NBL_DPED_FWD_VNI0_WIDTH (32)
#define NBL_DPED_FWD_VNI0_DWLEN (1)
union dped_fwd_vni0_u {
	struct dped_fwd_vni0 {
		u32 id:6;                /* [5:0] Default:0xe RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_VNI0_DWLEN];
} __packed;

#define NBL_DPED_FWD_VNI1_ADDR  (0x75c248)
#define NBL_DPED_FWD_VNI1_DEPTH (1)
#define NBL_DPED_FWD_VNI1_WIDTH (32)
#define NBL_DPED_FWD_VNI1_DWLEN (1)
union dped_fwd_vni1_u {
	struct dped_fwd_vni1 {
		u32 id:6;                /* [5:0] Default:0xf RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_VNI1_DWLEN];
} __packed;

#define NBL_DPED_FWD_PRI_MDF_ADDR  (0x75c250)
#define NBL_DPED_FWD_PRI_MDF_DEPTH (1)
#define NBL_DPED_FWD_PRI_MDF_WIDTH (32)
#define NBL_DPED_FWD_PRI_MDF_DWLEN (1)
union dped_fwd_pri_mdf_u {
	struct dped_fwd_pri_mdf {
		u32 id:6;                /* [5:0] Default:0x15 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_FWD_PRI_MDF_DWLEN];
} __packed;

#define NBL_DPED_VLAN_TYPE0_ADDR  (0x75c260)
#define NBL_DPED_VLAN_TYPE0_DEPTH (1)
#define NBL_DPED_VLAN_TYPE0_WIDTH (32)
#define NBL_DPED_VLAN_TYPE0_DWLEN (1)
union dped_vlan_type0_u {
	struct dped_vlan_type0 {
		u32 vau:16;              /* [15:0] Default:0x8100 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_VLAN_TYPE0_DWLEN];
} __packed;

#define NBL_DPED_VLAN_TYPE1_ADDR  (0x75c264)
#define NBL_DPED_VLAN_TYPE1_DEPTH (1)
#define NBL_DPED_VLAN_TYPE1_WIDTH (32)
#define NBL_DPED_VLAN_TYPE1_DWLEN (1)
union dped_vlan_type1_u {
	struct dped_vlan_type1 {
		u32 vau:16;              /* [15:0] Default:0x88A8 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_VLAN_TYPE1_DWLEN];
} __packed;

#define NBL_DPED_VLAN_TYPE2_ADDR  (0x75c268)
#define NBL_DPED_VLAN_TYPE2_DEPTH (1)
#define NBL_DPED_VLAN_TYPE2_WIDTH (32)
#define NBL_DPED_VLAN_TYPE2_DWLEN (1)
union dped_vlan_type2_u {
	struct dped_vlan_type2 {
		u32 vau:16;              /* [15:0] Default:0x9100 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_VLAN_TYPE2_DWLEN];
} __packed;

#define NBL_DPED_VLAN_TYPE3_ADDR  (0x75c26c)
#define NBL_DPED_VLAN_TYPE3_DEPTH (1)
#define NBL_DPED_VLAN_TYPE3_WIDTH (32)
#define NBL_DPED_VLAN_TYPE3_DWLEN (1)
union dped_vlan_type3_u {
	struct dped_vlan_type3 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_VLAN_TYPE3_DWLEN];
} __packed;

#define NBL_DPED_L3_LEN_MDY_CMD_0_ADDR  (0x75c300)
#define NBL_DPED_L3_LEN_MDY_CMD_0_DEPTH (1)
#define NBL_DPED_L3_LEN_MDY_CMD_0_WIDTH (32)
#define NBL_DPED_L3_LEN_MDY_CMD_0_DWLEN (1)
union dped_l3_len_mdy_cmd_0_u {
	struct dped_l3_len_mdy_cmd_0 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0x2 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x2 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x2 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x0 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L3_LEN_MDY_CMD_0_DWLEN];
} __packed;

#define NBL_DPED_L3_LEN_MDY_CMD_1_ADDR  (0x75c304)
#define NBL_DPED_L3_LEN_MDY_CMD_1_DEPTH (1)
#define NBL_DPED_L3_LEN_MDY_CMD_1_WIDTH (32)
#define NBL_DPED_L3_LEN_MDY_CMD_1_DWLEN (1)
union dped_l3_len_mdy_cmd_1_u {
	struct dped_l3_len_mdy_cmd_1 {
		u32 value:8;             /* [7:0] Default:0x28 RW */
		u32 in_oft:7;            /* [14:8] Default:0x4 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x2 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x1 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x0 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L3_LEN_MDY_CMD_1_DWLEN];
} __packed;

#define NBL_DPED_L4_LEN_MDY_CMD_0_ADDR  (0x75c308)
#define NBL_DPED_L4_LEN_MDY_CMD_0_DEPTH (1)
#define NBL_DPED_L4_LEN_MDY_CMD_0_WIDTH (32)
#define NBL_DPED_L4_LEN_MDY_CMD_0_DWLEN (1)
union dped_l4_len_mdy_cmd_0_u {
	struct dped_l4_len_mdy_cmd_0 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0xc RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x3 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x0 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x1 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_LEN_MDY_CMD_0_DWLEN];
} __packed;

#define NBL_DPED_L4_LEN_MDY_CMD_1_ADDR  (0x75c30c)
#define NBL_DPED_L4_LEN_MDY_CMD_1_DEPTH (1)
#define NBL_DPED_L4_LEN_MDY_CMD_1_WIDTH (32)
#define NBL_DPED_L4_LEN_MDY_CMD_1_DWLEN (1)
union dped_l4_len_mdy_cmd_1_u {
	struct dped_l4_len_mdy_cmd_1 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0x4 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x3 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x0 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x1 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_LEN_MDY_CMD_1_DWLEN];
} __packed;

#define NBL_DPED_L3_CK_CMD_00_ADDR  (0x75c310)
#define NBL_DPED_L3_CK_CMD_00_DEPTH (1)
#define NBL_DPED_L3_CK_CMD_00_WIDTH (32)
#define NBL_DPED_L3_CK_CMD_00_DWLEN (1)
union dped_l3_ck_cmd_00_u {
	struct dped_l3_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0xa RW */
		u32 phid:2;              /* [27:26] Default:0x2 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L3_CK_CMD_00_DWLEN];
} __packed;

#define NBL_DPED_L3_CK_CMD_01_ADDR  (0x75c314)
#define NBL_DPED_L3_CK_CMD_01_DEPTH (1)
#define NBL_DPED_L3_CK_CMD_01_WIDTH (32)
#define NBL_DPED_L3_CK_CMD_01_DWLEN (1)
union dped_l3_ck_cmd_01_u {
	struct dped_l3_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_L3_CK_CMD_01_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_00_ADDR  (0x75c318)
#define NBL_DPED_L4_CK_CMD_00_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_00_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_00_DWLEN (1)
union dped_l4_ck_cmd_00_u {
	struct dped_l4_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x6 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x10 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_00_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_01_ADDR  (0x75c31c)
#define NBL_DPED_L4_CK_CMD_01_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_01_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_01_DWLEN (1)
union dped_l4_ck_cmd_01_u {
	struct dped_l4_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_01_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_10_ADDR  (0x75c320)
#define NBL_DPED_L4_CK_CMD_10_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_10_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_10_DWLEN (1)
union dped_l4_ck_cmd_10_u {
	struct dped_l4_ck_cmd_10 {
		u32 value:8;             /* [7:0] Default:0x11 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_10_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_11_ADDR  (0x75c324)
#define NBL_DPED_L4_CK_CMD_11_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_11_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_11_DWLEN (1)
union dped_l4_ck_cmd_11_u {
	struct dped_l4_ck_cmd_11 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_11_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_20_ADDR  (0x75c328)
#define NBL_DPED_L4_CK_CMD_20_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_20_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_20_DWLEN (1)
union dped_l4_ck_cmd_20_u {
	struct dped_l4_ck_cmd_20 {
		u32 value:8;             /* [7:0] Default:0x2e RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x10 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_20_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_21_ADDR  (0x75c32c)
#define NBL_DPED_L4_CK_CMD_21_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_21_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_21_DWLEN (1)
union dped_l4_ck_cmd_21_u {
	struct dped_l4_ck_cmd_21 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_21_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_30_ADDR  (0x75c330)
#define NBL_DPED_L4_CK_CMD_30_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_30_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_30_DWLEN (1)
union dped_l4_ck_cmd_30_u {
	struct dped_l4_ck_cmd_30 {
		u32 value:8;             /* [7:0] Default:0x39 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_30_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_31_ADDR  (0x75c334)
#define NBL_DPED_L4_CK_CMD_31_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_31_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_31_DWLEN (1)
union dped_l4_ck_cmd_31_u {
	struct dped_l4_ck_cmd_31 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_31_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_40_ADDR  (0x75c338)
#define NBL_DPED_L4_CK_CMD_40_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_40_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_40_DWLEN (1)
union dped_l4_ck_cmd_40_u {
	struct dped_l4_ck_cmd_40 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x8 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x1 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_40_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_41_ADDR  (0x75c33c)
#define NBL_DPED_L4_CK_CMD_41_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_41_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_41_DWLEN (1)
union dped_l4_ck_cmd_41_u {
	struct dped_l4_ck_cmd_41 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x0 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x0 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_41_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_50_ADDR  (0x75c340)
#define NBL_DPED_L4_CK_CMD_50_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_50_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_50_DWLEN (1)
union dped_l4_ck_cmd_50_u {
	struct dped_l4_ck_cmd_50 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x2 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_50_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_51_ADDR  (0x75c344)
#define NBL_DPED_L4_CK_CMD_51_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_51_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_51_DWLEN (1)
union dped_l4_ck_cmd_51_u {
	struct dped_l4_ck_cmd_51 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x0 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_51_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_60_ADDR  (0x75c348)
#define NBL_DPED_L4_CK_CMD_60_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_60_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_60_DWLEN (1)
union dped_l4_ck_cmd_60_u {
	struct dped_l4_ck_cmd_60 {
		u32 value:8;             /* [7:0] Default:0x62 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x2 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_60_DWLEN];
} __packed;

#define NBL_DPED_L4_CK_CMD_61_ADDR  (0x75c34c)
#define NBL_DPED_L4_CK_CMD_61_DEPTH (1)
#define NBL_DPED_L4_CK_CMD_61_WIDTH (32)
#define NBL_DPED_L4_CK_CMD_61_DWLEN (1)
union dped_l4_ck_cmd_61_u {
	struct dped_l4_ck_cmd_61 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x0 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x0 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_L4_CK_CMD_61_DWLEN];
} __packed;

#define NBL_DPED_TNL_L3_CK_CMD_00_ADDR  (0x75c350)
#define NBL_DPED_TNL_L3_CK_CMD_00_DEPTH (1)
#define NBL_DPED_TNL_L3_CK_CMD_00_WIDTH (32)
#define NBL_DPED_TNL_L3_CK_CMD_00_DWLEN (1)
union dped_tnl_l3_ck_cmd_00_u {
	struct dped_tnl_l3_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0xa RW */
		u32 phid:2;              /* [27:26] Default:0x2 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L3_CK_CMD_00_DWLEN];
} __packed;

#define NBL_DPED_TNL_L3_CK_CMD_01_ADDR  (0x75c354)
#define NBL_DPED_TNL_L3_CK_CMD_01_DEPTH (1)
#define NBL_DPED_TNL_L3_CK_CMD_01_WIDTH (32)
#define NBL_DPED_TNL_L3_CK_CMD_01_DWLEN (1)
union dped_tnl_l3_ck_cmd_01_u {
	struct dped_tnl_l3_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L3_CK_CMD_01_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_00_ADDR  (0x75c360)
#define NBL_DPED_TNL_L4_CK_CMD_00_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_00_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_00_DWLEN (1)
union dped_tnl_l4_ck_cmd_00_u {
	struct dped_tnl_l4_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x11 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_00_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_01_ADDR  (0x75c364)
#define NBL_DPED_TNL_L4_CK_CMD_01_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_01_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_01_DWLEN (1)
union dped_tnl_l4_ck_cmd_01_u {
	struct dped_tnl_l4_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_01_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_10_ADDR  (0x75c368)
#define NBL_DPED_TNL_L4_CK_CMD_10_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_10_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_10_DWLEN (1)
union dped_tnl_l4_ck_cmd_10_u {
	struct dped_tnl_l4_ck_cmd_10 {
		u32 value:8;             /* [7:0] Default:0x39 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_10_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_11_ADDR  (0x75c36c)
#define NBL_DPED_TNL_L4_CK_CMD_11_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_11_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_11_DWLEN (1)
union dped_tnl_l4_ck_cmd_11_u {
	struct dped_tnl_l4_ck_cmd_11 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_11_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_20_ADDR  (0x75c370)
#define NBL_DPED_TNL_L4_CK_CMD_20_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_20_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_20_DWLEN (1)
union dped_tnl_l4_ck_cmd_20_u {
	struct dped_tnl_l4_ck_cmd_20 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x0 RW */
		u32 phid:2;              /* [27:26] Default:0x0 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_20_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_21_ADDR  (0x75c374)
#define NBL_DPED_TNL_L4_CK_CMD_21_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_21_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_21_DWLEN (1)
union dped_tnl_l4_ck_cmd_21_u {
	struct dped_tnl_l4_ck_cmd_21 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x14 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_21_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_30_ADDR  (0x75c378)
#define NBL_DPED_TNL_L4_CK_CMD_30_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_30_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_30_DWLEN (1)
union dped_tnl_l4_ck_cmd_30_u {
	struct dped_tnl_l4_ck_cmd_30 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x0 RW */
		u32 phid:2;              /* [27:26] Default:0x0 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_30_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_31_ADDR  (0x75c37c)
#define NBL_DPED_TNL_L4_CK_CMD_31_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_31_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_31_DWLEN (1)
union dped_tnl_l4_ck_cmd_31_u {
	struct dped_tnl_l4_ck_cmd_31 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x8 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_31_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_40_ADDR  (0x75c380)
#define NBL_DPED_TNL_L4_CK_CMD_40_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_40_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_40_DWLEN (1)
union dped_tnl_l4_ck_cmd_40_u {
	struct dped_tnl_l4_ck_cmd_40 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x0 RW */
		u32 phid:2;              /* [27:26] Default:0x0 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_40_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_41_ADDR  (0x75c384)
#define NBL_DPED_TNL_L4_CK_CMD_41_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_41_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_41_DWLEN (1)
union dped_tnl_l4_ck_cmd_41_u {
	struct dped_tnl_l4_ck_cmd_41 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x8 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_41_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_50_ADDR  (0x75c388)
#define NBL_DPED_TNL_L4_CK_CMD_50_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_50_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_50_DWLEN (1)
union dped_tnl_l4_ck_cmd_50_u {
	struct dped_tnl_l4_ck_cmd_50 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x0 RW */
		u32 phid:2;              /* [27:26] Default:0x0 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_50_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_51_ADDR  (0x75c38c)
#define NBL_DPED_TNL_L4_CK_CMD_51_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_51_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_51_DWLEN (1)
union dped_tnl_l4_ck_cmd_51_u {
	struct dped_tnl_l4_ck_cmd_51 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x8 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_51_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_60_ADDR  (0x75c390)
#define NBL_DPED_TNL_L4_CK_CMD_60_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_60_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_60_DWLEN (1)
union dped_tnl_l4_ck_cmd_60_u {
	struct dped_tnl_l4_ck_cmd_60 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x0 RW */
		u32 phid:2;              /* [27:26] Default:0x0 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_60_DWLEN];
} __packed;

#define NBL_DPED_TNL_L4_CK_CMD_61_ADDR  (0x75c394)
#define NBL_DPED_TNL_L4_CK_CMD_61_DEPTH (1)
#define NBL_DPED_TNL_L4_CK_CMD_61_WIDTH (32)
#define NBL_DPED_TNL_L4_CK_CMD_61_DWLEN (1)
union dped_tnl_l4_ck_cmd_61_u {
	struct dped_tnl_l4_ck_cmd_61 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x8 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DPED_TNL_L4_CK_CMD_61_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_00_ADDR  (0x75c3a0)
#define NBL_DPED_MIR_CMD_00_DEPTH (1)
#define NBL_DPED_MIR_CMD_00_WIDTH (32)
#define NBL_DPED_MIR_CMD_00_DWLEN (1)
union dped_mir_cmd_00_u {
	struct dped_mir_cmd_00 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_00_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_01_ADDR  (0x75c3a4)
#define NBL_DPED_MIR_CMD_01_DEPTH (1)
#define NBL_DPED_MIR_CMD_01_WIDTH (32)
#define NBL_DPED_MIR_CMD_01_DWLEN (1)
union dped_mir_cmd_01_u {
	struct dped_mir_cmd_01 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_01_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_10_ADDR  (0x75c3a8)
#define NBL_DPED_MIR_CMD_10_DEPTH (1)
#define NBL_DPED_MIR_CMD_10_WIDTH (32)
#define NBL_DPED_MIR_CMD_10_DWLEN (1)
union dped_mir_cmd_10_u {
	struct dped_mir_cmd_10 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_10_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_11_ADDR  (0x75c3ac)
#define NBL_DPED_MIR_CMD_11_DEPTH (1)
#define NBL_DPED_MIR_CMD_11_WIDTH (32)
#define NBL_DPED_MIR_CMD_11_DWLEN (1)
union dped_mir_cmd_11_u {
	struct dped_mir_cmd_11 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_11_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_20_ADDR  (0x75c3b0)
#define NBL_DPED_MIR_CMD_20_DEPTH (1)
#define NBL_DPED_MIR_CMD_20_WIDTH (32)
#define NBL_DPED_MIR_CMD_20_DWLEN (1)
union dped_mir_cmd_20_u {
	struct dped_mir_cmd_20 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_20_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_21_ADDR  (0x75c3b4)
#define NBL_DPED_MIR_CMD_21_DEPTH (1)
#define NBL_DPED_MIR_CMD_21_WIDTH (32)
#define NBL_DPED_MIR_CMD_21_DWLEN (1)
union dped_mir_cmd_21_u {
	struct dped_mir_cmd_21 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_21_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_30_ADDR  (0x75c3b8)
#define NBL_DPED_MIR_CMD_30_DEPTH (1)
#define NBL_DPED_MIR_CMD_30_WIDTH (32)
#define NBL_DPED_MIR_CMD_30_DWLEN (1)
union dped_mir_cmd_30_u {
	struct dped_mir_cmd_30 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_30_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_31_ADDR  (0x75c3bc)
#define NBL_DPED_MIR_CMD_31_DEPTH (1)
#define NBL_DPED_MIR_CMD_31_WIDTH (32)
#define NBL_DPED_MIR_CMD_31_DWLEN (1)
union dped_mir_cmd_31_u {
	struct dped_mir_cmd_31 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_31_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_40_ADDR  (0x75c3c0)
#define NBL_DPED_MIR_CMD_40_DEPTH (1)
#define NBL_DPED_MIR_CMD_40_WIDTH (32)
#define NBL_DPED_MIR_CMD_40_DWLEN (1)
union dped_mir_cmd_40_u {
	struct dped_mir_cmd_40 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_40_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_41_ADDR  (0x75c3c4)
#define NBL_DPED_MIR_CMD_41_DEPTH (1)
#define NBL_DPED_MIR_CMD_41_WIDTH (32)
#define NBL_DPED_MIR_CMD_41_DWLEN (1)
union dped_mir_cmd_41_u {
	struct dped_mir_cmd_41 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_41_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_50_ADDR  (0x75c3c8)
#define NBL_DPED_MIR_CMD_50_DEPTH (1)
#define NBL_DPED_MIR_CMD_50_WIDTH (32)
#define NBL_DPED_MIR_CMD_50_DWLEN (1)
union dped_mir_cmd_50_u {
	struct dped_mir_cmd_50 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_50_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_51_ADDR  (0x75c3cc)
#define NBL_DPED_MIR_CMD_51_DEPTH (1)
#define NBL_DPED_MIR_CMD_51_WIDTH (32)
#define NBL_DPED_MIR_CMD_51_DWLEN (1)
union dped_mir_cmd_51_u {
	struct dped_mir_cmd_51 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_51_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_60_ADDR  (0x75c3d0)
#define NBL_DPED_MIR_CMD_60_DEPTH (1)
#define NBL_DPED_MIR_CMD_60_WIDTH (32)
#define NBL_DPED_MIR_CMD_60_DWLEN (1)
union dped_mir_cmd_60_u {
	struct dped_mir_cmd_60 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_60_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_61_ADDR  (0x75c3d4)
#define NBL_DPED_MIR_CMD_61_DEPTH (1)
#define NBL_DPED_MIR_CMD_61_WIDTH (32)
#define NBL_DPED_MIR_CMD_61_DWLEN (1)
union dped_mir_cmd_61_u {
	struct dped_mir_cmd_61 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_61_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_70_ADDR  (0x75c3d8)
#define NBL_DPED_MIR_CMD_70_DEPTH (1)
#define NBL_DPED_MIR_CMD_70_WIDTH (32)
#define NBL_DPED_MIR_CMD_70_DWLEN (1)
union dped_mir_cmd_70_u {
	struct dped_mir_cmd_70 {
		u32 len:7;               /* [6:0] Default:0x0 RW */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 oft:7;               /* [14:8] Default:0x0 RW */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 mode:1;              /* [16] Default:0x0 RW */
		u32 en:1;                /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_70_DWLEN];
} __packed;

#define NBL_DPED_MIR_CMD_71_ADDR  (0x75c3dc)
#define NBL_DPED_MIR_CMD_71_DEPTH (1)
#define NBL_DPED_MIR_CMD_71_WIDTH (32)
#define NBL_DPED_MIR_CMD_71_DWLEN (1)
union dped_mir_cmd_71_u {
	struct dped_mir_cmd_71 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 type_sel:2;          /* [17:16] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIR_CMD_71_DWLEN];
} __packed;

#define NBL_DPED_DSCP_CK_EN_ADDR  (0x75c3e8)
#define NBL_DPED_DSCP_CK_EN_DEPTH (1)
#define NBL_DPED_DSCP_CK_EN_WIDTH (32)
#define NBL_DPED_DSCP_CK_EN_DWLEN (1)
union dped_dscp_ck_en_u {
	struct dped_dscp_ck_en {
		u32 l4_en:1;             /* [0] Default:0x0 RW */
		u32 l3_en:1;             /* [1] Default:0x1 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_DSCP_CK_EN_DWLEN];
} __packed;

#define NBL_DPED_RDMA_ECN_REMARK_ADDR  (0x75c3f0)
#define NBL_DPED_RDMA_ECN_REMARK_DEPTH (1)
#define NBL_DPED_RDMA_ECN_REMARK_WIDTH (32)
#define NBL_DPED_RDMA_ECN_REMARK_DWLEN (1)
union dped_rdma_ecn_remark_u {
	struct dped_rdma_ecn_remark {
		u32 vau:2;               /* [1:0] Default:0x1 RW */
		u32 rsv1:2;              /* [3:2] Default:0x0 RO */
		u32 en:1;                /* [4] Default:0x0 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_RDMA_ECN_REMARK_DWLEN];
} __packed;

#define NBL_DPED_VLAN_OFFSET_ADDR  (0x75c3f4)
#define NBL_DPED_VLAN_OFFSET_DEPTH (1)
#define NBL_DPED_VLAN_OFFSET_WIDTH (32)
#define NBL_DPED_VLAN_OFFSET_DWLEN (1)
union dped_vlan_offset_u {
	struct dped_vlan_offset {
		u32 oft:8;               /* [7:0] Default:0xC RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_VLAN_OFFSET_DWLEN];
} __packed;

#define NBL_DPED_DSCP_OFFSET_0_ADDR  (0x75c3f8)
#define NBL_DPED_DSCP_OFFSET_0_DEPTH (1)
#define NBL_DPED_DSCP_OFFSET_0_WIDTH (32)
#define NBL_DPED_DSCP_OFFSET_0_DWLEN (1)
union dped_dscp_offset_0_u {
	struct dped_dscp_offset_0 {
		u32 oft:8;               /* [7:0] Default:0x8 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_DSCP_OFFSET_0_DWLEN];
} __packed;

#define NBL_DPED_DSCP_OFFSET_1_ADDR  (0x75c3fc)
#define NBL_DPED_DSCP_OFFSET_1_DEPTH (1)
#define NBL_DPED_DSCP_OFFSET_1_WIDTH (32)
#define NBL_DPED_DSCP_OFFSET_1_DWLEN (1)
union dped_dscp_offset_1_u {
	struct dped_dscp_offset_1 {
		u32 oft:8;               /* [7:0] Default:0x4 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_DSCP_OFFSET_1_DWLEN];
} __packed;

#define NBL_DPED_CFG_TEST_ADDR  (0x75c600)
#define NBL_DPED_CFG_TEST_DEPTH (1)
#define NBL_DPED_CFG_TEST_WIDTH (32)
#define NBL_DPED_CFG_TEST_DWLEN (1)
union dped_cfg_test_u {
	struct dped_cfg_test {
		u32 test:32;             /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_CFG_TEST_DWLEN];
} __packed;

#define NBL_DPED_BP_STATE_ADDR  (0x75c608)
#define NBL_DPED_BP_STATE_DEPTH (1)
#define NBL_DPED_BP_STATE_WIDTH (32)
#define NBL_DPED_BP_STATE_DWLEN (1)
union dped_bp_state_u {
	struct dped_bp_state {
		u32 bm_rtn_tout:1;       /* [0] Default:0x0 RO */
		u32 bm_not_rdy:1;        /* [1] Default:0x0 RO */
		u32 dprbac_fc:1;         /* [2] Default:0x0 RO */
		u32 qm_fc:1;             /* [3] Default:0x0 RO */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_BP_STATE_DWLEN];
} __packed;

#define NBL_DPED_BP_HISTORY_ADDR  (0x75c60c)
#define NBL_DPED_BP_HISTORY_DEPTH (1)
#define NBL_DPED_BP_HISTORY_WIDTH (32)
#define NBL_DPED_BP_HISTORY_DWLEN (1)
union dped_bp_history_u {
	struct dped_bp_history {
		u32 bm_rtn_tout:1;       /* [0] Default:0x0 RC */
		u32 bm_not_rdy:1;        /* [1] Default:0x0 RC */
		u32 dprbac_fc:1;         /* [2] Default:0x0 RC */
		u32 qm_fc:1;             /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_BP_HISTORY_DWLEN];
} __packed;

#define NBL_DPED_MIRID_IND_ADDR  (0x75c900)
#define NBL_DPED_MIRID_IND_DEPTH (1)
#define NBL_DPED_MIRID_IND_WIDTH (32)
#define NBL_DPED_MIRID_IND_DWLEN (1)
union dped_mirid_ind_u {
	struct dped_mirid_ind {
		u32 nomat:1;             /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MIRID_IND_DWLEN];
} __packed;

#define NBL_DPED_MD_AUX_OFT_ADDR  (0x75c904)
#define NBL_DPED_MD_AUX_OFT_DEPTH (1)
#define NBL_DPED_MD_AUX_OFT_WIDTH (32)
#define NBL_DPED_MD_AUX_OFT_DWLEN (1)
union dped_md_aux_oft_u {
	struct dped_md_aux_oft {
		u32 l2_oft:8;            /* [7:0] Default:0x0 RO */
		u32 l3_oft:8;            /* [15:8] Default:0x0 RO */
		u32 l4_oft:8;            /* [23:16] Default:0x0 RO */
		u32 pld_oft:8;           /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_AUX_OFT_DWLEN];
} __packed;

#define NBL_DPED_MD_AUX_PKT_LEN_ADDR  (0x75c908)
#define NBL_DPED_MD_AUX_PKT_LEN_DEPTH (1)
#define NBL_DPED_MD_AUX_PKT_LEN_WIDTH (32)
#define NBL_DPED_MD_AUX_PKT_LEN_DWLEN (1)
union dped_md_aux_pkt_len_u {
	struct dped_md_aux_pkt_len {
		u32 len:14;              /* [13:0] Default:0x0 RO */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_AUX_PKT_LEN_DWLEN];
} __packed;

#define NBL_DPED_MD_FWD_MIR_ADDR  (0x75c90c)
#define NBL_DPED_MD_FWD_MIR_DEPTH (1)
#define NBL_DPED_MD_FWD_MIR_WIDTH (32)
#define NBL_DPED_MD_FWD_MIR_DWLEN (1)
union dped_md_fwd_mir_u {
	struct dped_md_fwd_mir {
		u32 id:4;                /* [3:0] Default:0x0 RO */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_FWD_MIR_DWLEN];
} __packed;

#define NBL_DPED_MD_FWD_DPORT_ADDR  (0x75c910)
#define NBL_DPED_MD_FWD_DPORT_DEPTH (1)
#define NBL_DPED_MD_FWD_DPORT_WIDTH (32)
#define NBL_DPED_MD_FWD_DPORT_DWLEN (1)
union dped_md_fwd_dport_u {
	struct dped_md_fwd_dport {
		u32 id:16;               /* [15:0] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_FWD_DPORT_DWLEN];
} __packed;

#define NBL_DPED_MD_AUX_PLD_CKSUM_ADDR  (0x75c914)
#define NBL_DPED_MD_AUX_PLD_CKSUM_DEPTH (1)
#define NBL_DPED_MD_AUX_PLD_CKSUM_WIDTH (32)
#define NBL_DPED_MD_AUX_PLD_CKSUM_DWLEN (1)
union dped_md_aux_pld_cksum_u {
	struct dped_md_aux_pld_cksum {
		u32 ck:32;               /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_AUX_PLD_CKSUM_DWLEN];
} __packed;

#define NBL_DPED_INNER_PKT_CKSUM_ADDR  (0x75c918)
#define NBL_DPED_INNER_PKT_CKSUM_DEPTH (1)
#define NBL_DPED_INNER_PKT_CKSUM_WIDTH (32)
#define NBL_DPED_INNER_PKT_CKSUM_DWLEN (1)
union dped_inner_pkt_cksum_u {
	struct dped_inner_pkt_cksum {
		u32 ck:16;               /* [15:0] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_INNER_PKT_CKSUM_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_0_ADDR  (0x75c920)
#define NBL_DPED_MD_EDIT_0_DEPTH (1)
#define NBL_DPED_MD_EDIT_0_WIDTH (32)
#define NBL_DPED_MD_EDIT_0_DWLEN (1)
union dped_md_edit_0_u {
	struct dped_md_edit_0 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_0_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_1_ADDR  (0x75c924)
#define NBL_DPED_MD_EDIT_1_DEPTH (1)
#define NBL_DPED_MD_EDIT_1_WIDTH (32)
#define NBL_DPED_MD_EDIT_1_DWLEN (1)
union dped_md_edit_1_u {
	struct dped_md_edit_1 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_1_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_2_ADDR  (0x75c928)
#define NBL_DPED_MD_EDIT_2_DEPTH (1)
#define NBL_DPED_MD_EDIT_2_WIDTH (32)
#define NBL_DPED_MD_EDIT_2_DWLEN (1)
union dped_md_edit_2_u {
	struct dped_md_edit_2 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_2_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_3_ADDR  (0x75c92c)
#define NBL_DPED_MD_EDIT_3_DEPTH (1)
#define NBL_DPED_MD_EDIT_3_WIDTH (32)
#define NBL_DPED_MD_EDIT_3_DWLEN (1)
union dped_md_edit_3_u {
	struct dped_md_edit_3 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_3_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_4_ADDR  (0x75c930)
#define NBL_DPED_MD_EDIT_4_DEPTH (1)
#define NBL_DPED_MD_EDIT_4_WIDTH (32)
#define NBL_DPED_MD_EDIT_4_DWLEN (1)
union dped_md_edit_4_u {
	struct dped_md_edit_4 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_4_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_5_ADDR  (0x75c934)
#define NBL_DPED_MD_EDIT_5_DEPTH (1)
#define NBL_DPED_MD_EDIT_5_WIDTH (32)
#define NBL_DPED_MD_EDIT_5_DWLEN (1)
union dped_md_edit_5_u {
	struct dped_md_edit_5 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_5_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_6_ADDR  (0x75c938)
#define NBL_DPED_MD_EDIT_6_DEPTH (1)
#define NBL_DPED_MD_EDIT_6_WIDTH (32)
#define NBL_DPED_MD_EDIT_6_DWLEN (1)
union dped_md_edit_6_u {
	struct dped_md_edit_6 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_6_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_7_ADDR  (0x75c93c)
#define NBL_DPED_MD_EDIT_7_DEPTH (1)
#define NBL_DPED_MD_EDIT_7_WIDTH (32)
#define NBL_DPED_MD_EDIT_7_DWLEN (1)
union dped_md_edit_7_u {
	struct dped_md_edit_7 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_7_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_8_ADDR  (0x75c940)
#define NBL_DPED_MD_EDIT_8_DEPTH (1)
#define NBL_DPED_MD_EDIT_8_WIDTH (32)
#define NBL_DPED_MD_EDIT_8_DWLEN (1)
union dped_md_edit_8_u {
	struct dped_md_edit_8 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_8_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_9_ADDR  (0x75c944)
#define NBL_DPED_MD_EDIT_9_DEPTH (1)
#define NBL_DPED_MD_EDIT_9_WIDTH (32)
#define NBL_DPED_MD_EDIT_9_DWLEN (1)
union dped_md_edit_9_u {
	struct dped_md_edit_9 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_9_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_10_ADDR  (0x75c948)
#define NBL_DPED_MD_EDIT_10_DEPTH (1)
#define NBL_DPED_MD_EDIT_10_WIDTH (32)
#define NBL_DPED_MD_EDIT_10_DWLEN (1)
union dped_md_edit_10_u {
	struct dped_md_edit_10 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_10_DWLEN];
} __packed;

#define NBL_DPED_MD_EDIT_11_ADDR  (0x75c94c)
#define NBL_DPED_MD_EDIT_11_DEPTH (1)
#define NBL_DPED_MD_EDIT_11_WIDTH (32)
#define NBL_DPED_MD_EDIT_11_DWLEN (1)
union dped_md_edit_11_u {
	struct dped_md_edit_11 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_MD_EDIT_11_DWLEN];
} __packed;

#define NBL_DPED_ADD_DEL_LEN_ADDR  (0x75c950)
#define NBL_DPED_ADD_DEL_LEN_DEPTH (1)
#define NBL_DPED_ADD_DEL_LEN_WIDTH (32)
#define NBL_DPED_ADD_DEL_LEN_DWLEN (1)
union dped_add_del_len_u {
	struct dped_add_del_len {
		u32 len:9;               /* [8:0] Default:0x0 RO */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_ADD_DEL_LEN_DWLEN];
} __packed;

#define NBL_DPED_TTL_INFO_ADDR  (0x75c970)
#define NBL_DPED_TTL_INFO_DEPTH (1)
#define NBL_DPED_TTL_INFO_WIDTH (32)
#define NBL_DPED_TTL_INFO_DWLEN (1)
union dped_ttl_info_u {
	struct dped_ttl_info {
		u32 old_ttl:8;           /* [7:0] Default:0x0 RO */
		u32 new_ttl:8;           /* [15:8] Default:0x0 RO */
		u32 ttl_val:1;           /* [16] Default:0x0 RC */
		u32 rsv:15;              /* [31:17] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TTL_INFO_DWLEN];
} __packed;

#define NBL_DPED_LEN_INFO_VLD_ADDR  (0x75c974)
#define NBL_DPED_LEN_INFO_VLD_DEPTH (1)
#define NBL_DPED_LEN_INFO_VLD_WIDTH (32)
#define NBL_DPED_LEN_INFO_VLD_DWLEN (1)
union dped_len_info_vld_u {
	struct dped_len_info_vld {
		u32 length0:1;           /* [0] Default:0x0 RC */
		u32 length1:1;           /* [1] Default:0x0 RC */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_LEN_INFO_VLD_DWLEN];
} __packed;

#define NBL_DPED_LEN0_INFO_ADDR  (0x75c978)
#define NBL_DPED_LEN0_INFO_DEPTH (1)
#define NBL_DPED_LEN0_INFO_WIDTH (32)
#define NBL_DPED_LEN0_INFO_DWLEN (1)
union dped_len0_info_u {
	struct dped_len0_info {
		u32 old_len:16;          /* [15:0] Default:0x0 RO */
		u32 new_len:16;          /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_LEN0_INFO_DWLEN];
} __packed;

#define NBL_DPED_LEN1_INFO_ADDR  (0x75c97c)
#define NBL_DPED_LEN1_INFO_DEPTH (1)
#define NBL_DPED_LEN1_INFO_WIDTH (32)
#define NBL_DPED_LEN1_INFO_DWLEN (1)
union dped_len1_info_u {
	struct dped_len1_info {
		u32 old_len:16;          /* [15:0] Default:0x0 RO */
		u32 new_len:16;          /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_LEN1_INFO_DWLEN];
} __packed;

#define NBL_DPED_EDIT_ATNUM_INFO_ADDR  (0x75c980)
#define NBL_DPED_EDIT_ATNUM_INFO_DEPTH (1)
#define NBL_DPED_EDIT_ATNUM_INFO_WIDTH (32)
#define NBL_DPED_EDIT_ATNUM_INFO_DWLEN (1)
union dped_edit_atnum_info_u {
	struct dped_edit_atnum_info {
		u32 replace:4;           /* [3:0] Default:0x0 RO */
		u32 del:4;               /* [7:4] Default:0x0 RO */
		u32 add:4;               /* [11:8] Default:0x0 RO */
		u32 ttl:4;               /* [15:12] Default:0x0 RO */
		u32 dscp:4;              /* [19:16] Default:0x0 RO */
		u32 tnl:4;               /* [23:20] Default:0x0 RO */
		u32 sport:4;             /* [27:24] Default:0x0 RO */
		u32 rsv:4;               /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_EDIT_ATNUM_INFO_DWLEN];
} __packed;

#define NBL_DPED_EDIT_NO_AT_INFO_ADDR  (0x75c984)
#define NBL_DPED_EDIT_NO_AT_INFO_DEPTH (1)
#define NBL_DPED_EDIT_NO_AT_INFO_WIDTH (32)
#define NBL_DPED_EDIT_NO_AT_INFO_DWLEN (1)
union dped_edit_no_at_info_u {
	struct dped_edit_no_at_info {
		u32 l3_len:1;            /* [0] Default:0x0 RC */
		u32 l4_len:1;            /* [1] Default:0x0 RC */
		u32 l3_ck:1;             /* [2] Default:0x0 RC */
		u32 l4_ck:1;             /* [3] Default:0x0 RC */
		u32 sctp_ck:1;           /* [4] Default:0x0 RC */
		u32 padding:1;           /* [5] Default:0x0 RC */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_EDIT_NO_AT_INFO_DWLEN];
} __packed;

#define NBL_DPED_HW_EDT_PROF_ADDR  (0x75d000)
#define NBL_DPED_HW_EDT_PROF_DEPTH (32)
#define NBL_DPED_HW_EDT_PROF_WIDTH (32)
#define NBL_DPED_HW_EDT_PROF_DWLEN (1)
union dped_hw_edt_prof_u {
	struct dped_hw_edt_prof {
		u32 l4_len:2;            /* [1:0] Default:0x2 RW */
		u32 l3_len:2;            /* [3:2] Default:0x2 RW */
		u32 l4_ck:3;             /* [6:4] Default:0x7 RW */
		u32 l3_ck:1;             /* [7:7] Default:0x0 RW */
		u32 l4_ck_zero_free:1;   /* [8:8] Default:0x1 RW */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_HW_EDT_PROF_DWLEN];
} __packed;
#define NBL_DPED_HW_EDT_PROF_REG(r) (NBL_DPED_HW_EDT_PROF_ADDR + \
		(NBL_DPED_HW_EDT_PROF_DWLEN * 4) * (r))

#define NBL_DPED_OUT_MASK_ADDR  (0x75e000)
#define NBL_DPED_OUT_MASK_DEPTH (24)
#define NBL_DPED_OUT_MASK_WIDTH (64)
#define NBL_DPED_OUT_MASK_DWLEN (2)
union dped_out_mask_u {
	struct dped_out_mask {
		u32 flag:32;             /* [31:0] Default:0x0 RW */
		u32 fwd:30;              /* [61:32] Default:0x0 RW */
		u32 rsv:2;               /* [63:62] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_OUT_MASK_DWLEN];
} __packed;
#define NBL_DPED_OUT_MASK_REG(r) (NBL_DPED_OUT_MASK_ADDR + \
		(NBL_DPED_OUT_MASK_DWLEN * 4) * (r))

#define NBL_DPED_TAB_EDIT_CMD_ADDR  (0x75f000)
#define NBL_DPED_TAB_EDIT_CMD_DEPTH (32)
#define NBL_DPED_TAB_EDIT_CMD_WIDTH (32)
#define NBL_DPED_TAB_EDIT_CMD_DWLEN (1)
union dped_tab_edit_cmd_u {
	struct dped_tab_edit_cmd {
		u32 in_offset:8;         /* [7:0] Default:0x0 RW */
		u32 phid:2;              /* [9:8] Default:0x0 RW */
		u32 len:7;               /* [16:10] Default:0x0 RW */
		u32 mode:4;              /* [20:17] Default:0xf RW */
		u32 l4_ck_ofld_upt:1;    /* [21] Default:0x1 RW */
		u32 l3_ck_ofld_upt:1;    /* [22] Default:0x1 RW */
		u32 rsv:9;               /* [31:23] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TAB_EDIT_CMD_DWLEN];
} __packed;
#define NBL_DPED_TAB_EDIT_CMD_REG(r) (NBL_DPED_TAB_EDIT_CMD_ADDR + \
		(NBL_DPED_TAB_EDIT_CMD_DWLEN * 4) * (r))

#define NBL_DPED_TAB_MIR_ADDR  (0x760000)
#define NBL_DPED_TAB_MIR_DEPTH (8)
#define NBL_DPED_TAB_MIR_WIDTH (1024)
#define NBL_DPED_TAB_MIR_DWLEN (32)
union dped_tab_mir_u {
	struct dped_tab_mir {
		u32 cfg_mir_data:16;     /* [719:0] Default:0x0 RW */
		u32 cfg_mir_data_arr[22]; /* [719:0] Default:0x0 RW */
		u32 cfg_mir_info_l:32;   /* [755:720] Default:0x0 RW */
		u32 cfg_mir_info_h:4;    /* [755:720] Default:0x0 RW */
		u32 rsv:12;              /* [1023:756] Default:0x0 RO */
		u32 rsv_arr[8];          /* [1023:756] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TAB_MIR_DWLEN];
} __packed;
#define NBL_DPED_TAB_MIR_REG(r) (NBL_DPED_TAB_MIR_ADDR + \
		(NBL_DPED_TAB_MIR_DWLEN * 4) * (r))

#define NBL_DPED_TAB_VSI_TYPE_ADDR  (0x761000)
#define NBL_DPED_TAB_VSI_TYPE_DEPTH (1031)
#define NBL_DPED_TAB_VSI_TYPE_WIDTH (32)
#define NBL_DPED_TAB_VSI_TYPE_DWLEN (1)
union dped_tab_vsi_type_u {
	struct dped_tab_vsi_type {
		u32 sel:4;               /* [3:0] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TAB_VSI_TYPE_DWLEN];
} __packed;
#define NBL_DPED_TAB_VSI_TYPE_REG(r) (NBL_DPED_TAB_VSI_TYPE_ADDR + \
		(NBL_DPED_TAB_VSI_TYPE_DWLEN * 4) * (r))

#define NBL_DPED_TAB_REPLACE_ADDR  (0x763000)
#define NBL_DPED_TAB_REPLACE_DEPTH (2048)
#define NBL_DPED_TAB_REPLACE_WIDTH (64)
#define NBL_DPED_TAB_REPLACE_DWLEN (2)
union dped_tab_replace_u {
	struct dped_tab_replace {
		u32 vau_arr[2];          /* [63:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPED_TAB_REPLACE_DWLEN];
} __packed;
#define NBL_DPED_TAB_REPLACE_REG(r) (NBL_DPED_TAB_REPLACE_ADDR + \
		(NBL_DPED_TAB_REPLACE_DWLEN * 4) * (r))

#define NBL_DPED_TAB_TNL_ADDR  (0x7dc000)
#define NBL_DPED_TAB_TNL_DEPTH (4096)
#define NBL_DPED_TAB_TNL_WIDTH (1024)
#define NBL_DPED_TAB_TNL_DWLEN (32)
union dped_tab_tnl_u {
	struct dped_tab_tnl {
		u32 cfg_tnl_data:16;     /* [719:0] Default:0x0 RW */
		u32 cfg_tnl_data_arr[22]; /* [719:0] Default:0x0 RW */
		u32 cfg_tnl_info:8;      /* [791:720] Default:0x0 RW */
		u32 cfg_tnl_info_arr[2]; /* [791:720] Default:0x0 RW */
		u32 rsv_l:32;            /* [1023:792] Default:0x0 RO */
		u32 rsv_h:8;             /* [1023:792] Default:0x0 RO */
		u32 rsv_arr[6];          /* [1023:792] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPED_TAB_TNL_DWLEN];
} __packed;
#define NBL_DPED_TAB_TNL_REG(r) (NBL_DPED_TAB_TNL_ADDR + \
		(NBL_DPED_TAB_TNL_DWLEN * 4) * (r))

#endif
