/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_UPED_H
#define NBL_UPED_H 1

#include <linux/types.h>

#define NBL_UPED_BASE (0x0015C000)

#define NBL_UPED_INT_STATUS_ADDR  (0x15c000)
#define NBL_UPED_INT_STATUS_DEPTH (1)
#define NBL_UPED_INT_STATUS_WIDTH (32)
#define NBL_UPED_INT_STATUS_DWLEN (1)
union uped_int_status_u {
	struct uped_int_status {
		u32 pkt_length_err:1;    /* [0] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fsm_err:1;           /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 input_err:1;         /* [5] Default:0x0 RWC */
		u32 cfg_err:1;           /* [6] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [7] Default:0x0 RWC */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 RWC */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 RWC */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 RWC */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x0 RWC */
		u32 meta_value_err:1;    /* [12] Default:0x0 RWC */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 RWC */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 RWC */
		u32 edit_pos_err:1;      /* [15] Default:0x0 RWC */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 RWC */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 RWC */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INT_STATUS_DWLEN];
} __packed;

#define NBL_UPED_INT_MASK_ADDR  (0x15c004)
#define NBL_UPED_INT_MASK_DEPTH (1)
#define NBL_UPED_INT_MASK_WIDTH (32)
#define NBL_UPED_INT_MASK_DWLEN (1)
union uped_int_mask_u {
	struct uped_int_mask {
		u32 pkt_length_err:1;    /* [0] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RW */
		u32 fsm_err:1;           /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 input_err:1;         /* [5] Default:0x0 RW */
		u32 cfg_err:1;           /* [6] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [7] Default:0x0 RW */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 RW */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 RW */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 RW */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x1 RW */
		u32 meta_value_err:1;    /* [12] Default:0x0 RW */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 RW */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 RW */
		u32 edit_pos_err:1;      /* [15] Default:0x0 RW */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 RW */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 RW */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INT_MASK_DWLEN];
} __packed;

#define NBL_UPED_INT_SET_ADDR  (0x15c008)
#define NBL_UPED_INT_SET_DEPTH (1)
#define NBL_UPED_INT_SET_WIDTH (32)
#define NBL_UPED_INT_SET_DWLEN (1)
union uped_int_set_u {
	struct uped_int_set {
		u32 pkt_length_err:1;    /* [0] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 WO */
		u32 fsm_err:1;           /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 input_err:1;         /* [5] Default:0x0 WO */
		u32 cfg_err:1;           /* [6] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [7] Default:0x0 WO */
		u32 inmeta_ucor_err:1;   /* [8] Default:0x0 WO */
		u32 meta_ucor_err:1;     /* [9] Default:0x0 WO */
		u32 meta_cor_ecc_err:1;  /* [10] Default:0x0 WO */
		u32 fwd_atid_nomat_err:1; /* [11] Default:0x0 WO */
		u32 meta_value_err:1;    /* [12] Default:0x0 WO */
		u32 edit_atnum_err:1;    /* [13] Default:0x0 WO */
		u32 header_oft_ovf:1;    /* [14] Default:0x0 WO */
		u32 edit_pos_err:1;      /* [15] Default:0x0 WO */
		u32 da_oft_len_ovf:1;    /* [16] Default:0x0 WO */
		u32 lxoffset_ovf:1;      /* [17] Default:0x0 WO */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INT_SET_DWLEN];
} __packed;

#define NBL_UPED_INIT_DONE_ADDR  (0x15c00c)
#define NBL_UPED_INIT_DONE_DEPTH (1)
#define NBL_UPED_INIT_DONE_WIDTH (32)
#define NBL_UPED_INIT_DONE_DWLEN (1)
union uped_init_done_u {
	struct uped_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INIT_DONE_DWLEN];
} __packed;

#define NBL_UPED_PKT_LENGTH_ERR_INFO_ADDR  (0x15c020)
#define NBL_UPED_PKT_LENGTH_ERR_INFO_DEPTH (1)
#define NBL_UPED_PKT_LENGTH_ERR_INFO_WIDTH (32)
#define NBL_UPED_PKT_LENGTH_ERR_INFO_DWLEN (1)
union uped_pkt_length_err_info_u {
	struct uped_pkt_length_err_info {
		u32 ptr_eop:1;           /* [0] Default:0x0 RC */
		u32 pkt_eop:1;           /* [1] Default:0x0 RC */
		u32 pkt_mod:1;           /* [2] Default:0x0 RC */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_PKT_LENGTH_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_CIF_ERR_INFO_ADDR  (0x15c040)
#define NBL_UPED_CIF_ERR_INFO_DEPTH (1)
#define NBL_UPED_CIF_ERR_INFO_WIDTH (32)
#define NBL_UPED_CIF_ERR_INFO_DWLEN (1)
union uped_cif_err_info_u {
	struct uped_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_INPUT_ERR_INFO_ADDR  (0x15c048)
#define NBL_UPED_INPUT_ERR_INFO_DEPTH (1)
#define NBL_UPED_INPUT_ERR_INFO_WIDTH (32)
#define NBL_UPED_INPUT_ERR_INFO_DWLEN (1)
union uped_input_err_info_u {
	struct uped_input_err_info {
		u32 eoc_miss:1;          /* [0] Default:0x0 RC */
		u32 soc_miss:1;          /* [1] Default:0x0 RC */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INPUT_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_CFG_ERR_INFO_ADDR  (0x15c050)
#define NBL_UPED_CFG_ERR_INFO_DEPTH (1)
#define NBL_UPED_CFG_ERR_INFO_WIDTH (32)
#define NBL_UPED_CFG_ERR_INFO_DWLEN (1)
union uped_cfg_err_info_u {
	struct uped_cfg_err_info {
		u32 length:1;            /* [0] Default:0x0 RC */
		u32 rd_conflict:1;       /* [1] Default:0x0 RC */
		u32 rd_addr:8;           /* [9:2] Default:0x0 RC */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_FWD_ATID_NOMAT_ERR_INFO_ADDR  (0x15c06c)
#define NBL_UPED_FWD_ATID_NOMAT_ERR_INFO_DEPTH (1)
#define NBL_UPED_FWD_ATID_NOMAT_ERR_INFO_WIDTH (32)
#define NBL_UPED_FWD_ATID_NOMAT_ERR_INFO_DWLEN (1)
union uped_fwd_atid_nomat_err_info_u {
	struct uped_fwd_atid_nomat_err_info {
		u32 dport:1;             /* [0] Default:0x0 RC */
		u32 dqueue:1;            /* [1] Default:0x0 RC */
		u32 hash0:1;             /* [2] Default:0x0 RC */
		u32 hash1:1;             /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_ATID_NOMAT_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_META_VALUE_ERR_INFO_ADDR  (0x15c070)
#define NBL_UPED_META_VALUE_ERR_INFO_DEPTH (1)
#define NBL_UPED_META_VALUE_ERR_INFO_WIDTH (32)
#define NBL_UPED_META_VALUE_ERR_INFO_DWLEN (1)
union uped_meta_value_err_info_u {
	struct uped_meta_value_err_info {
		u32 sport:1;             /* [0] Default:0x0 RC */
		u32 dport:1;             /* [1] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [2] Default:0x0 RC */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_META_VALUE_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_EDIT_ATNUM_ERR_INFO_ADDR  (0x15c078)
#define NBL_UPED_EDIT_ATNUM_ERR_INFO_DEPTH (1)
#define NBL_UPED_EDIT_ATNUM_ERR_INFO_WIDTH (32)
#define NBL_UPED_EDIT_ATNUM_ERR_INFO_DWLEN (1)
union uped_edit_atnum_err_info_u {
	struct uped_edit_atnum_err_info {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 del_add:1;           /* [1] Default:0x0 RC */
		u32 ttl:1;               /* [2] Default:0x0 RC */
		u32 dscp:1;              /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_EDIT_ATNUM_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPED_HEADER_OFT_OVF_ADDR  (0x15c080)
#define NBL_UPED_HEADER_OFT_OVF_DEPTH (1)
#define NBL_UPED_HEADER_OFT_OVF_WIDTH (32)
#define NBL_UPED_HEADER_OFT_OVF_DWLEN (1)
union uped_header_oft_ovf_u {
	struct uped_header_oft_ovf {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 rsv2:7;              /* [7:1] Default:0x0 RO */
		u32 add_del:6;           /* [13:8] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [14] Default:0x0 RC */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 ttl:1;               /* [16] Default:0x0 RC */
		u32 sctp:1;              /* [17] Default:0x0 RC */
		u32 ck_len0:1;           /* [18] Default:0x0 RC */
		u32 ck_len1:1;           /* [19] Default:0x0 RC */
		u32 len0:1;              /* [20] Default:0x0 RC */
		u32 len1:1;              /* [21] Default:0x0 RC */
		u32 ck0:1;               /* [22] Default:0x0 RC */
		u32 ck1:1;               /* [23] Default:0x0 RC */
		u32 ck_start0_0:1;       /* [24] Default:0x0 RC */
		u32 ck_start0_1:1;       /* [25] Default:0x0 RC */
		u32 ck_start1_0:1;       /* [26] Default:0x0 RC */
		u32 ck_start1_1:1;       /* [27] Default:0x0 RC */
		u32 head:1;              /* [28] Default:0x0 RC */
		u32 head_out:1;          /* [29] Default:0x0 RC */
		u32 l4_head:1;           /* [30] Default:0x0 RC */
		u32 rsv:1;               /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HEADER_OFT_OVF_DWLEN];
} __packed;

#define NBL_UPED_EDIT_POS_ERR_ADDR  (0x15c088)
#define NBL_UPED_EDIT_POS_ERR_DEPTH (1)
#define NBL_UPED_EDIT_POS_ERR_WIDTH (32)
#define NBL_UPED_EDIT_POS_ERR_DWLEN (1)
union uped_edit_pos_err_u {
	struct uped_edit_pos_err {
		u32 replace:1;           /* [0] Default:0x0 RC */
		u32 cross_level:6;       /* [6:1] Default:0x0 RC */
		u32 rsv2:1;              /* [7] Default:0x0 RO */
		u32 add_del:6;           /* [13:8] Default:0x0 RC */
		u32 dscp_ecn:1;          /* [14] Default:0x0 RC */
		u32 rsv1:1;              /* [15] Default:0x0 RO */
		u32 ttl:1;               /* [16] Default:0x0 RC */
		u32 sctp:1;              /* [17] Default:0x0 RC */
		u32 ck_len0:1;           /* [18] Default:0x0 RC */
		u32 ck_len1:1;           /* [19] Default:0x0 RC */
		u32 len0:1;              /* [20] Default:0x0 RC */
		u32 len1:1;              /* [21] Default:0x0 RC */
		u32 ck0:1;               /* [22] Default:0x0 RC */
		u32 ck1:1;               /* [23] Default:0x0 RC */
		u32 ck_start0_0:1;       /* [24] Default:0x0 RC */
		u32 ck_start0_1:1;       /* [25] Default:0x0 RC */
		u32 ck_start1_0:1;       /* [26] Default:0x0 RC */
		u32 ck_start1_1:1;       /* [27] Default:0x0 RC */
		u32 bth_header:1;        /* [28] Default:0x0 RC */
		u32 rsv:3;               /* [31:29] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_EDIT_POS_ERR_DWLEN];
} __packed;

#define NBL_UPED_DA_OFT_LEN_OVF_ADDR  (0x15c090)
#define NBL_UPED_DA_OFT_LEN_OVF_DEPTH (1)
#define NBL_UPED_DA_OFT_LEN_OVF_WIDTH (32)
#define NBL_UPED_DA_OFT_LEN_OVF_DWLEN (1)
union uped_da_oft_len_ovf_u {
	struct uped_da_oft_len_ovf {
		u32 at0:5;               /* [4:0] Default:0x0 RC */
		u32 at1:5;               /* [9:5] Default:0x0 RC */
		u32 at2:5;               /* [14:10] Default:0x0 RC */
		u32 at3:5;               /* [19:15] Default:0x0 RC */
		u32 at4:5;               /* [24:20] Default:0x0 RC */
		u32 at5:5;               /* [29:25] Default:0x0 RC */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_DA_OFT_LEN_OVF_DWLEN];
} __packed;

#define NBL_UPED_LXOFFSET_OVF_ADDR  (0x15c098)
#define NBL_UPED_LXOFFSET_OVF_DEPTH (1)
#define NBL_UPED_LXOFFSET_OVF_WIDTH (32)
#define NBL_UPED_LXOFFSET_OVF_DWLEN (1)
union uped_lxoffset_ovf_u {
	struct uped_lxoffset_ovf {
		u32 l2:1;                /* [0] Default:0x0 RC */
		u32 l3:1;                /* [1] Default:0x0 RC */
		u32 l4:1;                /* [2] Default:0x0 RC */
		u32 pld:1;               /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_LXOFFSET_OVF_DWLEN];
} __packed;

#define NBL_UPED_CAR_CTRL_ADDR  (0x15c100)
#define NBL_UPED_CAR_CTRL_DEPTH (1)
#define NBL_UPED_CAR_CTRL_WIDTH (32)
#define NBL_UPED_CAR_CTRL_DWLEN (1)
union uped_car_ctrl_u {
	struct uped_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_CAR_CTRL_DWLEN];
} __packed;

#define NBL_UPED_INIT_START_ADDR  (0x15c10c)
#define NBL_UPED_INIT_START_DEPTH (1)
#define NBL_UPED_INIT_START_WIDTH (32)
#define NBL_UPED_INIT_START_DWLEN (1)
union uped_init_start_u {
	struct uped_init_start {
		u32 start:1;             /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INIT_START_DWLEN];
} __packed;

#define NBL_UPED_TIMEOUT_CFG_ADDR  (0x15c110)
#define NBL_UPED_TIMEOUT_CFG_DEPTH (1)
#define NBL_UPED_TIMEOUT_CFG_WIDTH (32)
#define NBL_UPED_TIMEOUT_CFG_DWLEN (1)
union uped_timeout_cfg_u {
	struct uped_timeout_cfg {
		u32 fsm_max_num:16;      /* [15:00] Default:0xfff RW */
		u32 tab:8;               /* [23:16] Default:0x40 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TIMEOUT_CFG_DWLEN];
} __packed;

#define NBL_UPED_PKT_DROP_EN_ADDR  (0x15c170)
#define NBL_UPED_PKT_DROP_EN_DEPTH (1)
#define NBL_UPED_PKT_DROP_EN_WIDTH (32)
#define NBL_UPED_PKT_DROP_EN_DWLEN (1)
union uped_pkt_drop_en_u {
	struct uped_pkt_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_PKT_DROP_EN_DWLEN];
} __packed;

#define NBL_UPED_PKT_HERR_DROP_EN_ADDR  (0x15c174)
#define NBL_UPED_PKT_HERR_DROP_EN_DEPTH (1)
#define NBL_UPED_PKT_HERR_DROP_EN_WIDTH (32)
#define NBL_UPED_PKT_HERR_DROP_EN_DWLEN (1)
union uped_pkt_herr_drop_en_u {
	struct uped_pkt_herr_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_PKT_HERR_DROP_EN_DWLEN];
} __packed;

#define NBL_UPED_PKT_PARITY_DROP_EN_ADDR  (0x15c178)
#define NBL_UPED_PKT_PARITY_DROP_EN_DEPTH (1)
#define NBL_UPED_PKT_PARITY_DROP_EN_WIDTH (32)
#define NBL_UPED_PKT_PARITY_DROP_EN_DWLEN (1)
union uped_pkt_parity_drop_en_u {
	struct uped_pkt_parity_drop_en {
		u32 en0:1;               /* [0] Default:0x1 RW */
		u32 en1:1;               /* [1] Default:0x1 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_PKT_PARITY_DROP_EN_DWLEN];
} __packed;

#define NBL_UPED_TTL_DROP_EN_ADDR  (0x15c17c)
#define NBL_UPED_TTL_DROP_EN_DEPTH (1)
#define NBL_UPED_TTL_DROP_EN_WIDTH (32)
#define NBL_UPED_TTL_DROP_EN_DWLEN (1)
union uped_ttl_drop_en_u {
	struct uped_ttl_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TTL_DROP_EN_DWLEN];
} __packed;

#define NBL_UPED_DQUEUE_DROP_EN_ADDR  (0x15c180)
#define NBL_UPED_DQUEUE_DROP_EN_DEPTH (1)
#define NBL_UPED_DQUEUE_DROP_EN_WIDTH (32)
#define NBL_UPED_DQUEUE_DROP_EN_DWLEN (1)
union uped_dqueue_drop_en_u {
	struct uped_dqueue_drop_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_DQUEUE_DROP_EN_DWLEN];
} __packed;

#define NBL_UPED_INTF_ECC_ERR_EN_ADDR  (0x15c184)
#define NBL_UPED_INTF_ECC_ERR_EN_DEPTH (1)
#define NBL_UPED_INTF_ECC_ERR_EN_WIDTH (32)
#define NBL_UPED_INTF_ECC_ERR_EN_DWLEN (1)
union uped_intf_ecc_err_en_u {
	struct uped_intf_ecc_err_en {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INTF_ECC_ERR_EN_DWLEN];
} __packed;

#define NBL_UPED_TTL_ERROR_CODE_ADDR  (0x15c188)
#define NBL_UPED_TTL_ERROR_CODE_DEPTH (1)
#define NBL_UPED_TTL_ERROR_CODE_WIDTH (32)
#define NBL_UPED_TTL_ERROR_CODE_DWLEN (1)
union uped_ttl_error_code_u {
	struct uped_ttl_error_code {
		u32 en:1;                /* [0] Default:0x1 RW */
		u32 rsv1:7;              /* [7:1] Default:0x0 RO */
		u32 id:4;                /* [11:8] Default:0x6 RW */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TTL_ERROR_CODE_DWLEN];
} __packed;

#define NBL_UPED_HIGH_PRI_PKT_EN_ADDR  (0x15c190)
#define NBL_UPED_HIGH_PRI_PKT_EN_DEPTH (1)
#define NBL_UPED_HIGH_PRI_PKT_EN_WIDTH (32)
#define NBL_UPED_HIGH_PRI_PKT_EN_DWLEN (1)
union uped_high_pri_pkt_en_u {
	struct uped_high_pri_pkt_en {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HIGH_PRI_PKT_EN_DWLEN];
} __packed;

#define NBL_UPED_HW_EDIT_FLAG_SEL0_ADDR  (0x15c204)
#define NBL_UPED_HW_EDIT_FLAG_SEL0_DEPTH (1)
#define NBL_UPED_HW_EDIT_FLAG_SEL0_WIDTH (32)
#define NBL_UPED_HW_EDIT_FLAG_SEL0_DWLEN (1)
union uped_hw_edit_flag_sel0_u {
	struct uped_hw_edit_flag_sel0 {
		u32 oft:5;               /* [4:0] Default:0x1 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDIT_FLAG_SEL0_DWLEN];
} __packed;

#define NBL_UPED_HW_EDIT_FLAG_SEL1_ADDR  (0x15c208)
#define NBL_UPED_HW_EDIT_FLAG_SEL1_DEPTH (1)
#define NBL_UPED_HW_EDIT_FLAG_SEL1_WIDTH (32)
#define NBL_UPED_HW_EDIT_FLAG_SEL1_DWLEN (1)
union uped_hw_edit_flag_sel1_u {
	struct uped_hw_edit_flag_sel1 {
		u32 oft:5;               /* [4:0] Default:0x2 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDIT_FLAG_SEL1_DWLEN];
} __packed;

#define NBL_UPED_HW_EDIT_FLAG_SEL2_ADDR  (0x15c20c)
#define NBL_UPED_HW_EDIT_FLAG_SEL2_DEPTH (1)
#define NBL_UPED_HW_EDIT_FLAG_SEL2_WIDTH (32)
#define NBL_UPED_HW_EDIT_FLAG_SEL2_DWLEN (1)
union uped_hw_edit_flag_sel2_u {
	struct uped_hw_edit_flag_sel2 {
		u32 oft:5;               /* [4:0] Default:0x3 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDIT_FLAG_SEL2_DWLEN];
} __packed;

#define NBL_UPED_HW_EDIT_FLAG_SEL3_ADDR  (0x15c210)
#define NBL_UPED_HW_EDIT_FLAG_SEL3_DEPTH (1)
#define NBL_UPED_HW_EDIT_FLAG_SEL3_WIDTH (32)
#define NBL_UPED_HW_EDIT_FLAG_SEL3_DWLEN (1)
union uped_hw_edit_flag_sel3_u {
	struct uped_hw_edit_flag_sel3 {
		u32 oft:5;               /* [4:0] Default:0x4 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDIT_FLAG_SEL3_DWLEN];
} __packed;

#define NBL_UPED_HW_EDIT_FLAG_SEL4_ADDR  (0x15c214)
#define NBL_UPED_HW_EDIT_FLAG_SEL4_DEPTH (1)
#define NBL_UPED_HW_EDIT_FLAG_SEL4_WIDTH (32)
#define NBL_UPED_HW_EDIT_FLAG_SEL4_DWLEN (1)
union uped_hw_edit_flag_sel4_u {
	struct uped_hw_edit_flag_sel4 {
		u32 oft:5;               /* [4:0] Default:0xe RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDIT_FLAG_SEL4_DWLEN];
} __packed;

#define NBL_UPED_FWD_DPORT_ADDR  (0x15c230)
#define NBL_UPED_FWD_DPORT_DEPTH (1)
#define NBL_UPED_FWD_DPORT_WIDTH (32)
#define NBL_UPED_FWD_DPORT_DWLEN (1)
union uped_fwd_dport_u {
	struct uped_fwd_dport {
		u32 id:6;                /* [5:0] Default:0x9 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_DPORT_DWLEN];
} __packed;

#define NBL_UPED_FWD_DQUEUE_ADDR  (0x15c234)
#define NBL_UPED_FWD_DQUEUE_DEPTH (1)
#define NBL_UPED_FWD_DQUEUE_WIDTH (32)
#define NBL_UPED_FWD_DQUEUE_DWLEN (1)
union uped_fwd_dqueue_u {
	struct uped_fwd_dqueue {
		u32 id:6;                /* [5:0] Default:0xa RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_DQUEUE_DWLEN];
} __packed;

#define NBL_UPED_FWD_MIRID_ADDR  (0x15c238)
#define NBL_UPED_FWD_MIRID_DEPTH (1)
#define NBL_UPED_FWD_MIRID_WIDTH (32)
#define NBL_UPED_FWD_MIRID_DWLEN (1)
union uped_fwd_mirid_u {
	struct uped_fwd_mirid {
		u32 id:6;                /* [5:0] Default:0x8 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_MIRID_DWLEN];
} __packed;

#define NBL_UPED_FWD_L4IDX_ADDR  (0x15c23c)
#define NBL_UPED_FWD_L4IDX_DEPTH (1)
#define NBL_UPED_FWD_L4IDX_WIDTH (32)
#define NBL_UPED_FWD_L4IDX_DWLEN (1)
union uped_fwd_l4idx_u {
	struct uped_fwd_l4idx {
		u32 id:6;                /* [5:0] Default:0x11 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_L4IDX_DWLEN];
} __packed;

#define NBL_UPED_FWD_HASH_0_ADDR  (0x15c244)
#define NBL_UPED_FWD_HASH_0_DEPTH (1)
#define NBL_UPED_FWD_HASH_0_WIDTH (32)
#define NBL_UPED_FWD_HASH_0_DWLEN (1)
union uped_fwd_hash_0_u {
	struct uped_fwd_hash_0 {
		u32 id:6;                /* [5:0] Default:0x13 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_HASH_0_DWLEN];
} __packed;

#define NBL_UPED_FWD_HASH_1_ADDR  (0x15c248)
#define NBL_UPED_FWD_HASH_1_DEPTH (1)
#define NBL_UPED_FWD_HASH_1_WIDTH (32)
#define NBL_UPED_FWD_HASH_1_DWLEN (1)
union uped_fwd_hash_1_u {
	struct uped_fwd_hash_1 {
		u32 id:6;                /* [5:0] Default:0x14 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_FWD_HASH_1_DWLEN];
} __packed;

#define NBL_UPED_L4_OFT_ADJUST_ADDR  (0x15c250)
#define NBL_UPED_L4_OFT_ADJUST_DEPTH (1)
#define NBL_UPED_L4_OFT_ADJUST_WIDTH (32)
#define NBL_UPED_L4_OFT_ADJUST_DWLEN (1)
union uped_l4_oft_adjust_u {
	struct uped_l4_oft_adjust {
		u32 vau:8;               /* [7:0] Default:0x0 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_L4_OFT_ADJUST_DWLEN];
} __packed;

#define NBL_UPED_PLD_OFT_ADJUST_ADDR  (0x15c254)
#define NBL_UPED_PLD_OFT_ADJUST_DEPTH (1)
#define NBL_UPED_PLD_OFT_ADJUST_WIDTH (32)
#define NBL_UPED_PLD_OFT_ADJUST_DWLEN (1)
union uped_pld_oft_adjust_u {
	struct uped_pld_oft_adjust {
		u32 vau:8;               /* [7:0] Default:0x0 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_PLD_OFT_ADJUST_DWLEN];
} __packed;

#define NBL_UPED_VLAN_TYPE0_ADDR  (0x15c260)
#define NBL_UPED_VLAN_TYPE0_DEPTH (1)
#define NBL_UPED_VLAN_TYPE0_WIDTH (32)
#define NBL_UPED_VLAN_TYPE0_DWLEN (1)
union uped_vlan_type0_u {
	struct uped_vlan_type0 {
		u32 vau:16;              /* [15:0] Default:0x8100 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_VLAN_TYPE0_DWLEN];
} __packed;

#define NBL_UPED_VLAN_TYPE1_ADDR  (0x15c264)
#define NBL_UPED_VLAN_TYPE1_DEPTH (1)
#define NBL_UPED_VLAN_TYPE1_WIDTH (32)
#define NBL_UPED_VLAN_TYPE1_DWLEN (1)
union uped_vlan_type1_u {
	struct uped_vlan_type1 {
		u32 vau:16;              /* [15:0] Default:0x88A8 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_VLAN_TYPE1_DWLEN];
} __packed;

#define NBL_UPED_VLAN_TYPE2_ADDR  (0x15c268)
#define NBL_UPED_VLAN_TYPE2_DEPTH (1)
#define NBL_UPED_VLAN_TYPE2_WIDTH (32)
#define NBL_UPED_VLAN_TYPE2_DWLEN (1)
union uped_vlan_type2_u {
	struct uped_vlan_type2 {
		u32 vau:16;              /* [15:0] Default:0x9100 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_VLAN_TYPE2_DWLEN];
} __packed;

#define NBL_UPED_VLAN_TYPE3_ADDR  (0x15c26c)
#define NBL_UPED_VLAN_TYPE3_DEPTH (1)
#define NBL_UPED_VLAN_TYPE3_WIDTH (32)
#define NBL_UPED_VLAN_TYPE3_DWLEN (1)
union uped_vlan_type3_u {
	struct uped_vlan_type3 {
		u32 vau:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_VLAN_TYPE3_DWLEN];
} __packed;

#define NBL_UPED_L3_LEN_MDY_CMD_0_ADDR  (0x15c300)
#define NBL_UPED_L3_LEN_MDY_CMD_0_DEPTH (1)
#define NBL_UPED_L3_LEN_MDY_CMD_0_WIDTH (32)
#define NBL_UPED_L3_LEN_MDY_CMD_0_DWLEN (1)
union uped_l3_len_mdy_cmd_0_u {
	struct uped_l3_len_mdy_cmd_0 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0x2 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x2 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x2 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x0 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L3_LEN_MDY_CMD_0_DWLEN];
} __packed;

#define NBL_UPED_L3_LEN_MDY_CMD_1_ADDR  (0x15c304)
#define NBL_UPED_L3_LEN_MDY_CMD_1_DEPTH (1)
#define NBL_UPED_L3_LEN_MDY_CMD_1_WIDTH (32)
#define NBL_UPED_L3_LEN_MDY_CMD_1_DWLEN (1)
union uped_l3_len_mdy_cmd_1_u {
	struct uped_l3_len_mdy_cmd_1 {
		u32 value:8;             /* [7:0] Default:0x28 RW */
		u32 in_oft:7;            /* [14:8] Default:0x4 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x2 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x1 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x0 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L3_LEN_MDY_CMD_1_DWLEN];
} __packed;

#define NBL_UPED_L4_LEN_MDY_CMD_0_ADDR  (0x15c308)
#define NBL_UPED_L4_LEN_MDY_CMD_0_DEPTH (1)
#define NBL_UPED_L4_LEN_MDY_CMD_0_WIDTH (32)
#define NBL_UPED_L4_LEN_MDY_CMD_0_DWLEN (1)
union uped_l4_len_mdy_cmd_0_u {
	struct uped_l4_len_mdy_cmd_0 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0xc RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x3 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x0 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x1 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_LEN_MDY_CMD_0_DWLEN];
} __packed;

#define NBL_UPED_L4_LEN_MDY_CMD_1_ADDR  (0x15c30c)
#define NBL_UPED_L4_LEN_MDY_CMD_1_DEPTH (1)
#define NBL_UPED_L4_LEN_MDY_CMD_1_WIDTH (32)
#define NBL_UPED_L4_LEN_MDY_CMD_1_DWLEN (1)
union uped_l4_len_mdy_cmd_1_u {
	struct uped_l4_len_mdy_cmd_1 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 in_oft:7;            /* [14:8] Default:0x4 RW */
		u32 rsv3:1;              /* [15] Default:0x0 RO */
		u32 phid:2;              /* [17:16] Default:0x3 RW */
		u32 rsv2:2;              /* [19:18] Default:0x0 RO */
		u32 mode:2;              /* [21:20] Default:0x0 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 unit:1;              /* [24] Default:0x1 RW */
		u32 rsv:6;               /* [30:25] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_LEN_MDY_CMD_1_DWLEN];
} __packed;

#define NBL_UPED_L3_CK_CMD_00_ADDR  (0x15c310)
#define NBL_UPED_L3_CK_CMD_00_DEPTH (1)
#define NBL_UPED_L3_CK_CMD_00_WIDTH (32)
#define NBL_UPED_L3_CK_CMD_00_DWLEN (1)
union uped_l3_ck_cmd_00_u {
	struct uped_l3_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0xa RW */
		u32 phid:2;              /* [27:26] Default:0x2 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L3_CK_CMD_00_DWLEN];
} __packed;

#define NBL_UPED_L3_CK_CMD_01_ADDR  (0x15c314)
#define NBL_UPED_L3_CK_CMD_01_DEPTH (1)
#define NBL_UPED_L3_CK_CMD_01_WIDTH (32)
#define NBL_UPED_L3_CK_CMD_01_DWLEN (1)
union uped_l3_ck_cmd_01_u {
	struct uped_l3_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPED_L3_CK_CMD_01_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_00_ADDR  (0x15c318)
#define NBL_UPED_L4_CK_CMD_00_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_00_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_00_DWLEN (1)
union uped_l4_ck_cmd_00_u {
	struct uped_l4_ck_cmd_00 {
		u32 value:8;             /* [7:0] Default:0x6 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x10 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_00_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_01_ADDR  (0x15c31c)
#define NBL_UPED_L4_CK_CMD_01_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_01_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_01_DWLEN (1)
union uped_l4_ck_cmd_01_u {
	struct uped_l4_ck_cmd_01 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_01_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_10_ADDR  (0x15c320)
#define NBL_UPED_L4_CK_CMD_10_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_10_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_10_DWLEN (1)
union uped_l4_ck_cmd_10_u {
	struct uped_l4_ck_cmd_10 {
		u32 value:8;             /* [7:0] Default:0x11 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_10_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_11_ADDR  (0x15c324)
#define NBL_UPED_L4_CK_CMD_11_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_11_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_11_DWLEN (1)
union uped_l4_ck_cmd_11_u {
	struct uped_l4_ck_cmd_11 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_11_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_20_ADDR  (0x15c328)
#define NBL_UPED_L4_CK_CMD_20_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_20_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_20_DWLEN (1)
union uped_l4_ck_cmd_20_u {
	struct uped_l4_ck_cmd_20 {
		u32 value:8;             /* [7:0] Default:0x2e RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x10 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_20_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_21_ADDR  (0x15c32c)
#define NBL_UPED_L4_CK_CMD_21_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_21_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_21_DWLEN (1)
union uped_l4_ck_cmd_21_u {
	struct uped_l4_ck_cmd_21 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_21_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_30_ADDR  (0x15c330)
#define NBL_UPED_L4_CK_CMD_30_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_30_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_30_DWLEN (1)
union uped_l4_ck_cmd_30_u {
	struct uped_l4_ck_cmd_30 {
		u32 value:8;             /* [7:0] Default:0x39 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x6 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x1 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_30_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_31_ADDR  (0x15c334)
#define NBL_UPED_L4_CK_CMD_31_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_31_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_31_DWLEN (1)
union uped_l4_ck_cmd_31_u {
	struct uped_l4_ck_cmd_31 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_31_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_40_ADDR  (0x15c338)
#define NBL_UPED_L4_CK_CMD_40_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_40_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_40_DWLEN (1)
union uped_l4_ck_cmd_40_u {
	struct uped_l4_ck_cmd_40 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x0 RW */
		u32 len_phid:2;          /* [16:15] Default:0x0 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x0 RW */
		u32 in_oft:7;            /* [25:19] Default:0x8 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x1 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_40_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_41_ADDR  (0x15c33c)
#define NBL_UPED_L4_CK_CMD_41_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_41_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_41_DWLEN (1)
union uped_l4_ck_cmd_41_u {
	struct uped_l4_ck_cmd_41 {
		u32 ck_start0:6;         /* [5:0] Default:0x0 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x0 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x0 RW */
		u32 ck_vld0:1;           /* [15] Default:0x0 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x0 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_41_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_50_ADDR  (0x15c340)
#define NBL_UPED_L4_CK_CMD_50_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_50_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_50_DWLEN (1)
union uped_l4_ck_cmd_50_u {
	struct uped_l4_ck_cmd_50 {
		u32 value:8;             /* [7:0] Default:0x0 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x2 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x0 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x2 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_50_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_51_ADDR  (0x15c344)
#define NBL_UPED_L4_CK_CMD_51_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_51_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_51_DWLEN (1)
union uped_l4_ck_cmd_51_u {
	struct uped_l4_ck_cmd_51 {
		u32 ck_start0:6;         /* [5:0] Default:0xc RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x8 RW */
		u32 ck_vld0:1;           /* [15] Default:0x0 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_51_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_60_ADDR  (0x15c348)
#define NBL_UPED_L4_CK_CMD_60_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_60_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_60_DWLEN (1)
union uped_l4_ck_cmd_60_u {
	struct uped_l4_ck_cmd_60 {
		u32 value:8;             /* [7:0] Default:0x62 RW */
		u32 len_in_oft:7;        /* [14:8] Default:0x4 RW */
		u32 len_phid:2;          /* [16:15] Default:0x2 RW */
		u32 len_vld:1;           /* [17] Default:0x1 RW */
		u32 data_vld:1;          /* [18] Default:0x1 RW */
		u32 in_oft:7;            /* [25:19] Default:0x2 RW */
		u32 phid:2;              /* [27:26] Default:0x3 RW */
		u32 flag:1;              /* [28] Default:0x0 RW */
		u32 mode:1;              /* [29] Default:0x0 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_60_DWLEN];
} __packed;

#define NBL_UPED_L4_CK_CMD_61_ADDR  (0x15c34c)
#define NBL_UPED_L4_CK_CMD_61_DEPTH (1)
#define NBL_UPED_L4_CK_CMD_61_WIDTH (32)
#define NBL_UPED_L4_CK_CMD_61_DWLEN (1)
union uped_l4_ck_cmd_61_u {
	struct uped_l4_ck_cmd_61 {
		u32 ck_start0:6;         /* [5:0] Default:0x8 RW */
		u32 ck_phid0:2;          /* [7:6] Default:0x2 RW */
		u32 ck_len0:7;           /* [14:8] Default:0x20 RW */
		u32 ck_vld0:1;           /* [15] Default:0x1 RW */
		u32 ck_start1:6;         /* [21:16] Default:0x0 RW */
		u32 ck_phid1:2;          /* [23:22] Default:0x3 RW */
		u32 ck_len1:7;           /* [30:24] Default:0x0 RW */
		u32 ck_vld1:1;           /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_UPED_L4_CK_CMD_61_DWLEN];
} __packed;

#define NBL_UPED_CFG_TEST_ADDR  (0x15c600)
#define NBL_UPED_CFG_TEST_DEPTH (1)
#define NBL_UPED_CFG_TEST_WIDTH (32)
#define NBL_UPED_CFG_TEST_DWLEN (1)
union uped_cfg_test_u {
	struct uped_cfg_test {
		u32 test:32;             /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPED_CFG_TEST_DWLEN];
} __packed;

#define NBL_UPED_BP_STATE_ADDR  (0x15c608)
#define NBL_UPED_BP_STATE_DEPTH (1)
#define NBL_UPED_BP_STATE_WIDTH (32)
#define NBL_UPED_BP_STATE_DWLEN (1)
union uped_bp_state_u {
	struct uped_bp_state {
		u32 bm_rtn_tout:1;       /* [0] Default:0x0 RO */
		u32 bm_not_rdy:1;        /* [1] Default:0x0 RO */
		u32 rsv1:1;              /* [2] Default:0x0 RO */
		u32 qm_fc:1;             /* [3] Default:0x0 RO */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_BP_STATE_DWLEN];
} __packed;

#define NBL_UPED_BP_HISTORY_ADDR  (0x15c60c)
#define NBL_UPED_BP_HISTORY_DEPTH (1)
#define NBL_UPED_BP_HISTORY_WIDTH (32)
#define NBL_UPED_BP_HISTORY_DWLEN (1)
union uped_bp_history_u {
	struct uped_bp_history {
		u32 bm_rtn_tout:1;       /* [0] Default:0x0 RC */
		u32 bm_not_rdy:1;        /* [1] Default:0x0 RC */
		u32 rsv1:1;              /* [2] Default:0x0 RC */
		u32 qm_fc:1;             /* [3] Default:0x0 RC */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_BP_HISTORY_DWLEN];
} __packed;

#define NBL_UPED_MIRID_IND_ADDR  (0x15c900)
#define NBL_UPED_MIRID_IND_DEPTH (1)
#define NBL_UPED_MIRID_IND_WIDTH (32)
#define NBL_UPED_MIRID_IND_DWLEN (1)
union uped_mirid_ind_u {
	struct uped_mirid_ind {
		u32 nomat:1;             /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MIRID_IND_DWLEN];
} __packed;

#define NBL_UPED_MD_AUX_OFT_ADDR  (0x15c904)
#define NBL_UPED_MD_AUX_OFT_DEPTH (1)
#define NBL_UPED_MD_AUX_OFT_WIDTH (32)
#define NBL_UPED_MD_AUX_OFT_DWLEN (1)
union uped_md_aux_oft_u {
	struct uped_md_aux_oft {
		u32 l2_oft:8;            /* [7:0] Default:0x0 RO */
		u32 l3_oft:8;            /* [15:8] Default:0x0 RO */
		u32 l4_oft:8;            /* [23:16] Default:0x0 RO */
		u32 pld_oft:8;           /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_AUX_OFT_DWLEN];
} __packed;

#define NBL_UPED_MD_AUX_PKT_LEN_ADDR  (0x15c908)
#define NBL_UPED_MD_AUX_PKT_LEN_DEPTH (1)
#define NBL_UPED_MD_AUX_PKT_LEN_WIDTH (32)
#define NBL_UPED_MD_AUX_PKT_LEN_DWLEN (1)
union uped_md_aux_pkt_len_u {
	struct uped_md_aux_pkt_len {
		u32 len:14;              /* [13:0] Default:0x0 RO */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_AUX_PKT_LEN_DWLEN];
} __packed;

#define NBL_UPED_MD_FWD_DPORT_ADDR  (0x15c910)
#define NBL_UPED_MD_FWD_DPORT_DEPTH (1)
#define NBL_UPED_MD_FWD_DPORT_WIDTH (32)
#define NBL_UPED_MD_FWD_DPORT_DWLEN (1)
union uped_md_fwd_dport_u {
	struct uped_md_fwd_dport {
		u32 id:16;               /* [15:0] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_FWD_DPORT_DWLEN];
} __packed;

#define NBL_UPED_MD_AUX_PLD_CKSUM_ADDR  (0x15c914)
#define NBL_UPED_MD_AUX_PLD_CKSUM_DEPTH (1)
#define NBL_UPED_MD_AUX_PLD_CKSUM_WIDTH (32)
#define NBL_UPED_MD_AUX_PLD_CKSUM_DWLEN (1)
union uped_md_aux_pld_cksum_u {
	struct uped_md_aux_pld_cksum {
		u32 ck:32;               /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_AUX_PLD_CKSUM_DWLEN];
} __packed;

#define NBL_UPED_INNER_PKT_CKSUM_ADDR  (0x15c918)
#define NBL_UPED_INNER_PKT_CKSUM_DEPTH (1)
#define NBL_UPED_INNER_PKT_CKSUM_WIDTH (32)
#define NBL_UPED_INNER_PKT_CKSUM_DWLEN (1)
union uped_inner_pkt_cksum_u {
	struct uped_inner_pkt_cksum {
		u32 ck:16;               /* [15:0] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_INNER_PKT_CKSUM_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_0_ADDR  (0x15c920)
#define NBL_UPED_MD_EDIT_0_DEPTH (1)
#define NBL_UPED_MD_EDIT_0_WIDTH (32)
#define NBL_UPED_MD_EDIT_0_DWLEN (1)
union uped_md_edit_0_u {
	struct uped_md_edit_0 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_0_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_1_ADDR  (0x15c924)
#define NBL_UPED_MD_EDIT_1_DEPTH (1)
#define NBL_UPED_MD_EDIT_1_WIDTH (32)
#define NBL_UPED_MD_EDIT_1_DWLEN (1)
union uped_md_edit_1_u {
	struct uped_md_edit_1 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_1_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_2_ADDR  (0x15c928)
#define NBL_UPED_MD_EDIT_2_DEPTH (1)
#define NBL_UPED_MD_EDIT_2_WIDTH (32)
#define NBL_UPED_MD_EDIT_2_DWLEN (1)
union uped_md_edit_2_u {
	struct uped_md_edit_2 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_2_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_3_ADDR  (0x15c92c)
#define NBL_UPED_MD_EDIT_3_DEPTH (1)
#define NBL_UPED_MD_EDIT_3_WIDTH (32)
#define NBL_UPED_MD_EDIT_3_DWLEN (1)
union uped_md_edit_3_u {
	struct uped_md_edit_3 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_3_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_4_ADDR  (0x15c930)
#define NBL_UPED_MD_EDIT_4_DEPTH (1)
#define NBL_UPED_MD_EDIT_4_WIDTH (32)
#define NBL_UPED_MD_EDIT_4_DWLEN (1)
union uped_md_edit_4_u {
	struct uped_md_edit_4 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_4_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_5_ADDR  (0x15c934)
#define NBL_UPED_MD_EDIT_5_DEPTH (1)
#define NBL_UPED_MD_EDIT_5_WIDTH (32)
#define NBL_UPED_MD_EDIT_5_DWLEN (1)
union uped_md_edit_5_u {
	struct uped_md_edit_5 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_5_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_6_ADDR  (0x15c938)
#define NBL_UPED_MD_EDIT_6_DEPTH (1)
#define NBL_UPED_MD_EDIT_6_WIDTH (32)
#define NBL_UPED_MD_EDIT_6_DWLEN (1)
union uped_md_edit_6_u {
	struct uped_md_edit_6 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_6_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_7_ADDR  (0x15c93c)
#define NBL_UPED_MD_EDIT_7_DEPTH (1)
#define NBL_UPED_MD_EDIT_7_WIDTH (32)
#define NBL_UPED_MD_EDIT_7_DWLEN (1)
union uped_md_edit_7_u {
	struct uped_md_edit_7 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_7_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_8_ADDR  (0x15c940)
#define NBL_UPED_MD_EDIT_8_DEPTH (1)
#define NBL_UPED_MD_EDIT_8_WIDTH (32)
#define NBL_UPED_MD_EDIT_8_DWLEN (1)
union uped_md_edit_8_u {
	struct uped_md_edit_8 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_8_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_9_ADDR  (0x15c944)
#define NBL_UPED_MD_EDIT_9_DEPTH (1)
#define NBL_UPED_MD_EDIT_9_WIDTH (32)
#define NBL_UPED_MD_EDIT_9_DWLEN (1)
union uped_md_edit_9_u {
	struct uped_md_edit_9 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_9_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_10_ADDR  (0x15c948)
#define NBL_UPED_MD_EDIT_10_DEPTH (1)
#define NBL_UPED_MD_EDIT_10_WIDTH (32)
#define NBL_UPED_MD_EDIT_10_DWLEN (1)
union uped_md_edit_10_u {
	struct uped_md_edit_10 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_10_DWLEN];
} __packed;

#define NBL_UPED_MD_EDIT_11_ADDR  (0x15c94c)
#define NBL_UPED_MD_EDIT_11_DEPTH (1)
#define NBL_UPED_MD_EDIT_11_WIDTH (32)
#define NBL_UPED_MD_EDIT_11_DWLEN (1)
union uped_md_edit_11_u {
	struct uped_md_edit_11 {
		u32 vau:16;              /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_MD_EDIT_11_DWLEN];
} __packed;

#define NBL_UPED_ADD_DEL_LEN_ADDR  (0x15c950)
#define NBL_UPED_ADD_DEL_LEN_DEPTH (1)
#define NBL_UPED_ADD_DEL_LEN_WIDTH (32)
#define NBL_UPED_ADD_DEL_LEN_DWLEN (1)
union uped_add_del_len_u {
	struct uped_add_del_len {
		u32 len:9;               /* [8:0] Default:0x0 RO */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_ADD_DEL_LEN_DWLEN];
} __packed;

#define NBL_UPED_TTL_INFO_ADDR  (0x15c970)
#define NBL_UPED_TTL_INFO_DEPTH (1)
#define NBL_UPED_TTL_INFO_WIDTH (32)
#define NBL_UPED_TTL_INFO_DWLEN (1)
union uped_ttl_info_u {
	struct uped_ttl_info {
		u32 old_ttl:8;           /* [7:0] Default:0x0 RO */
		u32 new_ttl:8;           /* [15:8] Default:0x0 RO */
		u32 ttl_val:1;           /* [16] Default:0x0 RC */
		u32 rsv:15;              /* [31:17] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TTL_INFO_DWLEN];
} __packed;

#define NBL_UPED_LEN_INFO_VLD_ADDR  (0x15c974)
#define NBL_UPED_LEN_INFO_VLD_DEPTH (1)
#define NBL_UPED_LEN_INFO_VLD_WIDTH (32)
#define NBL_UPED_LEN_INFO_VLD_DWLEN (1)
union uped_len_info_vld_u {
	struct uped_len_info_vld {
		u32 length0:1;           /* [0] Default:0x0 RC */
		u32 length1:1;           /* [1] Default:0x0 RC */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_LEN_INFO_VLD_DWLEN];
} __packed;

#define NBL_UPED_LEN0_INFO_ADDR  (0x15c978)
#define NBL_UPED_LEN0_INFO_DEPTH (1)
#define NBL_UPED_LEN0_INFO_WIDTH (32)
#define NBL_UPED_LEN0_INFO_DWLEN (1)
union uped_len0_info_u {
	struct uped_len0_info {
		u32 old_len:16;          /* [15:0] Default:0x0 RO */
		u32 new_len:16;          /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_LEN0_INFO_DWLEN];
} __packed;

#define NBL_UPED_LEN1_INFO_ADDR  (0x15c97c)
#define NBL_UPED_LEN1_INFO_DEPTH (1)
#define NBL_UPED_LEN1_INFO_WIDTH (32)
#define NBL_UPED_LEN1_INFO_DWLEN (1)
union uped_len1_info_u {
	struct uped_len1_info {
		u32 old_len:16;          /* [15:0] Default:0x0 RO */
		u32 new_len:16;          /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_LEN1_INFO_DWLEN];
} __packed;

#define NBL_UPED_EDIT_ATNUM_INFO_ADDR  (0x15c980)
#define NBL_UPED_EDIT_ATNUM_INFO_DEPTH (1)
#define NBL_UPED_EDIT_ATNUM_INFO_WIDTH (32)
#define NBL_UPED_EDIT_ATNUM_INFO_DWLEN (1)
union uped_edit_atnum_info_u {
	struct uped_edit_atnum_info {
		u32 replace:4;           /* [3:0] Default:0x0 RO */
		u32 del:4;               /* [7:4] Default:0x0 RO */
		u32 add:4;               /* [11:8] Default:0x0 RO */
		u32 ttl:4;               /* [15:12] Default:0x0 RO */
		u32 dscp:4;              /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_EDIT_ATNUM_INFO_DWLEN];
} __packed;

#define NBL_UPED_EDIT_NO_AT_INFO_ADDR  (0x15c984)
#define NBL_UPED_EDIT_NO_AT_INFO_DEPTH (1)
#define NBL_UPED_EDIT_NO_AT_INFO_WIDTH (32)
#define NBL_UPED_EDIT_NO_AT_INFO_DWLEN (1)
union uped_edit_no_at_info_u {
	struct uped_edit_no_at_info {
		u32 l3_len:1;            /* [0] Default:0x0 RC */
		u32 l4_len:1;            /* [1] Default:0x0 RC */
		u32 l3_ck:1;             /* [2] Default:0x0 RC */
		u32 l4_ck:1;             /* [3] Default:0x0 RC */
		u32 sctp_ck:1;           /* [4] Default:0x0 RC */
		u32 rsv:27;              /* [31:05] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_EDIT_NO_AT_INFO_DWLEN];
} __packed;

#define NBL_UPED_UL4S_TOTAL_LENGTH_ADDR  (0x15c988)
#define NBL_UPED_UL4S_TOTAL_LENGTH_DEPTH (1)
#define NBL_UPED_UL4S_TOTAL_LENGTH_WIDTH (32)
#define NBL_UPED_UL4S_TOTAL_LENGTH_DWLEN (1)
union uped_ul4s_total_length_u {
	struct uped_ul4s_total_length {
		u32 vau:14;              /* [13:0] Default:0x0 RO */
		u32 rsv:16;              /* [29:14] Default:0x0 RO */
		u32 tls_ind:1;           /* [30] Default:0x0 RO */
		u32 vld:1;               /* [31] Default:0x0 RC */
	} __packed info;
	u32 data[NBL_UPED_UL4S_TOTAL_LENGTH_DWLEN];
} __packed;

#define NBL_UPED_HW_EDT_PROF_ADDR  (0x15d000)
#define NBL_UPED_HW_EDT_PROF_DEPTH (32)
#define NBL_UPED_HW_EDT_PROF_WIDTH (32)
#define NBL_UPED_HW_EDT_PROF_DWLEN (1)
union uped_hw_edt_prof_u {
	struct uped_hw_edt_prof {
		u32 l4_len:2;            /* [1:0] Default:0x2 RW */
		u32 l3_len:2;            /* [3:2] Default:0x2 RW */
		u32 l4_ck:3;             /* [6:4] Default:0x7 RW */
		u32 l3_ck:1;             /* [7:7] Default:0x0 RW */
		u32 l4_ck_zero_free:1;   /* [8:8] Default:0x1 RW */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_HW_EDT_PROF_DWLEN];
} __packed;
#define NBL_UPED_HW_EDT_PROF_REG(r) (NBL_UPED_HW_EDT_PROF_ADDR + \
		(NBL_UPED_HW_EDT_PROF_DWLEN * 4) * (r))

#define NBL_UPED_OUT_MASK_ADDR  (0x15e000)
#define NBL_UPED_OUT_MASK_DEPTH (24)
#define NBL_UPED_OUT_MASK_WIDTH (64)
#define NBL_UPED_OUT_MASK_DWLEN (2)
union uped_out_mask_u {
	struct uped_out_mask {
		u32 flag:32;             /* [31:0] Default:0x0 RW */
		u32 fwd:30;              /* [61:32] Default:0x0 RW */
		u32 rsv:2;               /* [63:62] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_OUT_MASK_DWLEN];
} __packed;
#define NBL_UPED_OUT_MASK_REG(r) (NBL_UPED_OUT_MASK_ADDR + \
		(NBL_UPED_OUT_MASK_DWLEN * 4) * (r))

#define NBL_UPED_TAB_EDIT_CMD_ADDR  (0x15f000)
#define NBL_UPED_TAB_EDIT_CMD_DEPTH (32)
#define NBL_UPED_TAB_EDIT_CMD_WIDTH (32)
#define NBL_UPED_TAB_EDIT_CMD_DWLEN (1)
union uped_tab_edit_cmd_u {
	struct uped_tab_edit_cmd {
		u32 in_offset:8;         /* [7:0] Default:0x0 RW */
		u32 phid:2;              /* [9:8] Default:0x0 RW */
		u32 len:7;               /* [16:10] Default:0x0 RW */
		u32 mode:4;              /* [20:17] Default:0xf RW */
		u32 l4_ck_ofld_upt:1;    /* [21] Default:0x1 RW */
		u32 l3_ck_ofld_upt:1;    /* [22] Default:0x1 RW */
		u32 rsv:9;               /* [31:23] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TAB_EDIT_CMD_DWLEN];
} __packed;
#define NBL_UPED_TAB_EDIT_CMD_REG(r) (NBL_UPED_TAB_EDIT_CMD_ADDR + \
		(NBL_UPED_TAB_EDIT_CMD_DWLEN * 4) * (r))

#define NBL_UPED_TAB_VSI_TYPE_ADDR  (0x161000)
#define NBL_UPED_TAB_VSI_TYPE_DEPTH (1031)
#define NBL_UPED_TAB_VSI_TYPE_WIDTH (32)
#define NBL_UPED_TAB_VSI_TYPE_DWLEN (1)
union uped_tab_vsi_type_u {
	struct uped_tab_vsi_type {
		u32 sel:4;               /* [3:0] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPED_TAB_VSI_TYPE_DWLEN];
} __packed;
#define NBL_UPED_TAB_VSI_TYPE_REG(r) (NBL_UPED_TAB_VSI_TYPE_ADDR + \
		(NBL_UPED_TAB_VSI_TYPE_DWLEN * 4) * (r))

#define NBL_UPED_TAB_REPLACE_ADDR  (0x164000)
#define NBL_UPED_TAB_REPLACE_DEPTH (2048)
#define NBL_UPED_TAB_REPLACE_WIDTH (64)
#define NBL_UPED_TAB_REPLACE_DWLEN (2)
union uped_tab_replace_u {
	struct uped_tab_replace {
		u32 vau_arr[2];          /* [63:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPED_TAB_REPLACE_DWLEN];
} __packed;
#define NBL_UPED_TAB_REPLACE_REG(r) (NBL_UPED_TAB_REPLACE_ADDR + \
		(NBL_UPED_TAB_REPLACE_DWLEN * 4) * (r))

#endif
