/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_PP1_H
#define NBL_PP1_H 1

#include <linux/types.h>

#define NBL_PP1_BASE (0x00B24000)

#define NBL_PP1_INT_STATUS_ADDR  (0xb24000)
#define NBL_PP1_INT_STATUS_DEPTH (1)
#define NBL_PP1_INT_STATUS_WIDTH (32)
#define NBL_PP1_INT_STATUS_DWLEN (1)
union pp1_int_status_u {
	struct pp1_int_status {
		u32 rsv5:1;              /* [00:00] Default:0x0 RO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_INT_STATUS_DWLEN];
} __packed;

#define NBL_PP1_INT_MASK_ADDR  (0xb24004)
#define NBL_PP1_INT_MASK_DEPTH (1)
#define NBL_PP1_INT_MASK_WIDTH (32)
#define NBL_PP1_INT_MASK_DWLEN (1)
union pp1_int_mask_u {
	struct pp1_int_mask {
		u32 rsv5:1;              /* [00:00] Default:0x0 RO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_INT_MASK_DWLEN];
} __packed;

#define NBL_PP1_INT_SET_ADDR  (0xb24008)
#define NBL_PP1_INT_SET_DEPTH (1)
#define NBL_PP1_INT_SET_WIDTH (32)
#define NBL_PP1_INT_SET_DWLEN (1)
union pp1_int_set_u {
	struct pp1_int_set {
		u32 rsv5:1;              /* [00:00] Default:0x0 RO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_INT_SET_DWLEN];
} __packed;

#define NBL_PP1_INIT_DONE_ADDR  (0xb2400c)
#define NBL_PP1_INIT_DONE_DEPTH (1)
#define NBL_PP1_INIT_DONE_WIDTH (32)
#define NBL_PP1_INIT_DONE_DWLEN (1)
union pp1_init_done_u {
	struct pp1_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_INIT_DONE_DWLEN];
} __packed;

#define NBL_PP1_CFG_ERR_INFO_ADDR  (0xb24038)
#define NBL_PP1_CFG_ERR_INFO_DEPTH (1)
#define NBL_PP1_CFG_ERR_INFO_WIDTH (32)
#define NBL_PP1_CFG_ERR_INFO_DWLEN (1)
union pp1_cfg_err_info_u {
	struct pp1_cfg_err_info {
		u32 id:1;                /* [0:0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_PP1_CIF_ERR_INFO_ADDR  (0xb24040)
#define NBL_PP1_CIF_ERR_INFO_DEPTH (1)
#define NBL_PP1_CIF_ERR_INFO_WIDTH (32)
#define NBL_PP1_CIF_ERR_INFO_DWLEN (1)
union pp1_cif_err_info_u {
	struct pp1_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_PP1_CAR_CTRL_ADDR  (0xb24100)
#define NBL_PP1_CAR_CTRL_DEPTH (1)
#define NBL_PP1_CAR_CTRL_WIDTH (32)
#define NBL_PP1_CAR_CTRL_DWLEN (1)
union pp1_car_ctrl_u {
	struct pp1_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_CAR_CTRL_DWLEN];
} __packed;

#define NBL_PP1_MODE_ADDR  (0xb24104)
#define NBL_PP1_MODE_DEPTH (1)
#define NBL_PP1_MODE_WIDTH (32)
#define NBL_PP1_MODE_DWLEN (1)
union pp1_mode_u {
	struct pp1_mode {
		u32 bypass:1;            /* [0] Default:0x0 RW */
		u32 internal_loopback_en:1; /* [1] Default:0x0 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_MODE_DWLEN];
} __packed;

#define NBL_PP1_SET_FLAGS0_ADDR  (0xb24108)
#define NBL_PP1_SET_FLAGS0_DEPTH (1)
#define NBL_PP1_SET_FLAGS0_WIDTH (32)
#define NBL_PP1_SET_FLAGS0_DWLEN (1)
union pp1_set_flags0_u {
	struct pp1_set_flags0 {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_SET_FLAGS0_DWLEN];
} __packed;

#define NBL_PP1_SET_FLAGS1_ADDR  (0xb2410c)
#define NBL_PP1_SET_FLAGS1_DEPTH (1)
#define NBL_PP1_SET_FLAGS1_WIDTH (32)
#define NBL_PP1_SET_FLAGS1_DWLEN (1)
union pp1_set_flags1_u {
	struct pp1_set_flags1 {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_SET_FLAGS1_DWLEN];
} __packed;

#define NBL_PP1_CLEAR_FLAGS0_ADDR  (0xb24110)
#define NBL_PP1_CLEAR_FLAGS0_DEPTH (1)
#define NBL_PP1_CLEAR_FLAGS0_WIDTH (32)
#define NBL_PP1_CLEAR_FLAGS0_DWLEN (1)
union pp1_clear_flags0_u {
	struct pp1_clear_flags0 {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_CLEAR_FLAGS0_DWLEN];
} __packed;

#define NBL_PP1_CLEAR_FLAGS1_ADDR  (0xb24114)
#define NBL_PP1_CLEAR_FLAGS1_DEPTH (1)
#define NBL_PP1_CLEAR_FLAGS1_WIDTH (32)
#define NBL_PP1_CLEAR_FLAGS1_DWLEN (1)
union pp1_clear_flags1_u {
	struct pp1_clear_flags1 {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_CLEAR_FLAGS1_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY0_ADDR  (0xb24118)
#define NBL_PP1_ACTION_PRIORITY0_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY0_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY0_DWLEN (1)
union pp1_action_priority0_u {
	struct pp1_action_priority0 {
		u32 action_id3_pri:2;    /* [01:00] Default:0x0 RW */
		u32 action_id4_pri:2;    /* [03:02] Default:0x0 RW */
		u32 action_id5_pri:2;    /* [05:04] Default:0x0 RW */
		u32 action_id6_pri:2;    /* [07:06] Default:0x0 RW */
		u32 action_id7_pri:2;    /* [09:08] Default:0x0 RW */
		u32 action_id8_pri:2;    /* [11:10] Default:0x0 RW */
		u32 action_id9_pri:2;    /* [13:12] Default:0x0 RW */
		u32 action_id10_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id11_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id12_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id13_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id14_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id15_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id16_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id17_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id18_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY0_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY1_ADDR  (0xb2411c)
#define NBL_PP1_ACTION_PRIORITY1_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY1_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY1_DWLEN (1)
union pp1_action_priority1_u {
	struct pp1_action_priority1 {
		u32 action_id19_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id20_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id21_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id22_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id23_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id24_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id25_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id26_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id27_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id28_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id29_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id30_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id31_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id32_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id33_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id34_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY1_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY2_ADDR  (0xb24120)
#define NBL_PP1_ACTION_PRIORITY2_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY2_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY2_DWLEN (1)
union pp1_action_priority2_u {
	struct pp1_action_priority2 {
		u32 action_id35_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id36_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id37_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id38_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id39_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id40_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id41_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id42_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id43_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id44_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id45_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id46_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id47_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id48_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id49_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id50_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY2_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY3_ADDR  (0xb24124)
#define NBL_PP1_ACTION_PRIORITY3_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY3_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY3_DWLEN (1)
union pp1_action_priority3_u {
	struct pp1_action_priority3 {
		u32 action_id51_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id52_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id53_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id54_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id55_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id56_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id57_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id58_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id59_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id60_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id61_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id62_pri:2;   /* [23:22] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY3_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY4_ADDR  (0xb24128)
#define NBL_PP1_ACTION_PRIORITY4_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY4_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY4_DWLEN (1)
union pp1_action_priority4_u {
	struct pp1_action_priority4 {
		u32 action_id3_pri:2;    /* [01:00] Default:0x0 RW */
		u32 action_id4_pri:2;    /* [03:02] Default:0x0 RW */
		u32 action_id5_pri:2;    /* [05:04] Default:0x0 RW */
		u32 action_id6_pri:2;    /* [07:06] Default:0x0 RW */
		u32 action_id7_pri:2;    /* [09:08] Default:0x0 RW */
		u32 action_id8_pri:2;    /* [11:10] Default:0x0 RW */
		u32 action_id9_pri:2;    /* [13:12] Default:0x0 RW */
		u32 action_id10_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id11_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id12_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id13_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id14_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id15_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id16_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id17_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id18_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY4_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY5_ADDR  (0xb2412c)
#define NBL_PP1_ACTION_PRIORITY5_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY5_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY5_DWLEN (1)
union pp1_action_priority5_u {
	struct pp1_action_priority5 {
		u32 action_id19_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id20_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id21_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id22_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id23_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id24_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id25_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id26_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id27_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id28_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id29_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id30_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id31_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id32_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id33_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id34_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY5_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY6_ADDR  (0xb24130)
#define NBL_PP1_ACTION_PRIORITY6_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY6_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY6_DWLEN (1)
union pp1_action_priority6_u {
	struct pp1_action_priority6 {
		u32 action_id35_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id36_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id37_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id38_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id39_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id40_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id41_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id42_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id43_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id44_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id45_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id46_pri:2;   /* [23:22] Default:0x0 RW */
		u32 action_id47_pri:2;   /* [25:24] Default:0x0 RW */
		u32 action_id48_pri:2;   /* [27:26] Default:0x0 RW */
		u32 action_id49_pri:2;   /* [29:28] Default:0x0 RW */
		u32 action_id50_pri:2;   /* [31:30] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY6_DWLEN];
} __packed;

#define NBL_PP1_ACTION_PRIORITY7_ADDR  (0xb24134)
#define NBL_PP1_ACTION_PRIORITY7_DEPTH (1)
#define NBL_PP1_ACTION_PRIORITY7_WIDTH (32)
#define NBL_PP1_ACTION_PRIORITY7_DWLEN (1)
union pp1_action_priority7_u {
	struct pp1_action_priority7 {
		u32 action_id51_pri:2;   /* [01:00] Default:0x0 RW */
		u32 action_id52_pri:2;   /* [03:02] Default:0x0 RW */
		u32 action_id53_pri:2;   /* [05:04] Default:0x0 RW */
		u32 action_id54_pri:2;   /* [07:06] Default:0x0 RW */
		u32 action_id55_pri:2;   /* [09:08] Default:0x0 RW */
		u32 action_id56_pri:2;   /* [11:10] Default:0x0 RW */
		u32 action_id57_pri:2;   /* [13:12] Default:0x0 RW */
		u32 action_id58_pri:2;   /* [15:14] Default:0x0 RW */
		u32 action_id59_pri:2;   /* [17:16] Default:0x0 RW */
		u32 action_id60_pri:2;   /* [19:18] Default:0x0 RW */
		u32 action_id61_pri:2;   /* [21:20] Default:0x0 RW */
		u32 action_id62_pri:2;   /* [23:22] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ACTION_PRIORITY7_DWLEN];
} __packed;

#define NBL_PP1_CPU_ACCESS_ADDR  (0xb2416c)
#define NBL_PP1_CPU_ACCESS_DEPTH (1)
#define NBL_PP1_CPU_ACCESS_WIDTH (32)
#define NBL_PP1_CPU_ACCESS_DWLEN (1)
union pp1_cpu_access_u {
	struct pp1_cpu_access {
		u32 bp_th:10;            /* [9:0] Default:0x34 RW */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 timeout_th:10;       /* [25:16] Default:0x100 RW */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_CPU_ACCESS_DWLEN];
} __packed;

#define NBL_PP1_RDMA_BYPASS_ADDR  (0xb24170)
#define NBL_PP1_RDMA_BYPASS_DEPTH (1)
#define NBL_PP1_RDMA_BYPASS_WIDTH (32)
#define NBL_PP1_RDMA_BYPASS_DWLEN (1)
union pp1_rdma_bypass_u {
	struct pp1_rdma_bypass {
		u32 rdma_flag_offset:5;  /* [4:0] Default:0x0 RW */
		u32 dn_bypass_en:1;      /* [5] Default:0x0 RW */
		u32 up_bypass_en:1;      /* [6] Default:0x0 RW */
		u32 rsv1:1;              /* [7] Default:0x0 RO */
		u32 dir_flag_offset:5;   /* [12:8] Default:0x0 RW */
		u32 rsv:19;              /* [31:13] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_RDMA_BYPASS_DWLEN];
} __packed;

#define NBL_PP1_INIT_START_ADDR  (0xb241fc)
#define NBL_PP1_INIT_START_DEPTH (1)
#define NBL_PP1_INIT_START_WIDTH (32)
#define NBL_PP1_INIT_START_DWLEN (1)
union pp1_init_start_u {
	struct pp1_init_start {
		u32 en:1;                /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_INIT_START_DWLEN];
} __packed;

#define NBL_PP1_BP_SET_ADDR  (0xb24200)
#define NBL_PP1_BP_SET_DEPTH (1)
#define NBL_PP1_BP_SET_WIDTH (32)
#define NBL_PP1_BP_SET_DWLEN (1)
union pp1_bp_set_u {
	struct pp1_bp_set {
		u32 pp_up:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_BP_SET_DWLEN];
} __packed;

#define NBL_PP1_BP_MASK_ADDR  (0xb24204)
#define NBL_PP1_BP_MASK_DEPTH (1)
#define NBL_PP1_BP_MASK_WIDTH (32)
#define NBL_PP1_BP_MASK_DWLEN (1)
union pp1_bp_mask_u {
	struct pp1_bp_mask {
		u32 dn_pp:1;             /* [00:00] Default:0x0 RW */
		u32 fem_pp:1;            /* [01:01] Default:0x0 RW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_BP_MASK_DWLEN];
} __packed;

#define NBL_PP1_BP_STATE_ADDR  (0xb24308)
#define NBL_PP1_BP_STATE_DEPTH (1)
#define NBL_PP1_BP_STATE_WIDTH (32)
#define NBL_PP1_BP_STATE_DWLEN (1)
union pp1_bp_state_u {
	struct pp1_bp_state {
		u32 dn_pp_bp:1;          /* [00:00] Default:0x0 RO */
		u32 fem_pp_bp:1;         /* [01:01] Default:0x0 RO */
		u32 pp_up_bp:1;          /* [02:02] Default:0x0 RO */
		u32 inter_pp_bp:1;       /* [03:03] Default:0x0 RO */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_BP_STATE_DWLEN];
} __packed;

#define NBL_PP1_BP_HISTORY_ADDR  (0xb2430c)
#define NBL_PP1_BP_HISTORY_DEPTH (1)
#define NBL_PP1_BP_HISTORY_WIDTH (32)
#define NBL_PP1_BP_HISTORY_DWLEN (1)
union pp1_bp_history_u {
	struct pp1_bp_history {
		u32 dn_pp_bp:1;          /* [00:00] Default:0x0 RC */
		u32 fem_pp_bp:1;         /* [01:01] Default:0x0 RC */
		u32 pp_up_bp:1;          /* [02:02] Default:0x0 RC */
		u32 inter_pp_bp:1;       /* [03:03] Default:0x0 RC */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_BP_HISTORY_DWLEN];
} __packed;

#define NBL_PP1_CFG_TEST_ADDR  (0xb2442c)
#define NBL_PP1_CFG_TEST_DEPTH (1)
#define NBL_PP1_CFG_TEST_WIDTH (32)
#define NBL_PP1_CFG_TEST_DWLEN (1)
union pp1_cfg_test_u {
	struct pp1_cfg_test {
		u32 test:32;             /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_CFG_TEST_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION0_ADDR  (0xb24430)
#define NBL_PP1_ABNORMAL_ACTION0_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION0_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION0_DWLEN (1)
union pp1_abnormal_action0_u {
	struct pp1_abnormal_action0 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION0_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION1_ADDR  (0xb24434)
#define NBL_PP1_ABNORMAL_ACTION1_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION1_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION1_DWLEN (1)
union pp1_abnormal_action1_u {
	struct pp1_abnormal_action1 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION1_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION2_ADDR  (0xb24438)
#define NBL_PP1_ABNORMAL_ACTION2_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION2_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION2_DWLEN (1)
union pp1_abnormal_action2_u {
	struct pp1_abnormal_action2 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION2_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION3_ADDR  (0xb2443c)
#define NBL_PP1_ABNORMAL_ACTION3_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION3_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION3_DWLEN (1)
union pp1_abnormal_action3_u {
	struct pp1_abnormal_action3 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION3_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION4_ADDR  (0xb24440)
#define NBL_PP1_ABNORMAL_ACTION4_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION4_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION4_DWLEN (1)
union pp1_abnormal_action4_u {
	struct pp1_abnormal_action4 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION4_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION5_ADDR  (0xb24444)
#define NBL_PP1_ABNORMAL_ACTION5_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION5_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION5_DWLEN (1)
union pp1_abnormal_action5_u {
	struct pp1_abnormal_action5 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION5_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION6_ADDR  (0xb24448)
#define NBL_PP1_ABNORMAL_ACTION6_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION6_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION6_DWLEN (1)
union pp1_abnormal_action6_u {
	struct pp1_abnormal_action6 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION6_DWLEN];
} __packed;

#define NBL_PP1_ABNORMAL_ACTION7_ADDR  (0xb2444c)
#define NBL_PP1_ABNORMAL_ACTION7_DEPTH (1)
#define NBL_PP1_ABNORMAL_ACTION7_WIDTH (32)
#define NBL_PP1_ABNORMAL_ACTION7_DWLEN (1)
union pp1_abnormal_action7_u {
	struct pp1_abnormal_action7 {
		u32 data:22;             /* [21:00] Default:0x0 RW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_ABNORMAL_ACTION7_DWLEN];
} __packed;

#define NBL_PP1_FWD_DPORT_ACTION_ADDR  (0xb24450)
#define NBL_PP1_FWD_DPORT_ACTION_DEPTH (1)
#define NBL_PP1_FWD_DPORT_ACTION_WIDTH (32)
#define NBL_PP1_FWD_DPORT_ACTION_DWLEN (1)
union pp1_fwd_dport_action_u {
	struct pp1_fwd_dport_action {
		u32 action_id:6;         /* [05:00] Default:0x9 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PP1_FWD_DPORT_ACTION_DWLEN];
} __packed;

#define NBL_PP1_RDMA_VSI_BTM_ADDR  (0xb24454)
#define NBL_PP1_RDMA_VSI_BTM_DEPTH (32)
#define NBL_PP1_RDMA_VSI_BTM_WIDTH (32)
#define NBL_PP1_RDMA_VSI_BTM_DWLEN (1)
union pp1_rdma_vsi_btm_u {
	struct pp1_rdma_vsi_btm {
		u32 btm:32;              /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PP1_RDMA_VSI_BTM_DWLEN];
} __packed;
#define NBL_PP1_RDMA_VSI_BTM_REG(r) (NBL_PP1_RDMA_VSI_BTM_ADDR + \
		(NBL_PP1_RDMA_VSI_BTM_DWLEN * 4) * (r))

#define NBL_PP1_KGEN_KEY_PRF_ADDR (0xb25000)
#define NBL_PP1_KGEN_KEY_PRF_DEPTH (16)
#define NBL_PP1_KGEN_KEY_PRF_WIDTH (512)
#define NBL_PP1_KGEN_KEY_PRF_DWLEN (16)
union pp1_kgen_key_prf_u {
	struct pp1_kgen_key_prf {
		u32 ext4_0_src:10;
		u32 ext4_0_dst:7;
		u32 ext4_1_src:10;
		u32 ext4_1_dst:7;
		u32 ext4_2_src:10;
		u32 ext4_2_dst:7;
		u32 ext4_3_src:10;
		u32 ext4_3_dst:7;
		u32 ext8_0_src:9;
		u32 ext8_0_dst:6;
		u32 ext8_1_src:9;
		u32 ext8_1_dst:6;
		u32 ext8_2_src:9;
		u32 ext8_2_dst:6;
		u32 ext8_3_src:9;
		u32 ext8_3_dst:6;
		u32 ext8_4_src:9;
		u32 ext8_4_dst:6;
		u32 ext8_5_src:9;
		u32 ext8_5_dst:6;
		u32 ext8_6_src:9;
		u32 ext8_6_dst:6;
		u32 ext8_7_src:9;
		u32 ext8_7_dst:6;
		u32 ext16_0_src:8;
		u32 ext16_0_dst:5;
		u32 ext16_1_src:8;
		u32 ext16_1_dst:5;
		u32 ext16_2_src:8;
		u32 ext16_2_dst:5;
		u32 ext16_3_src:8;
		u32 ext16_3_dst:5;
		u32 ext32_0_src:7;
		u32 ext32_0_dst:4;
		u32 ext32_1_src:7;
		u32 ext32_1_dst:4;
		u32 ext32_2_src:7;
		u32 ext32_2_dst:4;
		u32 ext32_3_src:7;
		u32 ext32_3_dst:4;
		u32 sp_2_en:1;
		u32 sp_2_src_offset:3;
		u32 sp_2_dst_offset:8;
		u32 sp_4_en:1;
		u32 sp_4_src_offset:2;
		u32 sp_4_dst_offset:7;
		u32 sp_8_en:1;
		u32 sp_8_src_offset:1;
		u32 sp_8_dst_offset:6;
		u32 fwdact0_en:1;
		u32 fwdact0_id:6;
		u32 fwdact0_dst_offset:5;
		u32 fwdact1_en:1;
		u32 fwdact1_id:6;
		u32 fwdact1_dst_offset:5;
		u32 bts_en0:1;
		u32 bts_data0:1;
		u32 bts_des_offset0:9;
		u32 bts_en1:1;
		u32 bts_data1:1;
		u32 bts_des_offset1:9;
		u32 bts_en2:1;
		u32 bts_data2:1;
		u32 bts_des_offset2:9;
		u32 bts_en3:1;
		u32 bts_data3:1;
		u32 bts_des_offset3:9;
		u32 rsv1:2;
		u32 rsv[4];
	} __packed info;
	u32 data[NBL_PP1_KGEN_KEY_PRF_DWLEN];
};

#define NBL_PP1_KGEN_KEY_PRF_REG(r) (NBL_PP1_KGEN_KEY_PRF_ADDR + \
		(NBL_PP1_KGEN_KEY_PRF_DWLEN * 4) * (r))

#endif
