/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_MCC_H
#define NBL_MCC_H 1

#include <linux/types.h>

#define NBL_MCC_BASE (0x00B44000)

#define NBL_MCC_INT_STATUS_ADDR  (0xb44000)
#define NBL_MCC_INT_STATUS_DEPTH (1)
#define NBL_MCC_INT_STATUS_WIDTH (32)
#define NBL_MCC_INT_STATUS_DWLEN (1)
union mcc_int_status_u {
	struct mcc_int_status {
		u32 fatal_err:1;         /* [0] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fsm_err:1;           /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 cfg_err:1;           /* [5] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [6] Default:0x0 RWC */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_INT_STATUS_DWLEN];
} __packed;

#define NBL_MCC_INT_MASK_ADDR  (0xb44004)
#define NBL_MCC_INT_MASK_DEPTH (1)
#define NBL_MCC_INT_MASK_WIDTH (32)
#define NBL_MCC_INT_MASK_DWLEN (1)
union mcc_int_mask_u {
	struct mcc_int_mask {
		u32 fatal_err:1;         /* [0] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 RW */
		u32 fsm_err:1;           /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 cfg_err:1;           /* [5] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [6] Default:0x0 RW */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_INT_MASK_DWLEN];
} __packed;

#define NBL_MCC_INT_SET_ADDR  (0xb44008)
#define NBL_MCC_INT_SET_DEPTH (1)
#define NBL_MCC_INT_SET_WIDTH (32)
#define NBL_MCC_INT_SET_DWLEN (1)
union mcc_int_set_u {
	struct mcc_int_set {
		u32 fatal_err:1;         /* [0] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [1] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [2] Default:0x0 WO */
		u32 fsm_err:1;           /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 cfg_err:1;           /* [5] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [6] Default:0x0 WO */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_INT_SET_DWLEN];
} __packed;

#define NBL_MCC_INIT_DONE_ADDR  (0xb4400c)
#define NBL_MCC_INIT_DONE_DEPTH (1)
#define NBL_MCC_INIT_DONE_WIDTH (32)
#define NBL_MCC_INIT_DONE_DWLEN (1)
union mcc_init_done_u {
	struct mcc_init_done {
		u32 done:1;              /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_INIT_DONE_DWLEN];
} __packed;

#define NBL_MCC_CIF_ERR_INFO_ADDR  (0xb44040)
#define NBL_MCC_CIF_ERR_INFO_DEPTH (1)
#define NBL_MCC_CIF_ERR_INFO_WIDTH (32)
#define NBL_MCC_CIF_ERR_INFO_DWLEN (1)
union mcc_cif_err_info_u {
	struct mcc_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_MCC_CFG_ERR_INFO_ADDR  (0xb44050)
#define NBL_MCC_CFG_ERR_INFO_DEPTH (1)
#define NBL_MCC_CFG_ERR_INFO_WIDTH (32)
#define NBL_MCC_CFG_ERR_INFO_DWLEN (1)
union mcc_cfg_err_info_u {
	struct mcc_cfg_err_info {
		u32 id:8;                /* [7:0] Default:0x0 RO */
		u32 addr:16;             /* [23:8] Default:0x0 RO */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_MCC_CAR_CTRL_ADDR  (0xb44100)
#define NBL_MCC_CAR_CTRL_DEPTH (1)
#define NBL_MCC_CAR_CTRL_WIDTH (32)
#define NBL_MCC_CAR_CTRL_DWLEN (1)
union mcc_car_ctrl_u {
	struct mcc_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_CAR_CTRL_DWLEN];
} __packed;

#define NBL_MCC_TIMEOUT_CFG_ADDR  (0xb44140)
#define NBL_MCC_TIMEOUT_CFG_DEPTH (1)
#define NBL_MCC_TIMEOUT_CFG_WIDTH (32)
#define NBL_MCC_TIMEOUT_CFG_DWLEN (1)
union mcc_timeout_cfg_u {
	struct mcc_timeout_cfg {
		u32 fsm_max_num:32;      /* [31:0] Default:0x0ffffffff RW */
	} __packed info;
	u32 data[NBL_MCC_TIMEOUT_CFG_DWLEN];
} __packed;

#define NBL_MCC_INIT_START_ADDR  (0xb44180)
#define NBL_MCC_INIT_START_DEPTH (1)
#define NBL_MCC_INIT_START_WIDTH (32)
#define NBL_MCC_INIT_START_DWLEN (1)
union mcc_init_start_u {
	struct mcc_init_start {
		u32 start:1;             /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_INIT_START_DWLEN];
} __packed;

#define NBL_MCC_RATE_CTRL_ADDR  (0xb44300)
#define NBL_MCC_RATE_CTRL_DEPTH (1)
#define NBL_MCC_RATE_CTRL_WIDTH (32)
#define NBL_MCC_RATE_CTRL_DWLEN (1)
union mcc_rate_ctrl_u {
	struct mcc_rate_ctrl {
		u32 rate_ctrl_eth_bandwidth:3; /* [2:0] Default:0x0 RW */
		u32 rate_ctrl_eth_switch:2; /* [4:3] Default:0x0 RW */
		u32 rate_ctrl_gear:3;    /* [7:5] Default:0x0 RW */
		u32 rate_ctrl_en:1;      /* [8] Default:0x0 RW */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_RATE_CTRL_DWLEN];
} __packed;

#define NBL_MCC_CREDIT_ADDR  (0xb44400)
#define NBL_MCC_CREDIT_DEPTH (1)
#define NBL_MCC_CREDIT_WIDTH (32)
#define NBL_MCC_CREDIT_DWLEN (1)
union mcc_credit_u {
	struct mcc_credit {
		u32 mcc_up_credit:5;     /* [4:0] Default:0x1d RW */
		u32 mcc_up_vld:1;        /* [5] Default:0x0 WO */
		u32 rsv1:10;             /* [15:6] Default:0x0 RO */
		u32 mcc_dn_credit:5;     /* [20:16] Default:0x1d RW */
		u32 mcc_dn_vld:1;        /* [21] Default:0x0 WO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_CREDIT_DWLEN];
} __packed;

#define NBL_MCC_ACTION_PRIORITY_ADDR  (0xb44500)
#define NBL_MCC_ACTION_PRIORITY_DEPTH (1)
#define NBL_MCC_ACTION_PRIORITY_WIDTH (32)
#define NBL_MCC_ACTION_PRIORITY_DWLEN (1)
union mcc_action_priority_u {
	struct mcc_action_priority {
		u32 statidx_act_pri:2;   /* [1:0] Default:0x0 RW */
		u32 dport_act_pri:2;     /* [3:2] Default:0x0 RW */
		u32 dqueue_act_pri:2;    /* [5:4] Default:0x0 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_ACTION_PRIORITY_DWLEN];
} __packed;

#define NBL_MCC_UU_WEIGHT_ADDR  (0xb44600)
#define NBL_MCC_UU_WEIGHT_DEPTH (1)
#define NBL_MCC_UU_WEIGHT_WIDTH (32)
#define NBL_MCC_UU_WEIGHT_DWLEN (1)
union mcc_uu_weight_u {
	struct mcc_uu_weight {
		u32 uu_weight:8;         /* [7:0] Default:0x2 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_UU_WEIGHT_DWLEN];
} __packed;

#define NBL_MCC_DU_WEIGHT_ADDR  (0xb44604)
#define NBL_MCC_DU_WEIGHT_DEPTH (1)
#define NBL_MCC_DU_WEIGHT_WIDTH (32)
#define NBL_MCC_DU_WEIGHT_DWLEN (1)
union mcc_du_weight_u {
	struct mcc_du_weight {
		u32 du_weight:8;         /* [7:0] Default:0x2 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_DU_WEIGHT_DWLEN];
} __packed;

#define NBL_MCC_UCH_WEIGHT_ADDR  (0xb44608)
#define NBL_MCC_UCH_WEIGHT_DEPTH (1)
#define NBL_MCC_UCH_WEIGHT_WIDTH (32)
#define NBL_MCC_UCH_WEIGHT_DWLEN (1)
union mcc_uch_weight_u {
	struct mcc_uch_weight {
		u32 uch_weight:8;        /* [7:0] Default:0x1 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_UCH_WEIGHT_DWLEN];
} __packed;

#define NBL_MCC_DCH_WEIGHT_ADDR  (0xb4460c)
#define NBL_MCC_DCH_WEIGHT_DEPTH (1)
#define NBL_MCC_DCH_WEIGHT_WIDTH (32)
#define NBL_MCC_DCH_WEIGHT_DWLEN (1)
union mcc_dch_weight_u {
	struct mcc_dch_weight {
		u32 dch_weight:8;        /* [7:0] Default:0x1 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_DCH_WEIGHT_DWLEN];
} __packed;

#define NBL_MCC_SPD_TIMEOUT_TH_ADDR  (0xb44740)
#define NBL_MCC_SPD_TIMEOUT_TH_DEPTH (1)
#define NBL_MCC_SPD_TIMEOUT_TH_WIDTH (32)
#define NBL_MCC_SPD_TIMEOUT_TH_DWLEN (1)
union mcc_spd_timeout_th_u {
	struct mcc_spd_timeout_th {
		u32 timeout_th:8;        /* [7:0] Default:0xff RW */
		u32 rsv:14;              /* [21:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_SPD_TIMEOUT_TH_DWLEN];
} __packed;

#define NBL_MCC_EXT_FLAG_OFFSET_ADDR  (0xb44800)
#define NBL_MCC_EXT_FLAG_OFFSET_DEPTH (1)
#define NBL_MCC_EXT_FLAG_OFFSET_WIDTH (32)
#define NBL_MCC_EXT_FLAG_OFFSET_DWLEN (1)
union mcc_ext_flag_offset_u {
	struct mcc_ext_flag_offset {
		u32 dir_offset:5;        /* [4:0] Default:0x00 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_EXT_FLAG_OFFSET_DWLEN];
} __packed;

#define NBL_MCC_EXT_MCIDX_ADDR  (0xb44804)
#define NBL_MCC_EXT_MCIDX_DEPTH (1)
#define NBL_MCC_EXT_MCIDX_WIDTH (32)
#define NBL_MCC_EXT_MCIDX_DWLEN (1)
union mcc_ext_mcidx_u {
	struct mcc_ext_mcidx {
		u32 mcidx_act_id:6;      /* [5:0] Default:0x0d RW */
		u32 mcidx_vld:1;         /* [6] Default:0x1 RW */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_EXT_MCIDX_DWLEN];
} __packed;

#define NBL_MCC_MC_ORIGINAL_DPORT_ADDR  (0xb44808)
#define NBL_MCC_MC_ORIGINAL_DPORT_DEPTH (1)
#define NBL_MCC_MC_ORIGINAL_DPORT_WIDTH (32)
#define NBL_MCC_MC_ORIGINAL_DPORT_DWLEN (1)
union mcc_mc_original_dport_u {
	struct mcc_mc_original_dport {
		u32 dport:16;            /* [15:0] Default:0x2fef RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_MC_ORIGINAL_DPORT_DWLEN];
} __packed;

#define NBL_MCC_AM_SET_FLAGS_ADDR  (0xb44900)
#define NBL_MCC_AM_SET_FLAGS_DEPTH (1)
#define NBL_MCC_AM_SET_FLAGS_WIDTH (32)
#define NBL_MCC_AM_SET_FLAGS_DWLEN (1)
union mcc_am_set_flags_u {
	struct mcc_am_set_flags {
		u32 set_flags:32;        /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_MCC_AM_SET_FLAGS_DWLEN];
} __packed;

#define NBL_MCC_AM_CLEAR_FLAGS_ADDR  (0xb44904)
#define NBL_MCC_AM_CLEAR_FLAGS_DEPTH (1)
#define NBL_MCC_AM_CLEAR_FLAGS_WIDTH (32)
#define NBL_MCC_AM_CLEAR_FLAGS_DWLEN (1)
union mcc_am_clear_flags_u {
	struct mcc_am_clear_flags {
		u32 clear_flags:32;      /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_MCC_AM_CLEAR_FLAGS_DWLEN];
} __packed;

#define NBL_MCC_AM_ACT_ID_ADDR  (0xb44a00)
#define NBL_MCC_AM_ACT_ID_DEPTH (1)
#define NBL_MCC_AM_ACT_ID_WIDTH (32)
#define NBL_MCC_AM_ACT_ID_DWLEN (1)
union mcc_am_act_id_u {
	struct mcc_am_act_id {
		u32 dport_act_id:6;      /* [5:0] Default:0x9 RW */
		u32 rsv3:2;              /* [7:6] Default:0x0 RO */
		u32 dqueue_act_id:6;     /* [13:8] Default:0xa RW */
		u32 rsv2:2;              /* [15:14] Default:0x0 RO */
		u32 statidx_act_id:6;    /* [21:16] Default:0x10 RW */
		u32 rsv1:2;              /* [23:22] Default:0x0 RO */
		u32 mirroridx_act_id:6;  /* [29:24] Default:0x08 RW */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_AM_ACT_ID_DWLEN];
} __packed;

#define NBL_MCC_QUEUE_EN_CTRL_ADDR  (0xb44b00)
#define NBL_MCC_QUEUE_EN_CTRL_DEPTH (1)
#define NBL_MCC_QUEUE_EN_CTRL_WIDTH (32)
#define NBL_MCC_QUEUE_EN_CTRL_DWLEN (1)
union mcc_queue_en_ctrl_u {
	struct mcc_queue_en_ctrl {
		u32 uuq_en:1;            /* [0] Default:0x1 RW */
		u32 duq_en:1;            /* [1] Default:0x1 RW */
		u32 umhq_en:1;           /* [2] Default:0x1 RW */
		u32 dmhq_en:1;           /* [3] Default:0x1 RW */
		u32 umlq_en:1;           /* [4] Default:0x1 RW */
		u32 dmlq_en:1;           /* [5] Default:0x1 RW */
		u32 uchq_en:1;           /* [6] Default:0x1 RW */
		u32 dchq_en:1;           /* [7] Default:0x1 RW */
		u32 uclq_en:1;           /* [8] Default:0x1 RW */
		u32 dclq_en:1;           /* [9] Default:0x1 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_QUEUE_EN_CTRL_DWLEN];
} __packed;

#define NBL_MCC_CFG_TEST_ADDR  (0xb44c00)
#define NBL_MCC_CFG_TEST_DEPTH (1)
#define NBL_MCC_CFG_TEST_WIDTH (32)
#define NBL_MCC_CFG_TEST_DWLEN (1)
union mcc_cfg_test_u {
	struct mcc_cfg_test {
		u32 test:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_MCC_CFG_TEST_DWLEN];
} __packed;

#define NBL_MCC_BP_STATE_ADDR  (0xb44f00)
#define NBL_MCC_BP_STATE_DEPTH (1)
#define NBL_MCC_BP_STATE_WIDTH (32)
#define NBL_MCC_BP_STATE_DWLEN (1)
union mcc_bp_state_u {
	struct mcc_bp_state {
		u32 in_bp:1;             /* [0] Default:0x0 RO */
		u32 out_bp:1;            /* [1] Default:0x0 RO */
		u32 inter_bp:1;          /* [2] Default:0x0 RO */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_BP_STATE_DWLEN];
} __packed;

#define NBL_MCC_BP_HISTORY_ADDR  (0xb44f04)
#define NBL_MCC_BP_HISTORY_DEPTH (1)
#define NBL_MCC_BP_HISTORY_WIDTH (32)
#define NBL_MCC_BP_HISTORY_DWLEN (1)
union mcc_bp_history_u {
	struct mcc_bp_history {
		u32 in_bp:1;             /* [0] Default:0x0 RC */
		u32 out_bp:1;            /* [1] Default:0x0 RC */
		u32 inter_bp:1;          /* [2] Default:0x0 RC */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_BP_HISTORY_DWLEN];
} __packed;

#define NBL_MCC_TBL_ADDR  (0xb54000)
#define NBL_MCC_TBL_DEPTH (8192)
#define NBL_MCC_TBL_WIDTH (64)
#define NBL_MCC_TBL_DWLEN (2)
union mcc_tbl_u {
	struct mcc_tbl {
		u32 dport_act:16;        /* [15:0] Default:0x0 RW */
		u32 dqueue_act:11;       /* [26:16] Default:0x0 RW */
		u32 dqueue_en:1;         /* [27] Default:0x0 RW */
		u32 dqueue_rsv:4;        /* [31:28] Default:0x0 RO */
		u32 statid_act:11;       /* [42:32] Default:0x0 RW */
		u32 statid_filter:1;     /* [43] Default:0x0 RW */
		u32 flowid_filter:1;     /* [44] Default:0x0 RW */
		u32 stateid_rsv:3;       /* [47:45] Default:0x0 RO */
		u32 next_pntr:13;        /* [60:48] Default:0x0 RW */
		u32 tail:1;              /* [61] Default:0x0 RW */
		u32 vld:1;               /* [62] Default:0x0 RW */
		u32 rsv:1;               /* [63] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MCC_TBL_DWLEN];
} __packed;
#define NBL_MCC_TBL_REG(r) (NBL_MCC_TBL_ADDR + \
		(NBL_MCC_TBL_DWLEN * 4) * (r))

#endif
