/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_DSTORE_H
#define NBL_DSTORE_H 1

#include <linux/types.h>

#define NBL_DSTORE_BASE (0x00704000)

#define NBL_DSTORE_INT_STATUS_ADDR  (0x704000)
#define NBL_DSTORE_INT_STATUS_DEPTH (1)
#define NBL_DSTORE_INT_STATUS_WIDTH (32)
#define NBL_DSTORE_INT_STATUS_DWLEN (1)
union dstore_int_status_u {
	struct dstore_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 parity_err:1;        /* [5] Default:0x0 RWC */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_INT_STATUS_DWLEN];
} __packed;

#define NBL_DSTORE_INT_MASK_ADDR  (0x704004)
#define NBL_DSTORE_INT_MASK_DEPTH (1)
#define NBL_DSTORE_INT_MASK_WIDTH (32)
#define NBL_DSTORE_INT_MASK_DWLEN (1)
union dstore_int_mask_u {
	struct dstore_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 parity_err:1;        /* [5] Default:0x0 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_INT_MASK_DWLEN];
} __packed;

#define NBL_DSTORE_INT_SET_ADDR  (0x704008)
#define NBL_DSTORE_INT_SET_DEPTH (0)
#define NBL_DSTORE_INT_SET_WIDTH (32)
#define NBL_DSTORE_INT_SET_DWLEN (1)
union dstore_int_set_u {
	struct dstore_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 parity_err:1;        /* [5] Default:0x0 WO */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_INT_SET_DWLEN];
} __packed;

#define NBL_DSTORE_COR_ERR_INFO_ADDR  (0x70400c)
#define NBL_DSTORE_COR_ERR_INFO_DEPTH (1)
#define NBL_DSTORE_COR_ERR_INFO_WIDTH (32)
#define NBL_DSTORE_COR_ERR_INFO_DWLEN (1)
union dstore_cor_err_info_u {
	struct dstore_cor_err_info {
		u32 ram_addr:10;         /* [9:0] Default:0x0 RO */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DSTORE_PARITY_ERR_INFO_ADDR  (0x704014)
#define NBL_DSTORE_PARITY_ERR_INFO_DEPTH (1)
#define NBL_DSTORE_PARITY_ERR_INFO_WIDTH (32)
#define NBL_DSTORE_PARITY_ERR_INFO_DWLEN (1)
union dstore_parity_err_info_u {
	struct dstore_parity_err_info {
		u32 ram_addr:10;         /* [9:0] Default:0x0 RO */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_DSTORE_CIF_ERR_INFO_ADDR  (0x70401c)
#define NBL_DSTORE_CIF_ERR_INFO_DEPTH (1)
#define NBL_DSTORE_CIF_ERR_INFO_WIDTH (32)
#define NBL_DSTORE_CIF_ERR_INFO_DWLEN (1)
union dstore_cif_err_info_u {
	struct dstore_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_DSTORE_CAR_CTRL_ADDR  (0x704100)
#define NBL_DSTORE_CAR_CTRL_DEPTH (1)
#define NBL_DSTORE_CAR_CTRL_WIDTH (32)
#define NBL_DSTORE_CAR_CTRL_DWLEN (1)
union dstore_car_ctrl_u {
	struct dstore_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_CAR_CTRL_DWLEN];
} __packed;

#define NBL_DSTORE_INIT_START_ADDR  (0x704104)
#define NBL_DSTORE_INIT_START_DEPTH (1)
#define NBL_DSTORE_INIT_START_WIDTH (32)
#define NBL_DSTORE_INIT_START_DWLEN (1)
union dstore_init_start_u {
	struct dstore_init_start {
		u32 init_start:1;        /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_INIT_START_DWLEN];
} __packed;

#define NBL_DSTORE_PKT_LEN_ADDR  (0x704108)
#define NBL_DSTORE_PKT_LEN_DEPTH (1)
#define NBL_DSTORE_PKT_LEN_WIDTH (32)
#define NBL_DSTORE_PKT_LEN_DWLEN (1)
union dstore_pkt_len_u {
	struct dstore_pkt_len {
		u32 min:7;               /* [6:0] Default:60 RW */
		u32 rsv1:8;              /* [14:7] Default:0x0 RO */
		u32 min_chk_en:1;        /* [15] Default:0x0 RW */
		u32 max:14;              /* [29:16] Default:9600 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 max_chk_en:1;        /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DSTORE_PKT_LEN_DWLEN];
} __packed;

#define NBL_DSTORE_SCH_PD_BUFFER_TH_ADDR  (0x704128)
#define NBL_DSTORE_SCH_PD_BUFFER_TH_DEPTH (1)
#define NBL_DSTORE_SCH_PD_BUFFER_TH_WIDTH (32)
#define NBL_DSTORE_SCH_PD_BUFFER_TH_DWLEN (1)
union dstore_sch_pd_buffer_th_u {
	struct dstore_sch_pd_buffer_th {
		u32 aful_th:9;           /* [8:0] Default:500 RW */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_SCH_PD_BUFFER_TH_DWLEN];
} __packed;

#define NBL_DSTORE_GLB_FC_TH_ADDR  (0x70412c)
#define NBL_DSTORE_GLB_FC_TH_DEPTH (1)
#define NBL_DSTORE_GLB_FC_TH_WIDTH (32)
#define NBL_DSTORE_GLB_FC_TH_DWLEN (1)
union dstore_glb_fc_th_u {
	struct dstore_glb_fc_th {
		u32 xoff_th:10;          /* [9:0] Default:900 RW */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 xon_th:10;           /* [25:16] Default:850 RW */
		u32 rsv:5;               /* [30:26] Default:0x0 RO */
		u32 fc_en:1;             /* [31:31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DSTORE_GLB_FC_TH_DWLEN];
} __packed;

#define NBL_DSTORE_GLB_DROP_TH_ADDR  (0x704130)
#define NBL_DSTORE_GLB_DROP_TH_DEPTH (1)
#define NBL_DSTORE_GLB_DROP_TH_WIDTH (32)
#define NBL_DSTORE_GLB_DROP_TH_DWLEN (1)
union dstore_glb_drop_th_u {
	struct dstore_glb_drop_th {
		u32 disc_th:10;          /* [9:0] Default:985 RW */
		u32 rsv:21;              /* [30:10] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DSTORE_GLB_DROP_TH_DWLEN];
} __packed;

#define NBL_DSTORE_PORT_FC_TH_ADDR  (0x704134)
#define NBL_DSTORE_PORT_FC_TH_DEPTH (6)
#define NBL_DSTORE_PORT_FC_TH_WIDTH (32)
#define NBL_DSTORE_PORT_FC_TH_DWLEN (1)
union dstore_port_fc_th_u {
	struct dstore_port_fc_th {
		u32 xoff_th:10;          /* [9:0] Default:400 RW */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 xon_th:10;           /* [25:16] Default:400 RW */
		u32 rsv:4;               /* [29:26] Default:0x0 RO */
		u32 fc_set:1;            /* [30:30] Default:0x0 RW */
		u32 fc_en:1;             /* [31:31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DSTORE_PORT_FC_TH_DWLEN];
} __packed;
#define NBL_DSTORE_PORT_FC_TH_REG(r) (NBL_DSTORE_PORT_FC_TH_ADDR + \
		(NBL_DSTORE_PORT_FC_TH_DWLEN * 4) * (r))

#define NBL_DSTORE_PORT_DROP_TH_ADDR  (0x704150)
#define NBL_DSTORE_PORT_DROP_TH_DEPTH (6)
#define NBL_DSTORE_PORT_DROP_TH_WIDTH (32)
#define NBL_DSTORE_PORT_DROP_TH_DWLEN (1)
union dstore_port_drop_th_u {
	struct dstore_port_drop_th {
		u32 disc_th:10;          /* [9:0] Default:800 RW */
		u32 rsv:21;              /* [30:10] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_DSTORE_PORT_DROP_TH_DWLEN];
} __packed;
#define NBL_DSTORE_PORT_DROP_TH_REG(r) (NBL_DSTORE_PORT_DROP_TH_ADDR + \
		(NBL_DSTORE_PORT_DROP_TH_DWLEN * 4) * (r))

#define NBL_DSTORE_CFG_TEST_ADDR  (0x704170)
#define NBL_DSTORE_CFG_TEST_DEPTH (1)
#define NBL_DSTORE_CFG_TEST_WIDTH (32)
#define NBL_DSTORE_CFG_TEST_DWLEN (1)
union dstore_cfg_test_u {
	struct dstore_cfg_test {
		u32 test:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DSTORE_CFG_TEST_DWLEN];
} __packed;

#define NBL_DSTORE_HIGH_PRI_PKT_ADDR  (0x70417c)
#define NBL_DSTORE_HIGH_PRI_PKT_DEPTH (1)
#define NBL_DSTORE_HIGH_PRI_PKT_WIDTH (32)
#define NBL_DSTORE_HIGH_PRI_PKT_DWLEN (1)
union dstore_high_pri_pkt_u {
	struct dstore_high_pri_pkt {
		u32 en:1;                /* [0:0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_HIGH_PRI_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_COS_FC_TH_ADDR  (0x704200)
#define NBL_DSTORE_COS_FC_TH_DEPTH (48)
#define NBL_DSTORE_COS_FC_TH_WIDTH (32)
#define NBL_DSTORE_COS_FC_TH_DWLEN (1)
union dstore_cos_fc_th_u {
	struct dstore_cos_fc_th {
		u32 xoff_th:10;          /* [9:0] Default:100 RW */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 xon_th:10;           /* [25:16] Default:100 RW */
		u32 rsv:4;               /* [29:26] Default:0x0 RO */
		u32 fc_set:1;            /* [30:30] Default:0x0 RW */
		u32 fc_en:1;             /* [31:31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DSTORE_COS_FC_TH_DWLEN];
} __packed;
#define NBL_DSTORE_COS_FC_TH_REG(r) (NBL_DSTORE_COS_FC_TH_ADDR + \
		(NBL_DSTORE_COS_FC_TH_DWLEN * 4) * (r))

#define NBL_DSTORE_COS_DROP_TH_ADDR  (0x704300)
#define NBL_DSTORE_COS_DROP_TH_DEPTH (48)
#define NBL_DSTORE_COS_DROP_TH_WIDTH (32)
#define NBL_DSTORE_COS_DROP_TH_DWLEN (1)
union dstore_cos_drop_th_u {
	struct dstore_cos_drop_th {
		u32 disc_th:10;          /* [9:0] Default:120 RW */
		u32 rsv:21;              /* [30:10] Default:0x0 RO */
		u32 en:1;                /* [31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DSTORE_COS_DROP_TH_DWLEN];
} __packed;
#define NBL_DSTORE_COS_DROP_TH_REG(r) (NBL_DSTORE_COS_DROP_TH_ADDR + \
		(NBL_DSTORE_COS_DROP_TH_DWLEN * 4) * (r))

#define NBL_DSTORE_SCH_PD_WRR_WGT_ADDR  (0x704400)
#define NBL_DSTORE_SCH_PD_WRR_WGT_DEPTH (36)
#define NBL_DSTORE_SCH_PD_WRR_WGT_WIDTH (32)
#define NBL_DSTORE_SCH_PD_WRR_WGT_DWLEN (1)
union dstore_sch_pd_wrr_wgt_u {
	struct dstore_sch_pd_wrr_wgt {
		u32 wgt_cos:4;           /* [3:0] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_SCH_PD_WRR_WGT_DWLEN];
} __packed;
#define NBL_DSTORE_SCH_PD_WRR_WGT_REG(r) (NBL_DSTORE_SCH_PD_WRR_WGT_ADDR + \
		(NBL_DSTORE_SCH_PD_WRR_WGT_DWLEN * 4) * (r))

#define NBL_DSTORE_COS7_FORCE_ADDR  (0x704504)
#define NBL_DSTORE_COS7_FORCE_DEPTH (1)
#define NBL_DSTORE_COS7_FORCE_WIDTH (32)
#define NBL_DSTORE_COS7_FORCE_DWLEN (1)
union dstore_cos7_force_u {
	struct dstore_cos7_force {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_COS7_FORCE_DWLEN];
} __packed;

#define NBL_DSTORE_D_DPORT_FC_TH_ADDR  (0x704600)
#define NBL_DSTORE_D_DPORT_FC_TH_DEPTH (5)
#define NBL_DSTORE_D_DPORT_FC_TH_WIDTH (32)
#define NBL_DSTORE_D_DPORT_FC_TH_DWLEN (1)
union dstore_d_dport_fc_th_u {
	struct dstore_d_dport_fc_th {
		u32 xoff_th:11;          /* [10:0] Default:200 RW */
		u32 rsv1:5;              /* [15:11] Default:0x0 RO */
		u32 xon_th:11;           /* [26:16] Default:100 RW */
		u32 rsv:3;               /* [29:27] Default:0x0 RO */
		u32 fc_set:1;            /* [30:30] Default:0x0 RW */
		u32 fc_en:1;             /* [31:31] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DSTORE_D_DPORT_FC_TH_DWLEN];
} __packed;
#define NBL_DSTORE_D_DPORT_FC_TH_REG(r) (NBL_DSTORE_D_DPORT_FC_TH_ADDR + \
		(NBL_DSTORE_D_DPORT_FC_TH_DWLEN * 4) * (r))

#define NBL_DSTORE_INIT_DONE_ADDR  (0x704800)
#define NBL_DSTORE_INIT_DONE_DEPTH (1)
#define NBL_DSTORE_INIT_DONE_WIDTH (32)
#define NBL_DSTORE_INIT_DONE_DWLEN (1)
union dstore_init_done_u {
	struct dstore_init_done {
		u32 done:1;              /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_INIT_DONE_DWLEN];
} __packed;

#define NBL_DSTORE_SCH_IDLE_LIST_STATUS_CURR_ADDR  (0x70481c)
#define NBL_DSTORE_SCH_IDLE_LIST_STATUS_CURR_DEPTH (1)
#define NBL_DSTORE_SCH_IDLE_LIST_STATUS_CURR_WIDTH (32)
#define NBL_DSTORE_SCH_IDLE_LIST_STATUS_CURR_DWLEN (1)
union dstore_sch_idle_list_status_curr_u {
	struct dstore_sch_idle_list_status_curr {
		u32 empt:1;              /* [0] Default:0x0 RO */
		u32 full:1;              /* [1] Default:0x1 RO */
		u32 cnt:10;              /* [11:2] Default:0x200 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_SCH_IDLE_LIST_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DSTORE_SCH_QUE_LIST_STATUS_ADDR  (0x704820)
#define NBL_DSTORE_SCH_QUE_LIST_STATUS_DEPTH (48)
#define NBL_DSTORE_SCH_QUE_LIST_STATUS_WIDTH (32)
#define NBL_DSTORE_SCH_QUE_LIST_STATUS_DWLEN (1)
union dstore_sch_que_list_status_u {
	struct dstore_sch_que_list_status {
		u32 curr_empt:1;         /* [0] Default:0x1 RO */
		u32 curr_cnt:10;         /* [10:1] Default:0x0 RO */
		u32 history_udf:1;       /* [11] Default:0x0 RC */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_SCH_QUE_LIST_STATUS_DWLEN];
} __packed;
#define NBL_DSTORE_SCH_QUE_LIST_STATUS_REG(r) (NBL_DSTORE_SCH_QUE_LIST_STATUS_ADDR + \
		(NBL_DSTORE_SCH_QUE_LIST_STATUS_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_TOTAL_PKT_ADDR  (0x705050)
#define NBL_DSTORE_RCV_TOTAL_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_PKT_DWLEN (1)
union dstore_rcv_total_pkt_u {
	struct dstore_rcv_total_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_BYTE_ADDR  (0x705054)
#define NBL_DSTORE_RCV_TOTAL_BYTE_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_BYTE_WIDTH (48)
#define NBL_DSTORE_RCV_TOTAL_BYTE_DWLEN (2)
union dstore_rcv_total_byte_u {
	struct dstore_rcv_total_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_BYTE_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_RIGHT_PKT_ADDR  (0x70505c)
#define NBL_DSTORE_RCV_TOTAL_RIGHT_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_RIGHT_PKT_DWLEN (1)
union dstore_rcv_total_right_pkt_u {
	struct dstore_rcv_total_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_RIGHT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_WRONG_PKT_ADDR  (0x705060)
#define NBL_DSTORE_RCV_TOTAL_WRONG_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_WRONG_PKT_DWLEN (1)
union dstore_rcv_total_wrong_pkt_u {
	struct dstore_rcv_total_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_WRONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_FWD_RIGHT_PKT_ADDR  (0x705064)
#define NBL_DSTORE_RCV_FWD_RIGHT_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_FWD_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_FWD_RIGHT_PKT_DWLEN (1)
union dstore_rcv_fwd_right_pkt_u {
	struct dstore_rcv_fwd_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_FWD_RIGHT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_FWD_WRONG_PKT_ADDR  (0x705068)
#define NBL_DSTORE_RCV_FWD_WRONG_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_FWD_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_FWD_WRONG_PKT_DWLEN (1)
union dstore_rcv_fwd_wrong_pkt_u {
	struct dstore_rcv_fwd_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_FWD_WRONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_HERR_RIGHT_PKT_ADDR  (0x70506c)
#define NBL_DSTORE_RCV_HERR_RIGHT_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_HERR_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_HERR_RIGHT_PKT_DWLEN (1)
union dstore_rcv_herr_right_pkt_u {
	struct dstore_rcv_herr_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_HERR_RIGHT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_HERR_WRONG_PKT_ADDR  (0x705070)
#define NBL_DSTORE_RCV_HERR_WRONG_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_HERR_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_HERR_WRONG_PKT_DWLEN (1)
union dstore_rcv_herr_wrong_pkt_u {
	struct dstore_rcv_herr_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_HERR_WRONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_TOTAL_PKT_ADDR  (0x705074)
#define NBL_DSTORE_IPRO_TOTAL_PKT_DEPTH (1)
#define NBL_DSTORE_IPRO_TOTAL_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_TOTAL_PKT_DWLEN (1)
union dstore_ipro_total_pkt_u {
	struct dstore_ipro_total_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_TOTAL_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_TOTAL_BYTE_ADDR  (0x705078)
#define NBL_DSTORE_IPRO_TOTAL_BYTE_DEPTH (1)
#define NBL_DSTORE_IPRO_TOTAL_BYTE_WIDTH (48)
#define NBL_DSTORE_IPRO_TOTAL_BYTE_DWLEN (2)
union dstore_ipro_total_byte_u {
	struct dstore_ipro_total_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_TOTAL_BYTE_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_FWD_RIGHT_PKT_ADDR  (0x705080)
#define NBL_DSTORE_IPRO_FWD_RIGHT_PKT_DEPTH (1)
#define NBL_DSTORE_IPRO_FWD_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_FWD_RIGHT_PKT_DWLEN (1)
union dstore_ipro_fwd_right_pkt_u {
	struct dstore_ipro_fwd_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_FWD_RIGHT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_FWD_WRONG_PKT_ADDR  (0x705084)
#define NBL_DSTORE_IPRO_FWD_WRONG_PKT_DEPTH (1)
#define NBL_DSTORE_IPRO_FWD_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_FWD_WRONG_PKT_DWLEN (1)
union dstore_ipro_fwd_wrong_pkt_u {
	struct dstore_ipro_fwd_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_FWD_WRONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_HERR_RIGHT_PKT_ADDR  (0x705088)
#define NBL_DSTORE_IPRO_HERR_RIGHT_PKT_DEPTH (1)
#define NBL_DSTORE_IPRO_HERR_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_HERR_RIGHT_PKT_DWLEN (1)
union dstore_ipro_herr_right_pkt_u {
	struct dstore_ipro_herr_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_HERR_RIGHT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_IPRO_HERR_WRONG_PKT_ADDR  (0x70508c)
#define NBL_DSTORE_IPRO_HERR_WRONG_PKT_DEPTH (1)
#define NBL_DSTORE_IPRO_HERR_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_HERR_WRONG_PKT_DWLEN (1)
union dstore_ipro_herr_wrong_pkt_u {
	struct dstore_ipro_herr_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_HERR_WRONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_PMEM_TOTAL_PKT_ADDR  (0x705090)
#define NBL_DSTORE_PMEM_TOTAL_PKT_DEPTH (1)
#define NBL_DSTORE_PMEM_TOTAL_PKT_WIDTH (32)
#define NBL_DSTORE_PMEM_TOTAL_PKT_DWLEN (1)
union dstore_pmem_total_pkt_u {
	struct dstore_pmem_total_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_PMEM_TOTAL_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_PMEM_TOTAL_BYTE_ADDR  (0x705094)
#define NBL_DSTORE_PMEM_TOTAL_BYTE_DEPTH (1)
#define NBL_DSTORE_PMEM_TOTAL_BYTE_WIDTH (48)
#define NBL_DSTORE_PMEM_TOTAL_BYTE_DWLEN (2)
union dstore_pmem_total_byte_u {
	struct dstore_pmem_total_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_PMEM_TOTAL_BYTE_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_ERR_DROP_PKT_ADDR  (0x70509c)
#define NBL_DSTORE_RCV_TOTAL_ERR_DROP_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_ERR_DROP_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_ERR_DROP_PKT_DWLEN (1)
union dstore_rcv_total_err_drop_pkt_u {
	struct dstore_rcv_total_err_drop_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_ERR_DROP_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_SHORT_PKT_ADDR  (0x7050a0)
#define NBL_DSTORE_RCV_TOTAL_SHORT_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_SHORT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_SHORT_PKT_DWLEN (1)
union dstore_rcv_total_short_pkt_u {
	struct dstore_rcv_total_short_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_SHORT_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_TOTAL_LONG_PKT_ADDR  (0x7050a4)
#define NBL_DSTORE_RCV_TOTAL_LONG_PKT_DEPTH (1)
#define NBL_DSTORE_RCV_TOTAL_LONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_TOTAL_LONG_PKT_DWLEN (1)
union dstore_rcv_total_long_pkt_u {
	struct dstore_rcv_total_long_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_TOTAL_LONG_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_BUF_TOTAL_DROP_PKT_ADDR  (0x7050a8)
#define NBL_DSTORE_BUF_TOTAL_DROP_PKT_DEPTH (1)
#define NBL_DSTORE_BUF_TOTAL_DROP_PKT_WIDTH (32)
#define NBL_DSTORE_BUF_TOTAL_DROP_PKT_DWLEN (1)
union dstore_buf_total_drop_pkt_u {
	struct dstore_buf_total_drop_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_BUF_TOTAL_DROP_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_BUF_TOTAL_TRUN_PKT_ADDR  (0x7050ac)
#define NBL_DSTORE_BUF_TOTAL_TRUN_PKT_DEPTH (1)
#define NBL_DSTORE_BUF_TOTAL_TRUN_PKT_WIDTH (32)
#define NBL_DSTORE_BUF_TOTAL_TRUN_PKT_DWLEN (1)
union dstore_buf_total_trun_pkt_u {
	struct dstore_buf_total_trun_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_BUF_TOTAL_TRUN_PKT_DWLEN];
} __packed;

#define NBL_DSTORE_RCV_PORT_PKT_ADDR  (0x706000)
#define NBL_DSTORE_RCV_PORT_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_PKT_DWLEN (1)
union dstore_rcv_port_pkt_u {
	struct dstore_rcv_port_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_PKT_REG(r) (NBL_DSTORE_RCV_PORT_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_BYTE_ADDR  (0x706040)
#define NBL_DSTORE_RCV_PORT_BYTE_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_BYTE_WIDTH (48)
#define NBL_DSTORE_RCV_PORT_BYTE_DWLEN (2)
union dstore_rcv_port_byte_u {
	struct dstore_rcv_port_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_BYTE_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_BYTE_REG(r) (NBL_DSTORE_RCV_PORT_BYTE_ADDR + \
		(NBL_DSTORE_RCV_PORT_BYTE_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_ADDR  (0x7060c0)
#define NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_DWLEN (1)
union dstore_rcv_port_total_right_pkt_u {
	struct dstore_rcv_port_total_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_REG(r) (NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_TOTAL_RIGHT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_ADDR  (0x706100)
#define NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_DWLEN (1)
union dstore_rcv_port_total_wrong_pkt_u {
	struct dstore_rcv_port_total_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_REG(r) (NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_TOTAL_WRONG_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_ADDR  (0x706140)
#define NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_DWLEN (1)
union dstore_rcv_port_fwd_right_pkt_u {
	struct dstore_rcv_port_fwd_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_REG(r) (NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_FWD_RIGHT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_ADDR  (0x706180)
#define NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_DWLEN (1)
union dstore_rcv_port_fwd_wrong_pkt_u {
	struct dstore_rcv_port_fwd_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_REG(r) (NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_FWD_WRONG_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_ADDR  (0x7061c0)
#define NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_DWLEN (1)
union dstore_rcv_port_herr_right_pkt_u {
	struct dstore_rcv_port_herr_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_REG(r) (NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_HERR_RIGHT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_ADDR  (0x706200)
#define NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_DWLEN (1)
union dstore_rcv_port_herr_wrong_pkt_u {
	struct dstore_rcv_port_herr_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_REG(r) (NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_HERR_WRONG_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_IPRO_PORT_PKT_ADDR  (0x706240)
#define NBL_DSTORE_IPRO_PORT_PKT_DEPTH (12)
#define NBL_DSTORE_IPRO_PORT_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_PORT_PKT_DWLEN (1)
union dstore_ipro_port_pkt_u {
	struct dstore_ipro_port_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_PORT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_IPRO_PORT_PKT_REG(r) (NBL_DSTORE_IPRO_PORT_PKT_ADDR + \
		(NBL_DSTORE_IPRO_PORT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_IPRO_PORT_BYTE_ADDR  (0x706280)
#define NBL_DSTORE_IPRO_PORT_BYTE_DEPTH (12)
#define NBL_DSTORE_IPRO_PORT_BYTE_WIDTH (48)
#define NBL_DSTORE_IPRO_PORT_BYTE_DWLEN (2)
union dstore_ipro_port_byte_u {
	struct dstore_ipro_port_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_PORT_BYTE_DWLEN];
} __packed;
#define NBL_DSTORE_IPRO_PORT_BYTE_REG(r) (NBL_DSTORE_IPRO_PORT_BYTE_ADDR + \
		(NBL_DSTORE_IPRO_PORT_BYTE_DWLEN * 4) * (r))

#define NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_ADDR  (0x706300)
#define NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_DEPTH (12)
#define NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_DWLEN (1)
union dstore_ipro_port_fwd_right_pkt_u {
	struct dstore_ipro_port_fwd_right_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_REG(r) (NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_ADDR + \
		(NBL_DSTORE_IPRO_PORT_FWD_RIGHT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_ADDR  (0x706340)
#define NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_DEPTH (12)
#define NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_WIDTH (32)
#define NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_DWLEN (1)
union dstore_ipro_port_fwd_wrong_pkt_u {
	struct dstore_ipro_port_fwd_wrong_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_REG(r) (NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_ADDR + \
		(NBL_DSTORE_IPRO_PORT_FWD_WRONG_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_PMEM_PORT_PKT_ADDR  (0x706380)
#define NBL_DSTORE_PMEM_PORT_PKT_DEPTH (12)
#define NBL_DSTORE_PMEM_PORT_PKT_WIDTH (32)
#define NBL_DSTORE_PMEM_PORT_PKT_DWLEN (1)
union dstore_pmem_port_pkt_u {
	struct dstore_pmem_port_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_PMEM_PORT_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_PMEM_PORT_PKT_REG(r) (NBL_DSTORE_PMEM_PORT_PKT_ADDR + \
		(NBL_DSTORE_PMEM_PORT_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_PMEM_PORT_BYTE_ADDR  (0x7063c0)
#define NBL_DSTORE_PMEM_PORT_BYTE_DEPTH (12)
#define NBL_DSTORE_PMEM_PORT_BYTE_WIDTH (48)
#define NBL_DSTORE_PMEM_PORT_BYTE_DWLEN (2)
union dstore_pmem_port_byte_u {
	struct dstore_pmem_port_byte {
		u32 cnt_l:32;            /* [47:0] Default:0x0 RCTR */
		u32 cnt_h:16;            /* [47:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DSTORE_PMEM_PORT_BYTE_DWLEN];
} __packed;
#define NBL_DSTORE_PMEM_PORT_BYTE_REG(r) (NBL_DSTORE_PMEM_PORT_BYTE_ADDR + \
		(NBL_DSTORE_PMEM_PORT_BYTE_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_ADDR  (0x706440)
#define NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_DWLEN (1)
union dstore_rcv_err_port_drop_pkt_u {
	struct dstore_rcv_err_port_drop_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_REG(r) (NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_ADDR + \
		(NBL_DSTORE_RCV_ERR_PORT_DROP_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_ADDR  (0x706480)
#define NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_DWLEN (1)
union dstore_rcv_port_short_drop_pkt_u {
	struct dstore_rcv_port_short_drop_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_REG(r) (NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_SHORT_DROP_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_RCV_PORT_LONG_PKT_ADDR  (0x7064c0)
#define NBL_DSTORE_RCV_PORT_LONG_PKT_DEPTH (12)
#define NBL_DSTORE_RCV_PORT_LONG_PKT_WIDTH (32)
#define NBL_DSTORE_RCV_PORT_LONG_PKT_DWLEN (1)
union dstore_rcv_port_long_pkt_u {
	struct dstore_rcv_port_long_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_RCV_PORT_LONG_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_RCV_PORT_LONG_PKT_REG(r) (NBL_DSTORE_RCV_PORT_LONG_PKT_ADDR + \
		(NBL_DSTORE_RCV_PORT_LONG_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_BUF_PORT_DROP_PKT_ADDR  (0x706500)
#define NBL_DSTORE_BUF_PORT_DROP_PKT_DEPTH (12)
#define NBL_DSTORE_BUF_PORT_DROP_PKT_WIDTH (32)
#define NBL_DSTORE_BUF_PORT_DROP_PKT_DWLEN (1)
union dstore_buf_port_drop_pkt_u {
	struct dstore_buf_port_drop_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_BUF_PORT_DROP_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_BUF_PORT_DROP_PKT_REG(r) (NBL_DSTORE_BUF_PORT_DROP_PKT_ADDR + \
		(NBL_DSTORE_BUF_PORT_DROP_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_BUF_PORT_TRUN_PKT_ADDR  (0x706540)
#define NBL_DSTORE_BUF_PORT_TRUN_PKT_DEPTH (12)
#define NBL_DSTORE_BUF_PORT_TRUN_PKT_WIDTH (32)
#define NBL_DSTORE_BUF_PORT_TRUN_PKT_DWLEN (1)
union dstore_buf_port_trun_pkt_u {
	struct dstore_buf_port_trun_pkt {
		u32 cnt:32;              /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DSTORE_BUF_PORT_TRUN_PKT_DWLEN];
} __packed;
#define NBL_DSTORE_BUF_PORT_TRUN_PKT_REG(r) (NBL_DSTORE_BUF_PORT_TRUN_PKT_ADDR + \
		(NBL_DSTORE_BUF_PORT_TRUN_PKT_DWLEN * 4) * (r))

#define NBL_DSTORE_BP_CUR_1ST_ADDR  (0x706580)
#define NBL_DSTORE_BP_CUR_1ST_DEPTH (1)
#define NBL_DSTORE_BP_CUR_1ST_WIDTH (32)
#define NBL_DSTORE_BP_CUR_1ST_DWLEN (1)
union dstore_bp_cur_1st_u {
	struct dstore_bp_cur_1st {
		u32 link_fc:6;           /* [5:0] Default:0x0 RO */
		u32 rsv:2;               /* [7:6] Default:0x0 RO */
		u32 pfc:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_BP_CUR_1ST_DWLEN];
} __packed;

#define NBL_DSTORE_BP_CUR_2ND_ADDR  (0x706584)
#define NBL_DSTORE_BP_CUR_2ND_DEPTH (1)
#define NBL_DSTORE_BP_CUR_2ND_WIDTH (32)
#define NBL_DSTORE_BP_CUR_2ND_DWLEN (1)
union dstore_bp_cur_2nd_u {
	struct dstore_bp_cur_2nd {
		u32 pfc:24;              /* [23:0] Default:0x0 RO */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_BP_CUR_2ND_DWLEN];
} __packed;

#define NBL_DSTORE_BP_HISTORY_LINK_ADDR  (0x706590)
#define NBL_DSTORE_BP_HISTORY_LINK_DEPTH (6)
#define NBL_DSTORE_BP_HISTORY_LINK_WIDTH (32)
#define NBL_DSTORE_BP_HISTORY_LINK_DWLEN (1)
union dstore_bp_history_link_u {
	struct dstore_bp_history_link {
		u32 fc:1;                /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_BP_HISTORY_LINK_DWLEN];
} __packed;
#define NBL_DSTORE_BP_HISTORY_LINK_REG(r) (NBL_DSTORE_BP_HISTORY_LINK_ADDR + \
		(NBL_DSTORE_BP_HISTORY_LINK_DWLEN * 4) * (r))

#define NBL_DSTORE_BP_HISTORY_ADDR  (0x7065b0)
#define NBL_DSTORE_BP_HISTORY_DEPTH (48)
#define NBL_DSTORE_BP_HISTORY_WIDTH (32)
#define NBL_DSTORE_BP_HISTORY_DWLEN (1)
union dstore_bp_history_u {
	struct dstore_bp_history {
		u32 pfc:1;               /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_BP_HISTORY_DWLEN];
} __packed;
#define NBL_DSTORE_BP_HISTORY_REG(r) (NBL_DSTORE_BP_HISTORY_ADDR + \
		(NBL_DSTORE_BP_HISTORY_DWLEN * 4) * (r))

#define NBL_DSTORE_WRR_CUR_ADDR  (0x706800)
#define NBL_DSTORE_WRR_CUR_DEPTH (36)
#define NBL_DSTORE_WRR_CUR_WIDTH (32)
#define NBL_DSTORE_WRR_CUR_DWLEN (1)
union dstore_wrr_cur_u {
	struct dstore_wrr_cur {
		u32 wgt_cos:5;           /* [4:0] Default:0x0 RO */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_WRR_CUR_DWLEN];
} __packed;
#define NBL_DSTORE_WRR_CUR_REG(r) (NBL_DSTORE_WRR_CUR_ADDR + \
		(NBL_DSTORE_WRR_CUR_DWLEN * 4) * (r))

#define NBL_DSTORE_DDPORT_CUR_ADDR  (0x707018)
#define NBL_DSTORE_DDPORT_CUR_DEPTH (1)
#define NBL_DSTORE_DDPORT_CUR_WIDTH (32)
#define NBL_DSTORE_DDPORT_CUR_DWLEN (1)
union dstore_ddport_cur_u {
	struct dstore_ddport_cur {
		u32 link_fc:5;           /* [4:0] Default:0x0 RO */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_DDPORT_CUR_DWLEN];
} __packed;

#define NBL_DSTORE_DDPORT_HISTORY_ADDR  (0x70701c)
#define NBL_DSTORE_DDPORT_HISTORY_DEPTH (5)
#define NBL_DSTORE_DDPORT_HISTORY_WIDTH (32)
#define NBL_DSTORE_DDPORT_HISTORY_DWLEN (1)
union dstore_ddport_history_u {
	struct dstore_ddport_history {
		u32 link_fc:1;           /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_DDPORT_HISTORY_DWLEN];
} __packed;
#define NBL_DSTORE_DDPORT_HISTORY_REG(r) (NBL_DSTORE_DDPORT_HISTORY_ADDR + \
		(NBL_DSTORE_DDPORT_HISTORY_DWLEN * 4) * (r))

#define NBL_DSTORE_DDPORT_RSC_ADD_ADDR  (0x707050)
#define NBL_DSTORE_DDPORT_RSC_ADD_DEPTH (5)
#define NBL_DSTORE_DDPORT_RSC_ADD_WIDTH (32)
#define NBL_DSTORE_DDPORT_RSC_ADD_DWLEN (1)
union dstore_ddport_rsc_add_u {
	struct dstore_ddport_rsc_add {
		u32 cnt:12;              /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DSTORE_DDPORT_RSC_ADD_DWLEN];
} __packed;
#define NBL_DSTORE_DDPORT_RSC_ADD_REG(r) (NBL_DSTORE_DDPORT_RSC_ADD_ADDR + \
		(NBL_DSTORE_DDPORT_RSC_ADD_DWLEN * 4) * (r))

#endif
