/* SPDX-License-Identifier: GPL-2.0*/
/*
 * Copyright (c) 2022 nebula-matrix Limited.
 * Author:
 */
// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_VDPA_H
#define NBL_VDPA_H 1

#include <linux/types.h>

#define NBL_VDPA_BASE (0x00F98000)

#define NBL_VDPA_INT_STATUS_ADDR  (0xf98000)
#define NBL_VDPA_INT_STATUS_DEPTH (1)
#define NBL_VDPA_INT_STATUS_WIDTH (32)
#define NBL_VDPA_INT_STATUS_DWLEN (1)
union vdpa_int_status_u {
	struct vdpa_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 RWC */
		u32 cif_err:1;           /* [05:05] Default:0x0 RWC */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_INT_STATUS_DWLEN];
} __packed;

#define NBL_VDPA_INT_MASK_ADDR  (0xf98004)
#define NBL_VDPA_INT_MASK_DEPTH (1)
#define NBL_VDPA_INT_MASK_WIDTH (32)
#define NBL_VDPA_INT_MASK_DWLEN (1)
union vdpa_int_mask_u {
	struct vdpa_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 RW */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 RW */
		u32 cif_err:1;           /* [05:05] Default:0x0 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_INT_MASK_DWLEN];
} __packed;

#define NBL_VDPA_INT_SET_ADDR  (0xf98008)
#define NBL_VDPA_INT_SET_DEPTH (1)
#define NBL_VDPA_INT_SET_WIDTH (32)
#define NBL_VDPA_INT_SET_DWLEN (1)
union vdpa_int_set_u {
	struct vdpa_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 WO */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 WO */
		u32 cif_err:1;           /* [05:05] Default:0x0 WO */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_INT_SET_DWLEN];
} __packed;

#define NBL_VDPA_INIT_DONE_ADDR  (0xf9800c)
#define NBL_VDPA_INIT_DONE_DEPTH (1)
#define NBL_VDPA_INIT_DONE_WIDTH (32)
#define NBL_VDPA_INIT_DONE_DWLEN (1)
union vdpa_init_done_u {
	struct vdpa_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_INIT_DONE_DWLEN];
} __packed;

#define NBL_VDPA_CAR_CTRL_ADDR  (0xf98058)
#define NBL_VDPA_CAR_CTRL_DEPTH (1)
#define NBL_VDPA_CAR_CTRL_WIDTH (32)
#define NBL_VDPA_CAR_CTRL_DWLEN (1)
union vdpa_car_ctrl_u {
	struct vdpa_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_CAR_CTRL_DWLEN];
} __packed;

#define NBL_VDPA_FLOW_EN_ADDR  (0xf9805c)
#define NBL_VDPA_FLOW_EN_DEPTH (1)
#define NBL_VDPA_FLOW_EN_WIDTH (32)
#define NBL_VDPA_FLOW_EN_DWLEN (1)
union vdpa_flow_en_u {
	struct vdpa_flow_en {
		u32 ivdpa_cnt_en:1;      /* [00:00] Default:0x1 RW */
		u32 ovdpa_cnt_en:1;      /* [01:01] Default:0x1 RW */
		u32 vdpa_drop_cnt_en:1;  /* [02:02] Default:0x1 RW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_FLOW_EN_DWLEN];
} __packed;

#define NBL_VDPA_CIF_ERR_INFO_ADDR  (0xf98060)
#define NBL_VDPA_CIF_ERR_INFO_DEPTH (1)
#define NBL_VDPA_CIF_ERR_INFO_WIDTH (32)
#define NBL_VDPA_CIF_ERR_INFO_DWLEN (1)
union vdpa_cif_err_info_u {
	struct vdpa_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_VDPA_EN_ADDR  (0xf98100)
#define NBL_VDPA_EN_DEPTH (1)
#define NBL_VDPA_EN_WIDTH (32)
#define NBL_VDPA_EN_DWLEN (1)
union vdpa_en_u {
	struct vdpa_en {
		u32 vdpa_en:1;           /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_EN_DWLEN];
} __packed;

#define NBL_VDPA_RING_BASE_ADDR_L_ADDR  (0xf98104)
#define NBL_VDPA_RING_BASE_ADDR_L_DEPTH (1)
#define NBL_VDPA_RING_BASE_ADDR_L_WIDTH (32)
#define NBL_VDPA_RING_BASE_ADDR_L_DWLEN (1)
union vdpa_ring_base_addr_l_u {
	struct vdpa_ring_base_addr_l {
		u32 base_addr_l:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_VDPA_RING_BASE_ADDR_L_DWLEN];
} __packed;

#define NBL_VDPA_RING_BASE_ADDR_H_ADDR  (0xf98108)
#define NBL_VDPA_RING_BASE_ADDR_H_DEPTH (1)
#define NBL_VDPA_RING_BASE_ADDR_H_WIDTH (32)
#define NBL_VDPA_RING_BASE_ADDR_H_DWLEN (1)
union vdpa_ring_base_addr_h_u {
	struct vdpa_ring_base_addr_h {
		u32 base_addr_h:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_VDPA_RING_BASE_ADDR_H_DWLEN];
} __packed;

#define NBL_VDPA_RING_SIZE_MASK_ADDR  (0xf9810c)
#define NBL_VDPA_RING_SIZE_MASK_DEPTH (1)
#define NBL_VDPA_RING_SIZE_MASK_WIDTH (32)
#define NBL_VDPA_RING_SIZE_MASK_DWLEN (1)
union vdpa_ring_size_mask_u {
	struct vdpa_ring_size_mask {
		u32 size_mask:16;        /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_RING_SIZE_MASK_DWLEN];
} __packed;

#define NBL_VDPA_RING_TPNTR_ADDR  (0xf98110)
#define NBL_VDPA_RING_TPNTR_DEPTH (1)
#define NBL_VDPA_RING_TPNTR_WIDTH (32)
#define NBL_VDPA_RING_TPNTR_DWLEN (1)
union vdpa_ring_tpntr_u {
	struct vdpa_ring_tpntr {
		u32 tpntr:16;            /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_RING_TPNTR_DWLEN];
} __packed;

#define NBL_VDPA_RING_HPNTR_ADDR  (0xf98114)
#define NBL_VDPA_RING_HPNTR_DEPTH (1)
#define NBL_VDPA_RING_HPNTR_WIDTH (32)
#define NBL_VDPA_RING_HPNTR_DWLEN (1)
union vdpa_ring_hpntr_u {
	struct vdpa_ring_hpntr {
		u32 hpntr:16;            /* [15:00] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_RING_HPNTR_DWLEN];
} __packed;

#define NBL_VDPA_RING_HPNTR_RST_ADDR  (0xf98118)
#define NBL_VDPA_RING_HPNTR_RST_DEPTH (1)
#define NBL_VDPA_RING_HPNTR_RST_WIDTH (32)
#define NBL_VDPA_RING_HPNTR_RST_DWLEN (1)
union vdpa_ring_hpntr_rst_u {
	struct vdpa_ring_hpntr_rst {
		u32 hpntr_rst:1;         /* [00:00] Default:0x0 WO */
		u32 rdy:1;               /* [01:01] Default:0x1 RO */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_RING_HPNTR_RST_DWLEN];
} __packed;

#define NBL_VDPA_BURST_LEN_ADDR  (0xf9811c)
#define NBL_VDPA_BURST_LEN_DEPTH (1)
#define NBL_VDPA_BURST_LEN_WIDTH (32)
#define NBL_VDPA_BURST_LEN_DWLEN (1)
union vdpa_burst_len_u {
	struct vdpa_burst_len {
		u32 burst_len:6;         /* [05:00] Default:0x10 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_BURST_LEN_DWLEN];
} __packed;

#define NBL_VDPA_TIMEOUT_VALUE_ADDR  (0xf98120)
#define NBL_VDPA_TIMEOUT_VALUE_DEPTH (1)
#define NBL_VDPA_TIMEOUT_VALUE_WIDTH (32)
#define NBL_VDPA_TIMEOUT_VALUE_DWLEN (1)
union vdpa_timeout_value_u {
	struct vdpa_timeout_value {
		u32 timeout_value:32;    /* [31:00] Default:0x190 RW */
	} __packed info;
	u32 data[NBL_VDPA_TIMEOUT_VALUE_DWLEN];
} __packed;

#define NBL_VDPA_DIF_MODE_ADDR  (0xf98124)
#define NBL_VDPA_DIF_MODE_DEPTH (1)
#define NBL_VDPA_DIF_MODE_WIDTH (32)
#define NBL_VDPA_DIF_MODE_DWLEN (1)
union vdpa_dif_mode_u {
	struct vdpa_dif_mode {
		u32 dif_mode:3;          /* [02:00] Default:0x2 RW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_DIF_MODE_DWLEN];
} __packed;

#define NBL_VDPA_DIF_INFO_ADDR  (0xf98128)
#define NBL_VDPA_DIF_INFO_DEPTH (1)
#define NBL_VDPA_DIF_INFO_WIDTH (32)
#define NBL_VDPA_DIF_INFO_DWLEN (1)
union vdpa_dif_info_u {
	struct vdpa_dif_info {
		u32 dif_info:16;         /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_DIF_INFO_DWLEN];
} __packed;

#define NBL_VDPA_DIF_BDF_ADDR  (0xf9812c)
#define NBL_VDPA_DIF_BDF_DEPTH (1)
#define NBL_VDPA_DIF_BDF_WIDTH (32)
#define NBL_VDPA_DIF_BDF_DWLEN (1)
union vdpa_dif_bdf_u {
	struct vdpa_dif_bdf {
		u32 dif_bdf:16;          /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_DIF_BDF_DWLEN];
} __packed;

#define NBL_VDPA_DIF_INT_ADDR  (0xf98130)
#define NBL_VDPA_DIF_INT_DEPTH (1)
#define NBL_VDPA_DIF_INT_WIDTH (32)
#define NBL_VDPA_DIF_INT_DWLEN (1)
union vdpa_dif_int_u {
	struct vdpa_dif_int {
		u32 dif_int:1;           /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_VDPA_DIF_INT_DWLEN];
} __packed;

#define NBL_VDPA_MDL_INFO_ADDR  (0xf98134)
#define NBL_VDPA_MDL_INFO_DEPTH (1)
#define NBL_VDPA_MDL_INFO_WIDTH (32)
#define NBL_VDPA_MDL_INFO_DWLEN (1)
union vdpa_mdl_info_u {
	struct vdpa_mdl_info {
		u32 version_id:16;       /* [15:00] Default:0x0001 RO */
		u32 prj_id:16;           /* [31:16] Default:0x0020 RO */
	} __packed info;
	u32 data[NBL_VDPA_MDL_INFO_DWLEN];
} __packed;

#define NBL_VDPA_VERSION_ADDR  (0xf98138)
#define NBL_VDPA_VERSION_DEPTH (1)
#define NBL_VDPA_VERSION_WIDTH (32)
#define NBL_VDPA_VERSION_DWLEN (1)
union vdpa_version_u {
	struct vdpa_version {
		u32 date:32;             /* [31:00] Default:0x20220615 RO */
	} __packed info;
	u32 data[NBL_VDPA_VERSION_DWLEN];
} __packed;

#endif
